using System.Security.Cryptography;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace S1Interop.Compiler;

/// <summary>
/// Emits, per closed dictionary key type used by bridged dictionary storage, a nongeneric native-injected adapter class
/// so any CLR <c>IEqualityComparer&lt;K&gt;</c> can back an <c>Il2CppSystem.Collections.Generic.Dictionary</c>.
/// </summary>
/// <remarks>
/// IL2CPP class injection cannot inject generic types, so each key type gets its own class deriving
/// <c>Il2CppSystem.Object</c> that implements <c>IEqualityComparer&lt;K&gt;</c> natively and forwards to a CLR comparer
/// held in a managed field. Key types come from the author's own bridged dictionary expressions and types; nothing is
/// hard-coded per game type.
/// <para>
/// Names carry a hash of the mod's assembly name because <c>ClassInjector</c> rejects a second injected type with the
/// same full name and every mod shares one IL2CPP domain. The class is injected lazily from its static constructor, so
/// loading the mod performs no native call; the module initializer only registers delegates with the shared runtime.
/// </para>
/// <para>
/// Ownership: the injected object holds a strong GC handle to its managed peer (which holds the CLR comparer) until the
/// native object is finalized. Once a separate interface proxy holds a strong native handle, the adapter's own handle
/// becomes weak, breaking the native/managed ownership cycle. The conditional cache adds no roots to the comparer;
/// a cached adapter whose native object has been collected is recreated on demand.
/// </para>
/// </remarks>
internal static class ComparerAdapterGeneration
{
    public const string FilePath = "S1Interop.Compiler/ComparerAdapters.g.cs";

    private const string DictionaryDefinition = "System.Collections.Generic.Dictionary<TKey, TValue>";
    private const string ComparerRegistryType = "S1Interop.Compiler.Generated.S1InteropDictionaryComparer`1";

    private const string Header = """
        // <auto-generated/>
        #nullable disable
        """;

    private const string KeyTemplate = """
        namespace __NAMESPACE__
        {
            internal static class Factory___ID__
            {
                internal static volatile bool Registered;

                private static readonly global::System.Runtime.CompilerServices.ConditionalWeakTable<global::System.Collections.Generic.IEqualityComparer<__KEY__>, Adapter___ID__> Adapters =
                    new global::System.Runtime.CompilerServices.ConditionalWeakTable<global::System.Collections.Generic.IEqualityComparer<__KEY__>, Adapter___ID__>();

                internal static global::Il2CppSystem.Collections.Generic.IEqualityComparer<__KEY__> Create(global::System.Collections.Generic.IEqualityComparer<__KEY__> comparer)
                {
                    if (comparer == null) throw new global::System.ArgumentNullException("comparer");
                    lock (Adapters)
                    {
                        Adapter___ID__ adapter;
                        if (!Adapters.TryGetValue(comparer, out adapter) || adapter.WasCollected)
                        {
                            global::S1Interop.Compiler.Generated.S1InteropInjection.ValidateWeakOwnership();
                            adapter = new Adapter___ID__(comparer);
                            var owner = adapter.Cast<global::Il2CppSystem.Collections.Generic.IEqualityComparer<__KEY__>>();
                            global::S1Interop.Compiler.Generated.S1InteropInjection.WeakenNativeReference(adapter, owner);
                            Adapters.Remove(comparer);
                            Adapters.Add(comparer, adapter);
                            return owner;
                        }
                        return adapter.Cast<global::Il2CppSystem.Collections.Generic.IEqualityComparer<__KEY__>>();
                    }
                }

                // Never touches Adapter___ID__ until it exists, so recovery cannot trigger native class injection.
                internal static global::System.Collections.Generic.IEqualityComparer<__KEY__> Recover(global::Il2CppSystem.Collections.Generic.IEqualityComparer<__KEY__> native)
                {
                    if (!Registered || native == null) return null;
                    Adapter___ID__ adapter = native.TryCast<Adapter___ID__>();
                    return adapter == null ? null : adapter.comparer;
                }
            }

            internal sealed class Adapter___ID__ : global::Il2CppSystem.Object
            {
                internal readonly global::System.Collections.Generic.IEqualityComparer<__KEY__> comparer;

                static Adapter___ID__()
                {
                    global::Il2CppInterop.Runtime.Injection.ClassInjector.RegisterTypeInIl2Cpp<Adapter___ID__>(
                        new global::Il2CppInterop.Runtime.Injection.RegisterTypeOptions
                        {
                            __LOG_SUCCESS__
                            Interfaces = new global::System.Type[] { typeof(global::Il2CppSystem.Collections.Generic.IEqualityComparer<__KEY__>) }
                        });
                    Factory___ID__.Registered = true;
                }

                public Adapter___ID__(global::System.IntPtr pointer) : base(pointer) { }

                public Adapter___ID__(global::System.Collections.Generic.IEqualityComparer<__KEY__> comparer)
                    : base(global::Il2CppInterop.Runtime.Injection.ClassInjector.DerivedConstructorPointer<Adapter___ID__>())
                {
                    global::Il2CppInterop.Runtime.Injection.ClassInjector.DerivedConstructorBody(this);
                    this.comparer = comparer;
                }

                public bool Equals(__KEY__ left, __KEY__ right) => comparer.Equals(left, right);
                public int GetHashCode(__KEY__ value) => comparer.GetHashCode(value);
            }
        }
        """;

    private const string RegistrationTemplate = """
        namespace __NAMESPACE__
        {
            internal static class Registration
            {
                [global::System.Runtime.CompilerServices.ModuleInitializer]
                internal static void Initialize()
                {
                    global::S1Interop.Compiler.Generated.S1InteropRuntimeContract.Validate(__SIGNATURE__, __MOD__);
                    __REGISTRATIONS__
                }
            }
        }
        """;

    /// <summary>
    /// Creates the adapter source, or null when the author has no bridged dictionary with an adaptable key or the
    /// target references lack the injection surface the adapters need.
    /// </summary>
    public static SyntaxTree? CreateTree(Compilation author, MetadataSymbolMap map, CollectionStorageAnalysis storage,
        CSharpParseOptions options, string runtimeSignature, CancellationToken token)
    {
        if (string.IsNullOrEmpty(runtimeSignature) || !TryResolveSurface(map, out bool logSuccess)) return null;

        SortedDictionary<string, ITypeSymbol> keys = CollectKeys(author, map, storage, token);
        if (keys.Count == 0) return null;

        string assemblyName = author.AssemblyName ?? string.Empty;
        string ns = "S1Interop.Compiler.Generated.Comparers_" + Hash(assemblyName, 10);
        var text = new StringBuilder(Header).Append('\n');
        var registrations = new StringBuilder();
        foreach ((string key, ITypeSymbol symbol) in keys)
        {
            string id = Sanitize(symbol) + "_" + Hash(assemblyName + "|" + key, 8);
            text.Append(KeyTemplate
                .Replace("__NAMESPACE__", ns)
                .Replace("__ID__", id)
                .Replace("__KEY__", key)
                .Replace("__LOG_SUCCESS__", logSuccess ? "LogSuccess = false," : string.Empty)).Append('\n');
            registrations.Append("global::S1Interop.Compiler.Generated.S1InteropDictionaryComparer<").Append(key)
                .Append(">.RegisterFactory(").Append(ns).Append(".Factory_").Append(id).Append(".Create, ")
                .Append(ns).Append(".Factory_").Append(id).Append(".Recover);\n");
        }

        text.Append(RegistrationTemplate
            .Replace("__NAMESPACE__", ns)
            .Replace("__SIGNATURE__", SyntaxFactory.Literal(runtimeSignature).ToString())
            .Replace("__MOD__", SyntaxFactory.Literal(assemblyName).ToString())
            .Replace("__REGISTRATIONS__", registrations.ToString().TrimEnd()));

        // Module initializers need C# 9; a tree may carry its own language version, so raise only this one.
        CSharpParseOptions parse = options.LanguageVersion < LanguageVersion.CSharp9
            ? options.WithLanguageVersion(LanguageVersion.CSharp9) : options;
        return CSharpSyntaxTree.ParseText(text.ToString(), parse, FilePath, Encoding.UTF8, token);
    }

    private static SortedDictionary<string, ITypeSymbol> CollectKeys(Compilation author, MetadataSymbolMap map,
        CollectionStorageAnalysis storage, CancellationToken token)
    {
        var keys = new SortedDictionary<string, ITypeSymbol>(StringComparer.Ordinal);
        foreach (SyntaxTree tree in author.SyntaxTrees)
        {
            SemanticModel model = author.GetSemanticModel(tree);
            foreach (SyntaxNode node in tree.GetRoot(token).DescendantNodes())
            {
                token.ThrowIfCancellationRequested();
                if (node is not ExpressionSyntax expression) continue;
                // TypeSyntax is an expression; written types resolve through the symbol when they have no type info.
                ITypeSymbol? type = model.GetTypeInfo(expression).Type ??
                    (node is TypeSyntax ? model.GetSymbolInfo(expression).Symbol as ITypeSymbol : null);
                if (DictionaryRoot(type) is not { } dictionary) continue;
                ITypeSymbol key = dictionary.TypeArguments[0];
                if (!Adaptable(key, map)) continue;
                if (!storage.IsBridged(expression, model) && !(node is TypeSyntax written && storage.IsBridgedType(written, model))) continue;
                string display = map.TargetDisplay(key);
                if (!keys.ContainsKey(display)) keys.Add(display, key);
            }
        }
        return keys;
    }

    // Dictionary<,>.KeyCollection/ValueCollection/Enumerator share the dictionary's key type.
    private static INamedTypeSymbol? DictionaryRoot(ITypeSymbol? type)
    {
        INamedTypeSymbol? current = type as INamedTypeSymbol;
        while (current?.ContainingType is { } owner) current = owner;
        return current is not null && current.OriginalDefinition.ToDisplayString() == DictionaryDefinition ? current : null;
    }

    // Author-declared keys remain outside this path until their native generic interface instantiation is validated.
    private static bool Adaptable(ITypeSymbol key, MetadataSymbolMap map) =>
        Closed(key) && !AuthorDeclared(key, map) &&
        (Scalar(key) || key.TypeKind == TypeKind.Enum || map.IsNative(key));

    private static bool Closed(ITypeSymbol type) => type switch
    {
        ITypeParameterSymbol => false,
        IArrayTypeSymbol array => Closed(array.ElementType),
        INamedTypeSymbol named => (named.ContainingType is null || Closed(named.ContainingType)) && named.TypeArguments.All(Closed),
        _ => true
    };

    private static bool AuthorDeclared(ITypeSymbol type, MetadataSymbolMap map) => type switch
    {
        IArrayTypeSymbol array => AuthorDeclared(array.ElementType, map),
        INamedTypeSymbol named => map.IsAuthorType(named) || named.TypeArguments.Any(argument => AuthorDeclared(argument, map)),
        _ => false
    };

    private static bool Scalar(ITypeSymbol type) => type.SpecialType is SpecialType.System_String or SpecialType.System_Boolean or
        SpecialType.System_Byte or SpecialType.System_SByte or SpecialType.System_Int16 or SpecialType.System_UInt16 or
        SpecialType.System_Int32 or SpecialType.System_UInt32 or SpecialType.System_Int64 or SpecialType.System_UInt64 or
        SpecialType.System_Single or SpecialType.System_Double or SpecialType.System_Char;

    // Verifies every member the generated source calls so an older or foreign Il2CppInterop yields "no adapters"
    // and Resolve reports the missing adapter instead of emitting code against an incompatible runtime surface.
    private static bool TryResolveSurface(MetadataSymbolMap map, out bool logSuccess)
    {
        logSuccess = false;
        INamedTypeSymbol? objectBase = map.NativeObjectBase;
        INamedTypeSymbol? registry = map.FindTargetType(ComparerRegistryType);
        INamedTypeSymbol? injector = map.FindTargetType("Il2CppInterop.Runtime.Injection.ClassInjector");
        INamedTypeSymbol? options = map.FindTargetType("Il2CppInterop.Runtime.Injection.RegisterTypeOptions");
        INamedTypeSymbol? nativeObject = map.FindTargetType("Il2CppSystem.Object");
        if (objectBase is null || registry is null || injector is null || options is null || nativeObject is null ||
            map.FindTargetType("Il2CppSystem.Collections.Generic.Dictionary`2") is null ||
            map.FindTargetType("Il2CppSystem.Collections.Generic.IEqualityComparer`1") is null ||
            map.FindTargetType("Il2CppInterop.Runtime.Injection.Il2CppInterfaceCollection") is not { } collection)
            return false;

        bool registryReady = registry.GetMembers("RegisterFactory").OfType<IMethodSymbol>()
            .Any(method => method.IsStatic && method.DeclaredAccessibility == Accessibility.Public && method.Parameters.Length == 2);
        bool pointerCtor = nativeObject.InstanceConstructors.Any(ctor => ctor.DeclaredAccessibility == Accessibility.Public &&
            ctor.Parameters.Length == 1 && ctor.Parameters[0].Type.SpecialType == SpecialType.System_IntPtr);
        bool injectorReady =
            injector.GetMembers("DerivedConstructorPointer").OfType<IMethodSymbol>().Any(method =>
                method.IsStatic && method.TypeParameters.Length == 1 && method.Parameters.Length == 0) &&
            injector.GetMembers("DerivedConstructorBody").OfType<IMethodSymbol>().Any(method =>
                method.IsStatic && method.Parameters.Length == 1) &&
            injector.GetMembers("RegisterTypeInIl2Cpp").OfType<IMethodSymbol>().Any(method =>
                method.IsStatic && method.TypeParameters.Length == 1 && method.Parameters.Length == 1 &&
                SymbolEqualityComparer.Default.Equals(method.Parameters[0].Type, options));
        bool interfaces = options.GetMembers("Interfaces").OfType<IPropertySymbol>().Any(property =>
            property.SetMethod is { DeclaredAccessibility: Accessibility.Public } &&
            SymbolEqualityComparer.Default.Equals(property.Type, collection));
        // The collection must accept a Type[] (the injected class resolves interface pointers lazily from it).
        bool fromTypes = collection.GetMembers("op_Implicit").OfType<IMethodSymbol>().Any(method =>
            method.Parameters.Length == 1 && method.Parameters[0].Type is IArrayTypeSymbol { ElementType.Name: "Type" });
        bool baseReady = objectBase.GetMembers("WasCollected").OfType<IPropertySymbol>().Any() &&
            objectBase.GetMembers("Cast").OfType<IMethodSymbol>().Any(method => method.TypeParameters.Length == 1) &&
            objectBase.GetMembers("TryCast").OfType<IMethodSymbol>().Any(method => method.TypeParameters.Length == 1);
        logSuccess = options.GetMembers("LogSuccess").OfType<IPropertySymbol>().Any(property =>
            property.SetMethod is { DeclaredAccessibility: Accessibility.Public } && property.Type.SpecialType == SpecialType.System_Boolean);
        return registryReady && pointerCtor && injectorReady && interfaces && fromTypes && baseReady;
    }

    private static string Sanitize(ITypeSymbol type)
    {
        var name = new StringBuilder("Comparer_");
        foreach (char c in type.Name)
        {
            if (name.Length >= 32) break;
            if (char.IsLetterOrDigit(c) && c < 128) name.Append(c);
        }
        return name.ToString();
    }

    private static string Hash(string value, int length) =>
        Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(value)))[..length];
}
