using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace S1Interop.Compiler;

/// <summary>Emits lazy managed enumeration over native collection metadata, without copying the collection.</summary>
internal sealed class EnumerationAdapters(MetadataSymbolMap map)
{
    private const string Helper = "global::S1Interop.Compiler.Generated.S1InteropEnumeration";
    private readonly Dictionary<string, (string Method, string Source)> adapters = new(StringComparer.Ordinal);

    public ExpressionSyntax? Adapt(ExpressionSyntax expression, INamedTypeSymbol? collection, ITypeSymbol element)
    {
        if (collection is null || ContainsTypeParameter(collection) || ContainsTypeParameter(element) ||
            collection.AllInterfaces.Any(type => type.OriginalDefinition.ToDisplayString() == "System.Collections.Generic.IEnumerable<T>"))
            return null;

        IMethodSymbol? factory = Members(collection, "GetEnumerator").OfType<IMethodSymbol>()
            .FirstOrDefault(method => !method.IsStatic && method.Parameters.Length == 0 && method.DeclaredAccessibility == Accessibility.Public);
        if (factory?.ReturnType is not INamedTypeSymbol enumerator ||
            !Members(enumerator, "MoveNext").OfType<IMethodSymbol>().Any(method => method.Parameters.Length == 0 && method.ReturnType.SpecialType == SpecialType.System_Boolean) ||
            !Members(enumerator, "Current").OfType<IPropertySymbol>().Any() ||
            !Members(enumerator, "Dispose").OfType<IMethodSymbol>().Any(method => method.Parameters.Length == 0))
            return null;

        string native = collection.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        string managedElement = map.TargetDisplay(element);
        string key = native + "|" + managedElement;
        if (!adapters.TryGetValue(key, out var adapter))
        {
            string method = "Adapt" + adapters.Count;
            string current = map.IsNative(element)
                ? $"{NativeCastHelperSource.TypeName}.Cast<{managedElement}>(enumerator.Current)"
                : "enumerator.Current";
            string source = $$"""
                public static global::System.Collections.Generic.IEnumerable<{{managedElement}}> {{method}}({{native}} source)
                {
                    if (source is null) return null;
                    return {{method}}Iterator(source);
                }
                private static global::System.Collections.Generic.IEnumerable<{{managedElement}}> {{method}}Iterator({{native}} source)
                {
                    var enumerator = source.GetEnumerator();
                    try
                    {
                        while (enumerator.MoveNext()) yield return {{current}};
                    }
                    finally
                    {
                        if (!((object)enumerator is null)) enumerator.Dispose();
                    }
                }
                """;
            adapter = (method, source);
            adapters.Add(key, adapter);
        }
        return InvocationExpression(ParseExpression(Helper + "." + adapter.Method),
            ArgumentList(SingletonSeparatedList(Argument(expression.WithoutTrivia())))).WithTriviaFrom(expression);
    }

    public SyntaxTree? CreateTree(CSharpParseOptions options, CancellationToken token)
    {
        if (adapters.Count == 0) return null;
        string nullable = options.LanguageVersion >= LanguageVersion.CSharp8 ? "#nullable disable\n" : "";
        string source = "// <auto-generated/>\n" + nullable +
            "namespace S1Interop.Compiler.Generated { internal static class S1InteropEnumeration {\n" +
            string.Join("\n", adapters.Values.Select(adapter => adapter.Source)) + "\n} }";
        return CSharpSyntaxTree.ParseText(source, options, "S1Interop.Compiler/S1InteropEnumeration.g.cs", System.Text.Encoding.UTF8, token);
    }

    private static IEnumerable<ISymbol> Members(INamedTypeSymbol type, string name)
    {
        for (var current = type; current is not null; current = current.BaseType)
            foreach (ISymbol member in current.GetMembers(name)) yield return member;
    }

    private static bool ContainsTypeParameter(ITypeSymbol type) => type switch
    {
        ITypeParameterSymbol => true,
        IArrayTypeSymbol array => ContainsTypeParameter(array.ElementType),
        INamedTypeSymbol named => named.TypeArguments.Any(ContainsTypeParameter),
        _ => false
    };
}
