using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace S1Interop.Compiler;

/// <summary>Forwards CLR collection equality to the game's own generic comparer, including overrides and IEquatable.</summary>
internal static class NativeEqualityComparerSource
{
    public const string TypeName = "global::S1Interop.Compiler.Generated.S1InteropEqualityComparer";

    private const string Body = """
        namespace S1Interop.Compiler.Generated
        {
            public interface IS1InteropDefaultEqualityComparer { }
            public sealed class S1InteropEqualityComparer<T> : global::System.Collections.Generic.EqualityComparer<T>, IS1InteropDefaultEqualityComparer
                where T : global::Il2CppInterop.Runtime.InteropTypes.Il2CppObjectBase
            {
                public static readonly S1InteropEqualityComparer<T> Instance = new S1InteropEqualityComparer<T>();
                private S1InteropEqualityComparer() { }
                public override bool Equals(T left, T right) => global::Il2CppSystem.Collections.Generic.EqualityComparer<T>.Default.Equals(left, right);
                public override int GetHashCode(T value) => global::Il2CppSystem.Collections.Generic.EqualityComparer<T>.Default.GetHashCode(value);
            }
        }
        """;

    public static SyntaxTree CreateTree(CSharpParseOptions options, CancellationToken token)
    {
        string nullable = options.LanguageVersion >= LanguageVersion.CSharp8 ? "#nullable disable\n" : "";
        return CSharpSyntaxTree.ParseText("// <auto-generated/>\n" + nullable + Body, options,
            "S1Interop.Compiler/S1InteropEqualityComparer.g.cs", System.Text.Encoding.UTF8, token);
    }
}
