using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace S1Interop.Compiler;

internal static class NativeEventRepairSource
{
    internal static SyntaxTree CreateTree(CSharpParseOptions options, CancellationToken token) => CSharpSyntaxTree.ParseText("""
        // <auto-generated/>
        #nullable disable
        namespace S1Interop.Compiler.Generated {
            public static unsafe class S1InteropEventRepair {
                private sealed class Entry {
                    internal string Field;
                    internal string Callback;
                    internal bool Add;
                    internal bool Failed;
                    internal bool IsStatic;
                    internal global::System.IntPtr NativeClass;
                    internal int Offset;
                    internal global::System.IntPtr NativeField;
                }
                private static readonly object Gate = new object();
                private static readonly global::System.Collections.Concurrent.ConcurrentDictionary<global::System.Reflection.MethodBase, Entry> Entries =
                    new global::System.Collections.Concurrent.ConcurrentDictionary<global::System.Reflection.MethodBase, Entry>();
                private static readonly global::System.Collections.Generic.Dictionary<global::System.Reflection.Module, string> Hashes =
                    new global::System.Collections.Generic.Dictionary<global::System.Reflection.Module, string>();
                private static readonly global::HarmonyLib.Harmony Patcher = new global::HarmonyLib.Harmony("S1Interop.Compiler.AtomicEvents");
                private static global::System.IntPtr compareExchange;
                private static bool staticStorageAvailable;

                public static void Install(string assemblyName, string sha256, string mvid, int token, string declaringType,
                    string fieldName, string callbackType, bool add, bool isStatic = false) {
                    lock (Gate) {
                        if (global::Il2CppInterop.Runtime.IL2CPP.il2cpp_domain_get() == global::System.IntPtr.Zero ||
                            global::Il2CppInterop.Runtime.IL2CPP.il2cpp_thread_current() == global::System.IntPtr.Zero)
                            throw new global::System.InvalidOperationException("S1IC040: Event repairs require an initialized IL2CPP domain and attached loader thread.");
                        var assembly = global::System.Reflection.Assembly.Load(assemblyName);
                        var module = assembly.ManifestModule;
                        if (module.ModuleVersionId != new global::System.Guid(mvid))
                            throw new global::System.InvalidOperationException("S1IC040: Rebuild against the installed wrapper module: " + assemblyName +
                                ". Expected MVID " + mvid + "; loaded " + module.ModuleVersionId + ".");
                        string hash;
                        if (!Hashes.TryGetValue(module, out hash)) {
                            if (global::System.String.IsNullOrEmpty(assembly.Location))
                                throw new global::System.NotSupportedException("S1IC040: Event repair cannot verify an in-memory wrapper image: " + assemblyName);
                            using (var stream = global::System.IO.File.OpenRead(assembly.Location))
                            using (var algorithm = global::System.Security.Cryptography.SHA256.Create())
                                hash = global::System.BitConverter.ToString(algorithm.ComputeHash(stream)).Replace("-", "");
                            Hashes.Add(module, hash);
                        }
                        if (hash != sha256) throw new global::System.InvalidOperationException("S1IC040: Rebuild against the installed wrapper image: " + assemblyName +
                            ". Expected SHA256 " + sha256 + "; loaded " + hash + ".");
                        var method = module.ResolveMethod(token) as global::System.Reflection.MethodInfo;
                        var parameters = method == null ? null : method.GetParameters();
                        if (method == null || method.IsStatic != isStatic || method.ContainsGenericParameters || method.DeclaringType.IsGenericType || method.ReturnType != typeof(void) ||
                            method.DeclaringType.FullName != declaringType || method.Name != (add ? "add_" : "remove_") + fieldName ||
                            parameters.Length != 1 || TypeName(parameters[0].ParameterType) != callbackType ||
                            !typeof(global::Il2CppSystem.Delegate).IsAssignableFrom(parameters[0].ParameterType) ||
                            !isStatic && !typeof(global::Il2CppInterop.Runtime.InteropTypes.Il2CppObjectBase).IsAssignableFrom(method.DeclaringType))
                            throw new global::System.InvalidOperationException("Event repair target signature mismatch.");
                        Entry existing;
                        if (Entries.TryGetValue(method, out existing)) {
                            if (existing.Failed) throw new global::System.InvalidOperationException("A previous event repair installation failed.");
                            if (existing.Field != fieldName || existing.Callback != callbackType || existing.Add != add || existing.IsStatic != isStatic)
                                throw new global::System.InvalidOperationException("Conflicting event repair descriptors.");
                            return;
                        }
                        var klass = global::Il2CppInterop.Runtime.Il2CppClassPointerStore.GetNativeClassPointer(method.DeclaringType);
                        var callbackClass = global::Il2CppInterop.Runtime.Il2CppClassPointerStore.GetNativeClassPointer(parameters[0].ParameterType);
                        if (klass == global::System.IntPtr.Zero || callbackClass == global::System.IntPtr.Zero)
                            throw new global::System.NotSupportedException("Event repair native class metadata is unavailable.");
                        var field = global::Il2CppInterop.Runtime.IL2CPP.il2cpp_class_get_field_from_name(klass, fieldName);
                        if (field == global::System.IntPtr.Zero || global::Il2CppInterop.Runtime.IL2CPP.il2cpp_field_get_parent(field) != klass ||
                            (global::Il2CppInterop.Runtime.IL2CPP.il2cpp_field_get_flags(field) & 0x60) != 0 ||
                            ((global::Il2CppInterop.Runtime.IL2CPP.il2cpp_field_get_flags(field) & 0x10) != 0) != isStatic ||
                            global::Il2CppInterop.Runtime.IL2CPP.il2cpp_class_from_type(global::Il2CppInterop.Runtime.IL2CPP.il2cpp_field_get_type(field)) !=
                                callbackClass)
                            throw new global::System.NotSupportedException("Event repair native field layout mismatch.");
                        EnsureCompareExchange();
                        int offset = unchecked((int)global::Il2CppInterop.Runtime.IL2CPP.il2cpp_field_get_offset(field));
                        if (offset < 0 || offset % global::System.IntPtr.Size != 0)
                            throw new global::System.NotSupportedException("S1IC040: Event field storage is thread-local or has an unsupported offset.");
                        if (isStatic && !staticStorageAvailable) {
                            try { StaticData(klass); }
                            catch (global::System.Exception exception) when (exception is global::System.DllNotFoundException || exception is global::System.EntryPointNotFoundException) {
                                throw new global::System.NotSupportedException("S1IC040: The installed GameAssembly does not expose static field storage.", exception);
                            }
                            staticStorageAvailable = true;
                        }
                        var entry = new Entry { Field = fieldName, Callback = callbackType, Add = add, NativeField = field, IsStatic = isStatic, NativeClass = klass, Offset = offset };
                        Entries[method] = entry;
                        try {
                            Patcher.Patch(method, prefix: new global::HarmonyLib.HarmonyMethod(typeof(S1InteropEventRepair).GetMethod(isStatic ? "StaticPrefix" : "Prefix",
                                global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.NonPublic)));
                        } catch (global::System.Exception failure) {
                            entry.Failed = true;
                            try { Patcher.Unpatch(method, typeof(S1InteropEventRepair).GetMethod(isStatic ? "StaticPrefix" : "Prefix",
                                global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.NonPublic)); }
                            catch (global::System.Exception cleanup) { throw new global::System.AggregateException("Event repair installation and cleanup failed.", failure, cleanup); }
                            // Retain the immutable descriptor for any prefix already in flight.
                            // A failed module initializer prevents this mod from proceeding.
                            throw;
                        }
                    }
                }

                private static string TypeName(global::System.Type type) {
                    if (type.IsByRef) return TypeName(type.GetElementType()) + "&";
                    if (type.IsArray) return TypeName(type.GetElementType()) + "[" + new string(',', type.GetArrayRank() - 1) + "]";
                    if (!type.IsGenericType) return type.FullName;
                    var arguments = type.GetGenericArguments();
                    var names = new string[arguments.Length];
                    for (int i = 0; i < arguments.Length; i++) names[i] = TypeName(arguments[i]);
                    return type.GetGenericTypeDefinition().FullName + "<" + string.Join(",", names) + ">";
                }

                private static void EnsureCompareExchange() {
                    if (compareExchange != global::System.IntPtr.Zero) return;
                    var method = global::Il2CppInterop.Runtime.IL2CPP.GetIl2CppMethod(
                        global::Il2CppInterop.Runtime.Il2CppClassPointerStore.GetNativeClassPointer(typeof(global::Il2CppSystem.Threading.Interlocked)),
                        false, "CompareExchange", "System.Object", "System.Object&", "System.Object", "System.Object");
                    string[] names = { "System.Object&", "System.Object", "System.Object" };
                    if (method == global::System.IntPtr.Zero || global::Il2CppInterop.Runtime.IL2CPP.il2cpp_method_get_param_count(method) != 3 ||
                        global::Il2CppInterop.Runtime.IL2CPP.il2cpp_type_get_name_(global::Il2CppInterop.Runtime.IL2CPP.il2cpp_method_get_return_type(method)) != "System.Object")
                        throw new global::System.NotSupportedException("Exact native object CompareExchange is unavailable.");
                    for (uint i = 0; i < 3; i++)
                        if (global::Il2CppInterop.Runtime.IL2CPP.il2cpp_type_get_name_(global::Il2CppInterop.Runtime.IL2CPP.il2cpp_method_get_param(method, i)) != names[i])
                            throw new global::System.NotSupportedException("Native CompareExchange signature mismatch.");
                    compareExchange = method;
                }

                private static bool Prefix(global::Il2CppInterop.Runtime.InteropTypes.Il2CppObjectBase __instance,
                    global::Il2CppSystem.Delegate __0, global::System.Reflection.MethodBase __originalMethod) {
                    var entry = Entries[__originalMethod];
                    var address = global::Il2CppInterop.Runtime.IL2CPP.Il2CppObjectBaseToPtrNotNull(__instance) +
                        entry.Offset;
                    try { return Update(address, __0, entry); }
                    finally { global::System.GC.KeepAlive(__instance); }
                }

                [global::System.Runtime.InteropServices.DllImport("GameAssembly", EntryPoint = "il2cpp_class_get_static_field_data",
                    CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
                private static extern global::System.IntPtr StaticData(global::System.IntPtr klass);

                private static bool StaticPrefix(global::Il2CppSystem.Delegate __0, global::System.Reflection.MethodBase __originalMethod) {
                    var entry = Entries[__originalMethod];
                    global::Il2CppInterop.Runtime.IL2CPP.il2cpp_runtime_class_init(entry.NativeClass);
                    var storage = StaticData(entry.NativeClass);
                    if (storage == global::System.IntPtr.Zero)
                        throw new global::System.NotSupportedException("S1IC040: Static event storage is unavailable or thread-local.");
                    return Update(storage + entry.Offset, __0, entry);
                }

                private static bool Update(global::System.IntPtr address, global::Il2CppSystem.Delegate callback, Entry entry) {
                    try {
                        while (true) {
                            var observed = global::System.Threading.Volatile.Read(ref *(global::System.IntPtr*)address);
                            var current = observed == global::System.IntPtr.Zero ? null :
                                global::Il2CppInterop.Runtime.Runtime.Il2CppObjectPool.Get<global::Il2CppSystem.Delegate>(observed);
                            var next = entry.Add ? global::Il2CppSystem.Delegate.Combine(current, callback) : global::Il2CppSystem.Delegate.Remove(current, callback);
                            if (Exchange(address, next, current) == observed) return false;
                        }
                    } finally { global::System.GC.KeepAlive(callback); }
                }

                private static global::System.IntPtr Exchange(global::System.IntPtr address, global::Il2CppSystem.Delegate next, global::Il2CppSystem.Delegate current) {
                    try {
                        global::System.IntPtr* args = stackalloc global::System.IntPtr[3];
                        args[0] = address;
                        args[1] = next is null ? global::System.IntPtr.Zero : global::Il2CppInterop.Runtime.IL2CPP.Il2CppObjectBaseToPtr(next);
                        args[2] = current is null ? global::System.IntPtr.Zero : global::Il2CppInterop.Runtime.IL2CPP.Il2CppObjectBaseToPtr(current);
                        var exception = global::System.IntPtr.Zero;
                        var result = global::Il2CppInterop.Runtime.IL2CPP.il2cpp_runtime_invoke(compareExchange, global::System.IntPtr.Zero, (void**)args, ref exception);
                        global::Il2CppInterop.Runtime.Il2CppException.RaiseExceptionIfNecessary(exception);
                        return result;
                    } finally { global::System.GC.KeepAlive(next); global::System.GC.KeepAlive(current); }
                }
            }
        }
        """, options, "S1Interop.Compiler/S1InteropEventRepair.g.cs", System.Text.Encoding.UTF8, token);
}
