using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using System.Text;

namespace S1Interop.Generators;

public sealed partial class S1InteropTypeRegistryGenerator
{
    private static void GenerateMemberRegistry(
        StringBuilder builder,
        RuntimeBackend runtime,
        ImmutableArray<S1InteropTypeEntry> entries,
        ImmutableArray<S1InteropMemberEntry> members)
    {
        builder.AppendLine();
        builder.AppendLine("    internal static class S1InteropMemberRegistry");
        builder.AppendLine("    {");
        builder.AppendLine("        private const System.Reflection.BindingFlags AllBindings = System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Static;");
        builder.AppendLine("        private static readonly System.Collections.Generic.Dictionary<string, System.Reflection.MemberInfo?> Cache = new System.Collections.Generic.Dictionary<string, System.Reflection.MemberInfo?>(System.StringComparer.Ordinal);");
        builder.AppendLine();

        foreach (S1InteropMemberEntry member in members.OrderBy(member => member.Alias, StringComparer.Ordinal))
        {
            builder.AppendLine($"        public const string {member.Alias}Name = \"{Escape(member.MemberName)}\";");
            if (member.Kind == S1InteropMemberKind.Method)
            {
                builder.AppendLine($"        public static System.Reflection.MethodInfo? {member.Alias}Method => ResolveMethod(S1InteropTypeRegistry.{member.OwnerAlias}Name, {member.Alias}Name, {GenerateParameterTypeNamesExpression(runtime, entries, member)});");
                if (member.IsStatic)
                {
                    builder.AppendLine($"        public static object? Invoke{member.Alias}(params object?[] args) => Invoke(S1InteropTypeRegistry.{member.OwnerAlias}Name, {member.Alias}Name, {GenerateParameterTypeNamesExpression(runtime, entries, member)}, null, args);");
                    builder.AppendLine($"        public static T? Invoke{member.Alias}<T>(params object?[] args) => CastResult<T>(Invoke{member.Alias}(args));");
                }
                else
                {
                    builder.AppendLine($"        public static object? Invoke{member.Alias}(object? instance, params object?[] args) => Invoke(S1InteropTypeRegistry.{member.OwnerAlias}Name, {member.Alias}Name, {GenerateParameterTypeNamesExpression(runtime, entries, member)}, instance, args);");
                    builder.AppendLine($"        public static object? Invoke{member.Alias}(S1InteropObject<S1InteropTypeRegistry.{member.OwnerAlias}Tag> instance, params object?[] args) => Invoke(S1InteropTypeRegistry.{member.OwnerAlias}Name, {member.Alias}Name, {GenerateParameterTypeNamesExpression(runtime, entries, member)}, instance.Instance, args);");
                    builder.AppendLine($"        public static T? Invoke{member.Alias}<T>(object? instance, params object?[] args) => CastResult<T>(Invoke{member.Alias}(instance, args));");
                    builder.AppendLine($"        public static T? Invoke{member.Alias}<T>(S1InteropObject<S1InteropTypeRegistry.{member.OwnerAlias}Tag> instance, params object?[] args) => CastResult<T>(Invoke{member.Alias}(instance, args));");
                }
            }
            else
            {
                string memberKind = $"S1InteropMemberKind.{member.Kind}";
                if (member.Kind is S1InteropMemberKind.Field or S1InteropMemberKind.FieldOrProperty)
                {
                    builder.AppendLine($"        public static System.Reflection.FieldInfo? {member.Alias}FieldInfo => ResolveMember(S1InteropTypeRegistry.{member.OwnerAlias}Name, {member.Alias}Name, parameterTypeNames: null, S1InteropMemberKind.Field) as System.Reflection.FieldInfo;");
                }

                if (member.Kind is S1InteropMemberKind.Property or S1InteropMemberKind.FieldOrProperty)
                {
                    builder.AppendLine($"        public static System.Reflection.PropertyInfo? {member.Alias}PropertyInfo => ResolveMember(S1InteropTypeRegistry.{member.OwnerAlias}Name, {member.Alias}Name, parameterTypeNames: null, S1InteropMemberKind.Property) as System.Reflection.PropertyInfo;");
                }

                if (member.IsStatic)
                {
                    builder.AppendLine($"        public static object? Get{member.Alias}() => GetValue(S1InteropTypeRegistry.{member.OwnerAlias}Name, {member.Alias}Name, null, {memberKind});");
                    builder.AppendLine($"        public static T? Get{member.Alias}<T>() where T : class => Get{member.Alias}() as T;");
                    builder.AppendLine($"        public static T? Get{member.Alias}Value<T>() where T : struct => Get{member.Alias}() is T value ? value : (T?)null;");
                    builder.AppendLine($"        public static bool TrySet{member.Alias}(object? value) => TrySetValue(S1InteropTypeRegistry.{member.OwnerAlias}Name, {member.Alias}Name, null, value, {memberKind});");
                }
                else
                {
                    builder.AppendLine($"        public static object? Get{member.Alias}(object instance) => GetValue(S1InteropTypeRegistry.{member.OwnerAlias}Name, {member.Alias}Name, instance, {memberKind});");
                    builder.AppendLine($"        public static object? Get{member.Alias}(S1InteropObject<S1InteropTypeRegistry.{member.OwnerAlias}Tag> instance) => GetValue(S1InteropTypeRegistry.{member.OwnerAlias}Name, {member.Alias}Name, instance.Instance, {memberKind});");
                    builder.AppendLine($"        public static T? Get{member.Alias}<T>(object instance) where T : class => Get{member.Alias}(instance) as T;");
                    builder.AppendLine($"        public static T? Get{member.Alias}<T>(S1InteropObject<S1InteropTypeRegistry.{member.OwnerAlias}Tag> instance) where T : class => Get{member.Alias}(instance) as T;");
                    builder.AppendLine($"        public static T? Get{member.Alias}Value<T>(object instance) where T : struct => Get{member.Alias}(instance) is T value ? value : (T?)null;");
                    builder.AppendLine($"        public static T? Get{member.Alias}Value<T>(S1InteropObject<S1InteropTypeRegistry.{member.OwnerAlias}Tag> instance) where T : struct => Get{member.Alias}(instance) is T value ? value : (T?)null;");
                    builder.AppendLine($"        public static bool TrySet{member.Alias}(object instance, object? value) => TrySetValue(S1InteropTypeRegistry.{member.OwnerAlias}Name, {member.Alias}Name, instance, value, {memberKind});");
                    builder.AppendLine($"        public static bool TrySet{member.Alias}(S1InteropObject<S1InteropTypeRegistry.{member.OwnerAlias}Tag> instance, object? value) => TrySetValue(S1InteropTypeRegistry.{member.OwnerAlias}Name, {member.Alias}Name, instance.Instance, value, {memberKind});");
                }
            }

            builder.AppendLine();
        }

        builder.AppendLine("        public static object? GetValue(string ownerTypeName, string memberName, object? instance)");
        builder.AppendLine("        {");
        builder.AppendLine("            return GetValue(ownerTypeName, memberName, instance, S1InteropMemberKind.FieldOrProperty);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static T? CastResult<T>(object? value)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (value is T typed)");
        builder.AppendLine("            {");
        builder.AppendLine("                return typed;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (value is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return default;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Type targetType = System.Nullable.GetUnderlyingType(typeof(T)) ?? typeof(T);");
        builder.AppendLine("            if (targetType.IsEnum)");
        builder.AppendLine("            {");
        builder.AppendLine("                try");
        builder.AppendLine("                {");
        builder.AppendLine("                    return value is string text ? (T)System.Enum.Parse(targetType, text, ignoreCase: true) : (T)System.Enum.ToObject(targetType, value);");
        builder.AppendLine("                }");
        builder.AppendLine("                catch");
        builder.AppendLine("                {");
        builder.AppendLine("                    return default;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                return (T)System.Convert.ChangeType(value, targetType, System.Globalization.CultureInfo.InvariantCulture);");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("                return default;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static object? GetInstanceValue(object? instance, string memberName)");
        builder.AppendLine("        {");
        builder.AppendLine("            return GetInstanceValue(instance, memberName, S1InteropMemberKind.FieldOrProperty);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static object? GetInstanceValue(object? instance, string memberName, S1InteropMemberKind kind)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (instance is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return null;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Reflection.MemberInfo? member = ResolveMemberCached(instance.GetType(), memberName, parameterTypeNames: null, kind);");
        builder.AppendLine("            if (member is System.Reflection.PropertyInfo property)");
        builder.AppendLine("            {");
        builder.AppendLine("                return property.GetValue(instance, null);");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (member is System.Reflection.FieldInfo field)");
        builder.AppendLine("            {");
        builder.AppendLine("                return field.GetValue(instance);");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return null;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static object? GetValue(string ownerTypeName, string memberName, object? instance, S1InteropMemberKind kind)");
        builder.AppendLine("        {");
        builder.AppendLine("            System.Reflection.MemberInfo? member = ResolveMember(ownerTypeName, memberName, parameterTypeNames: null, kind);");
        builder.AppendLine("            if (member is System.Reflection.PropertyInfo property)");
        builder.AppendLine("            {");
        builder.AppendLine("                return property.GetValue(instance, null);");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (member is System.Reflection.FieldInfo field)");
        builder.AppendLine("            {");
        builder.AppendLine("                return field.GetValue(instance);");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return null;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static bool TrySetValue(string ownerTypeName, string memberName, object? instance, object? value)");
        builder.AppendLine("        {");
        builder.AppendLine("            return TrySetValue(ownerTypeName, memberName, instance, value, S1InteropMemberKind.FieldOrProperty);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static bool TrySetInstanceValue(object? instance, string memberName, object? value)");
        builder.AppendLine("        {");
        builder.AppendLine("            return TrySetInstanceValue(instance, memberName, value, S1InteropMemberKind.FieldOrProperty);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static bool TrySetInstanceValue(object? instance, string memberName, object? value, S1InteropMemberKind kind)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (instance is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return TrySetValue(ResolveMemberCached(instance.GetType(), memberName, parameterTypeNames: null, kind), instance, value);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static bool TrySetValue(string ownerTypeName, string memberName, object? instance, object? value, S1InteropMemberKind kind)");
        builder.AppendLine("        {");
        builder.AppendLine("            System.Reflection.MemberInfo? member = ResolveMember(ownerTypeName, memberName, parameterTypeNames: null, kind);");
        builder.AppendLine("            return TrySetValue(member, instance, value);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TrySetValue(System.Reflection.MemberInfo? member, object? instance, object? value)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (member is System.Reflection.PropertyInfo property && property.CanWrite)");
        builder.AppendLine("            {");
        builder.AppendLine("                if (!TryConvertValue(value, property.PropertyType, out object? converted))");
        builder.AppendLine("                {");
        builder.AppendLine("                    return false;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                property.SetValue(instance, converted, null);");
        builder.AppendLine("                return true;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (member is System.Reflection.FieldInfo field)");
        builder.AppendLine("            {");
        builder.AppendLine("                if (!TryConvertValue(value, field.FieldType, out object? converted))");
        builder.AppendLine("                {");
        builder.AppendLine("                    return false;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                field.SetValue(instance, converted);");
        builder.AppendLine("                return true;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return false;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static bool TryConvertValue(object? value, System.Type targetType, out object? converted)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (value is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                converted = targetType.IsValueType && System.Nullable.GetUnderlyingType(targetType) is null ? System.Activator.CreateInstance(targetType) : null;");
        builder.AppendLine("                return true;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Type conversionType = System.Nullable.GetUnderlyingType(targetType) ?? targetType;");
        builder.AppendLine("            if (conversionType.IsInstanceOfType(value))");
        builder.AppendLine("            {");
        builder.AppendLine("                converted = value;");
        builder.AppendLine("                return true;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                if (TryConvertIl2CppGuid(value, conversionType, out converted))");
        builder.AppendLine("                {");
        builder.AppendLine("                    return true;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                if (TryConvertIl2CppList(value, conversionType, out converted))");
        builder.AppendLine("                {");
        builder.AppendLine("                    return true;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                if (TryConvertIl2CppHashSet(value, conversionType, out converted))");
        builder.AppendLine("                {");
        builder.AppendLine("                    return true;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                if (TryConvertIl2CppDictionary(value, conversionType, out converted))");
        builder.AppendLine("                {");
        builder.AppendLine("                    return true;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                if (TryConvertIl2CppArray(value, conversionType, out converted))");
        builder.AppendLine("                {");
        builder.AppendLine("                    return true;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                if (conversionType.IsEnum)");
        builder.AppendLine("                {");
        builder.AppendLine("                    converted = value is string text ? System.Enum.Parse(conversionType, text, ignoreCase: true) : System.Enum.ToObject(conversionType, value);");
        builder.AppendLine("                    return true;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                converted = System.Convert.ChangeType(value, conversionType, System.Globalization.CultureInfo.InvariantCulture);");
        builder.AppendLine("                return true;");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("                converted = null;");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryConvertIl2CppGuid(object value, System.Type targetType, out object? converted)");
        builder.AppendLine("        {");
        builder.AppendLine("            converted = null;");
        builder.AppendLine("            if (!string.Equals(targetType.FullName, \"Il2CppSystem.Guid\", System.StringComparison.Ordinal) || value is not System.Guid guid)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                System.Reflection.ConstructorInfo? stringConstructor = targetType.GetConstructor(new[] { typeof(string) });");
        builder.AppendLine("                if (stringConstructor is not null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    converted = stringConstructor.Invoke(new object[] { guid.ToString() });");
        builder.AppendLine("                    return true;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                System.Reflection.ConstructorInfo? byteArrayConstructor = targetType.GetConstructor(new[] { typeof(byte[]) });");
        builder.AppendLine("                if (byteArrayConstructor is not null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    converted = byteArrayConstructor.Invoke(new object[] { guid.ToByteArray() });");
        builder.AppendLine("                    return true;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("                converted = null;");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return false;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryConvertIl2CppList(object value, System.Type targetType, out object? converted)");
        builder.AppendLine("        {");
        builder.AppendLine("            converted = null;");
        builder.AppendLine("            if (targetType.FullName is null || !targetType.FullName.StartsWith(\"Il2CppSystem.Collections.Generic.List`1\", System.StringComparison.Ordinal))");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (value is string || value is not System.Collections.IEnumerable enumerable)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Type[] genericArguments = targetType.GetGenericArguments();");
        builder.AppendLine("            if (genericArguments.Length != 1)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Reflection.MethodInfo? addMethod = targetType.GetMethod(\"Add\", new[] { genericArguments[0] });");
        builder.AppendLine("            if (addMethod is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                object? list = System.Activator.CreateInstance(targetType);");
        builder.AppendLine("                if (list is null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return false;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                foreach (object? item in enumerable)");
        builder.AppendLine("                {");
        builder.AppendLine("                    if (!TryConvertValue(item, genericArguments[0], out object? convertedItem))");
        builder.AppendLine("                    {");
        builder.AppendLine("                        return false;");
        builder.AppendLine("                    }");
        builder.AppendLine();
        builder.AppendLine("                    addMethod.Invoke(list, new object?[] { convertedItem });");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                converted = list;");
        builder.AppendLine("                return true;");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("                converted = null;");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryConvertIl2CppHashSet(object value, System.Type targetType, out object? converted)");
        builder.AppendLine("        {");
        builder.AppendLine("            converted = null;");
        builder.AppendLine("            if (targetType.FullName is null || !targetType.FullName.StartsWith(\"Il2CppSystem.Collections.Generic.HashSet`1\", System.StringComparison.Ordinal))");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (value is string || value is not System.Collections.IEnumerable enumerable)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Type[] genericArguments = targetType.GetGenericArguments();");
        builder.AppendLine("            if (genericArguments.Length != 1)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Reflection.MethodInfo? addMethod = targetType.GetMethod(\"Add\", new[] { genericArguments[0] });");
        builder.AppendLine("            if (addMethod is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                object? set = System.Activator.CreateInstance(targetType);");
        builder.AppendLine("                if (set is null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return false;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                foreach (object? item in enumerable)");
        builder.AppendLine("                {");
        builder.AppendLine("                    if (!TryConvertValue(item, genericArguments[0], out object? convertedItem))");
        builder.AppendLine("                    {");
        builder.AppendLine("                        return false;");
        builder.AppendLine("                    }");
        builder.AppendLine();
        builder.AppendLine("                    addMethod.Invoke(set, new object?[] { convertedItem });");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                converted = set;");
        builder.AppendLine("                return true;");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("                converted = null;");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryConvertIl2CppDictionary(object value, System.Type targetType, out object? converted)");
        builder.AppendLine("        {");
        builder.AppendLine("            converted = null;");
        builder.AppendLine("            if (targetType.FullName is null || !targetType.FullName.StartsWith(\"Il2CppSystem.Collections.Generic.Dictionary`2\", System.StringComparison.Ordinal))");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (value is not System.Collections.IEnumerable enumerable)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Type[] genericArguments = targetType.GetGenericArguments();");
        builder.AppendLine("            if (genericArguments.Length != 2)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Reflection.MethodInfo? addMethod = targetType.GetMethod(\"Add\", new[] { genericArguments[0], genericArguments[1] });");
        builder.AppendLine("            if (addMethod is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                object? il2CppDictionary = System.Activator.CreateInstance(targetType);");
        builder.AppendLine("                if (il2CppDictionary is null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return false;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                foreach (object? entry in enumerable)");
        builder.AppendLine("                {");
        builder.AppendLine("                    if (!TryGetDictionaryEntry(entry, out object? key, out object? entryValue) ||");
        builder.AppendLine("                        !TryConvertValue(key, genericArguments[0], out object? convertedKey) ||");
        builder.AppendLine("                        !TryConvertValue(entryValue, genericArguments[1], out object? convertedValue))");
        builder.AppendLine("                    {");
        builder.AppendLine("                        return false;");
        builder.AppendLine("                    }");
        builder.AppendLine();
        builder.AppendLine("                    addMethod.Invoke(il2CppDictionary, new object?[] { convertedKey, convertedValue });");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                converted = il2CppDictionary;");
        builder.AppendLine("                return true;");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("                converted = null;");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryGetDictionaryEntry(object? entry, out object? key, out object? value)");
        builder.AppendLine("        {");
        builder.AppendLine("            key = null;");
        builder.AppendLine("            value = null;");
        builder.AppendLine("            if (entry is System.Collections.DictionaryEntry dictionaryEntry)");
        builder.AppendLine("            {");
        builder.AppendLine("                key = dictionaryEntry.Key;");
        builder.AppendLine("                value = dictionaryEntry.Value;");
        builder.AppendLine("                return true;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (entry is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Type entryType = entry.GetType();");
        builder.AppendLine("            System.Reflection.PropertyInfo? keyProperty = entryType.GetProperty(\"Key\");");
        builder.AppendLine("            System.Reflection.PropertyInfo? valueProperty = entryType.GetProperty(\"Value\");");
        builder.AppendLine("            if (keyProperty is null || valueProperty is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            key = keyProperty.GetValue(entry, null);");
        builder.AppendLine("            value = valueProperty.GetValue(entry, null);");
        builder.AppendLine("            return true;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryConvertIl2CppArray(object value, System.Type targetType, out object? converted)");
        builder.AppendLine("        {");
        builder.AppendLine("            converted = null;");
        builder.AppendLine("            if (targetType.FullName is null ||");
        builder.AppendLine("                (!targetType.FullName.StartsWith(\"Il2CppInterop.Runtime.InteropTypes.Arrays.Il2CppStructArray`1\", System.StringComparison.Ordinal) &&");
        builder.AppendLine("                 !targetType.FullName.StartsWith(\"Il2CppInterop.Runtime.InteropTypes.Arrays.Il2CppReferenceArray`1\", System.StringComparison.Ordinal)))");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (value is string || value is not System.Collections.IEnumerable enumerable)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Type[] genericArguments = targetType.GetGenericArguments();");
        builder.AppendLine("            if (genericArguments.Length != 1)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                System.Collections.Generic.List<object?> items = new System.Collections.Generic.List<object?>();");
        builder.AppendLine("                foreach (object? item in enumerable)");
        builder.AppendLine("                {");
        builder.AppendLine("                    if (!TryConvertValue(item, genericArguments[0], out object? convertedItem))");
        builder.AppendLine("                    {");
        builder.AppendLine("                        return false;");
        builder.AppendLine("                    }");
        builder.AppendLine();
        builder.AppendLine("                    items.Add(convertedItem);");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                object? array = CreateIl2CppArray(targetType, items.Count);");
        builder.AppendLine("                if (array is null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return false;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                System.Reflection.PropertyInfo? indexer = targetType.GetProperty(\"Item\", new[] { typeof(int) });");
        builder.AppendLine("                System.Reflection.MethodInfo? setItem = targetType.GetMethod(\"set_Item\", new[] { typeof(int), genericArguments[0] });");
        builder.AppendLine("                if (indexer is null && setItem is null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return false;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                for (int index = 0; index < items.Count; index++)");
        builder.AppendLine("                {");
        builder.AppendLine("                    if (indexer is not null)");
        builder.AppendLine("                    {");
        builder.AppendLine("                        indexer.SetValue(array, items[index], new object[] { index });");
        builder.AppendLine("                    }");
        builder.AppendLine("                    else");
        builder.AppendLine("                    {");
        builder.AppendLine("                        setItem!.Invoke(array, new object?[] { index, items[index] });");
        builder.AppendLine("                    }");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                converted = array;");
        builder.AppendLine("                return true;");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("                converted = null;");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static object? CreateIl2CppArray(System.Type targetType, int count)");
        builder.AppendLine("        {");
        builder.AppendLine("            System.Reflection.ConstructorInfo? intConstructor = targetType.GetConstructor(new[] { typeof(int) });");
        builder.AppendLine("            if (intConstructor is not null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return intConstructor.Invoke(new object[] { count });");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Reflection.ConstructorInfo? longConstructor = targetType.GetConstructor(new[] { typeof(long) });");
        builder.AppendLine("            return longConstructor?.Invoke(new object[] { (long)count });");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static object? Invoke(string ownerTypeName, string memberName, string[]? parameterTypeNames, object? instance, params object?[] args)");
        builder.AppendLine("        {");
        builder.AppendLine("            return Invoke(ResolveMethod(ownerTypeName, memberName, parameterTypeNames), instance, args);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static object? InvokeInstance(object? instance, string memberName, params object?[] args)");
        builder.AppendLine("        {");
        builder.AppendLine("            return InvokeInstance(instance, memberName, null, args);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static object? InvokeInstance(object? instance, string memberName, string[]? parameterTypeNames, params object?[] args)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (instance is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return null;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return Invoke(ResolveMemberCached(instance.GetType(), memberName, parameterTypeNames, S1InteropMemberKind.Method) as System.Reflection.MethodInfo, instance, args);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static object? Invoke(System.Reflection.MethodInfo? method, object? instance, params object?[] args)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (method is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return null;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (!TryConvertArguments(method.GetParameters(), args, out object?[] converted))");
        builder.AppendLine("            {");
        builder.AppendLine("                return null;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            object? result = method.Invoke(instance, converted);");
        builder.AppendLine("            CopyByRefArguments(method.GetParameters(), converted, args);");
        builder.AppendLine("            return result;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryConvertArguments(System.Reflection.ParameterInfo[] parameters, object?[] args, out object?[] converted)");
        builder.AppendLine("        {");
        builder.AppendLine("            converted = System.Array.Empty<object?>();");
        builder.AppendLine("            if (parameters.Length != args.Length)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            converted = new object?[args.Length];");
        builder.AppendLine("            for (int index = 0; index < args.Length; index++)");
        builder.AppendLine("            {");
        builder.AppendLine("                System.Type parameterType = parameters[index].ParameterType;");
        builder.AppendLine("                System.Type conversionType = parameterType.IsByRef && parameterType.GetElementType() is System.Type elementType");
        builder.AppendLine("                    ? elementType");
        builder.AppendLine("                    : parameterType;");
        builder.AppendLine("                if (!TryConvertValue(args[index], conversionType, out object? convertedValue))");
        builder.AppendLine("                {");
        builder.AppendLine("                    return false;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                converted[index] = convertedValue;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return true;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static void CopyByRefArguments(System.Reflection.ParameterInfo[] parameters, object?[] converted, object?[] args)");
        builder.AppendLine("        {");
        builder.AppendLine("            int count = System.Math.Min(System.Math.Min(parameters.Length, converted.Length), args.Length);");
        builder.AppendLine("            for (int index = 0; index < count; index++)");
        builder.AppendLine("            {");
        builder.AppendLine("                if (parameters[index].ParameterType.IsByRef)");
        builder.AppendLine("                {");
        builder.AppendLine("                    args[index] = ConvertBackValue(args[index], converted[index]);");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static object? ConvertBackValue(object? original, object? converted)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (converted is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return null;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (original is System.Guid && TryConvertBackGuid(converted, out System.Guid guid))");
        builder.AppendLine("            {");
        builder.AppendLine("                return guid;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (original is System.Array originalArray && TryConvertBackArray(originalArray, converted, out System.Array? managedArray))");
        builder.AppendLine("            {");
        builder.AppendLine("                return managedArray;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (original is System.Collections.IList originalList && TryConvertBackList(originalList, converted, out System.Collections.IList? managedList))");
        builder.AppendLine("            {");
        builder.AppendLine("                return managedList;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (TryConvertBackDictionary(original, converted, out object? managedDictionary))");
        builder.AppendLine("            {");
        builder.AppendLine("                return managedDictionary;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (TryConvertBackHashSet(original, converted, out object? managedHashSet))");
        builder.AppendLine("            {");
        builder.AppendLine("                return managedHashSet;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return converted;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryConvertBackGuid(object converted, out System.Guid guid)");
        builder.AppendLine("        {");
        builder.AppendLine("            guid = default;");
        builder.AppendLine("            if (!string.Equals(converted.GetType().FullName, \"Il2CppSystem.Guid\", System.StringComparison.Ordinal))");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            object? value = converted.GetType().GetProperty(\"Value\")?.GetValue(converted, null);");
        builder.AppendLine("            string? text = value as string ?? converted.ToString();");
        builder.AppendLine("            return text is not null && System.Guid.TryParse(text, out guid);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryConvertBackArray(System.Array original, object converted, out System.Array? managedArray)");
        builder.AppendLine("        {");
        builder.AppendLine("            managedArray = null;");
        builder.AppendLine("            System.Type convertedType = converted.GetType();");
        builder.AppendLine("            if (convertedType.FullName is null ||");
        builder.AppendLine("                (!convertedType.FullName.StartsWith(\"Il2CppInterop.Runtime.InteropTypes.Arrays.Il2CppStructArray`1\", System.StringComparison.Ordinal) &&");
        builder.AppendLine("                 !convertedType.FullName.StartsWith(\"Il2CppInterop.Runtime.InteropTypes.Arrays.Il2CppReferenceArray`1\", System.StringComparison.Ordinal)))");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Reflection.PropertyInfo? lengthProperty = convertedType.GetProperty(\"Length\");");
        builder.AppendLine("            System.Reflection.PropertyInfo? indexer = convertedType.GetProperty(\"Item\", new[] { typeof(int) });");
        builder.AppendLine("            if (lengthProperty?.GetValue(converted, null) is not int length || indexer is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Type elementType = original.GetType().GetElementType() ?? typeof(object);");
        builder.AppendLine("            System.Array result = System.Array.CreateInstance(elementType, length);");
        builder.AppendLine("            for (int index = 0; index < length; index++)");
        builder.AppendLine("            {");
        builder.AppendLine("                object? item = indexer.GetValue(converted, new object[] { index });");
        builder.AppendLine("                if (!TryConvertValue(item, elementType, out object? managedItem))");
        builder.AppendLine("                {");
        builder.AppendLine("                    return false;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                result.SetValue(managedItem, index);");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            managedArray = result;");
        builder.AppendLine("            return true;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryConvertBackList(System.Collections.IList original, object converted, out System.Collections.IList? managedList)");
        builder.AppendLine("        {");
        builder.AppendLine("            managedList = null;");
        builder.AppendLine("            System.Type convertedType = converted.GetType();");
        builder.AppendLine("            if (convertedType.FullName is null || !convertedType.FullName.StartsWith(\"Il2CppSystem.Collections.Generic.List`1\", System.StringComparison.Ordinal))");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Reflection.PropertyInfo? countProperty = convertedType.GetProperty(\"Count\");");
        builder.AppendLine("            System.Reflection.PropertyInfo? indexer = convertedType.GetProperty(\"Item\", new[] { typeof(int) });");
        builder.AppendLine("            if (countProperty?.GetValue(converted, null) is not int count || indexer is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Collections.IList? result = CreateManagedList(original);");
        builder.AppendLine("            if (result is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Type elementType = GetListElementType(result.GetType()) ?? typeof(object);");
        builder.AppendLine("            for (int index = 0; index < count; index++)");
        builder.AppendLine("            {");
        builder.AppendLine("                object? item = indexer.GetValue(converted, new object[] { index });");
        builder.AppendLine("                if (!TryConvertValue(item, elementType, out object? managedItem))");
        builder.AppendLine("                {");
        builder.AppendLine("                    return false;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                result.Add(managedItem);");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            managedList = result;");
        builder.AppendLine("            return true;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static System.Collections.IList? CreateManagedList(System.Collections.IList original)");
        builder.AppendLine("        {");
        builder.AppendLine("            System.Type originalType = original.GetType();");
        builder.AppendLine("            if (!original.IsFixedSize && !original.IsReadOnly)");
        builder.AppendLine("            {");
        builder.AppendLine("                System.Collections.IList? recreated = System.Activator.CreateInstance(originalType) as System.Collections.IList;");
        builder.AppendLine("                if (recreated is not null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return recreated;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Type elementType = GetListElementType(originalType) ?? typeof(object);");
        builder.AppendLine("            System.Type listType = typeof(System.Collections.Generic.List<>).MakeGenericType(elementType);");
        builder.AppendLine("            return System.Activator.CreateInstance(listType) as System.Collections.IList;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static System.Type? GetListElementType(System.Type listType)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (listType.IsGenericType)");
        builder.AppendLine("            {");
        builder.AppendLine("                System.Type[] arguments = listType.GetGenericArguments();");
        builder.AppendLine("                if (arguments.Length == 1)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return arguments[0];");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            foreach (System.Type interfaceType in listType.GetInterfaces())");
        builder.AppendLine("            {");
        builder.AppendLine("                if (interfaceType.IsGenericType && interfaceType.GetGenericTypeDefinition() == typeof(System.Collections.Generic.IList<>))");
        builder.AppendLine("                {");
        builder.AppendLine("                    return interfaceType.GetGenericArguments()[0];");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return null;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryConvertBackDictionary(object? original, object converted, out object? managedDictionary)");
        builder.AppendLine("        {");
        builder.AppendLine("            managedDictionary = null;");
        builder.AppendLine("            if (original is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Type convertedType = converted.GetType();");
        builder.AppendLine("            if (convertedType.FullName is null || !convertedType.FullName.StartsWith(\"Il2CppSystem.Collections.Generic.Dictionary`2\", System.StringComparison.Ordinal))");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (!TryGetDictionaryTypes(original.GetType(), out System.Type? keyType, out System.Type? valueType))");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine("            if (keyType is null || valueType is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            object? result = CreateManagedDictionary(original, keyType, valueType);");
        builder.AppendLine("            if (result is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Reflection.MethodInfo? addMethod = result.GetType().GetMethod(\"Add\", new[] { keyType, valueType });");
        builder.AppendLine("            if (addMethod is null && result is not System.Collections.IDictionary)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                object? enumerator = convertedType.GetMethod(\"GetEnumerator\", System.Type.EmptyTypes)?.Invoke(converted, null);");
        builder.AppendLine("                if (enumerator is null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return false;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                System.Type enumeratorType = enumerator.GetType();");
        builder.AppendLine("                System.Reflection.MethodInfo? moveNext = enumeratorType.GetMethod(\"MoveNext\", System.Type.EmptyTypes);");
        builder.AppendLine("                System.Reflection.PropertyInfo? currentProperty = enumeratorType.GetProperty(\"Current\");");
        builder.AppendLine("                if (moveNext is null || currentProperty is null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return false;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                while (moveNext.Invoke(enumerator, null) is true)");
        builder.AppendLine("                {");
        builder.AppendLine("                    object? entry = currentProperty.GetValue(enumerator, null);");
        builder.AppendLine("                    if (!TryGetDictionaryEntry(entry, out object? key, out object? value) ||");
        builder.AppendLine("                        !TryConvertValue(key, keyType, out object? managedKey) ||");
        builder.AppendLine("                        !TryConvertValue(value, valueType, out object? managedValue))");
        builder.AppendLine("                    {");
        builder.AppendLine("                        return false;");
        builder.AppendLine("                    }");
        builder.AppendLine();
        builder.AppendLine("                    if (result is System.Collections.IDictionary dictionary)");
        builder.AppendLine("                    {");
        builder.AppendLine("                        dictionary.Add(managedKey, managedValue);");
        builder.AppendLine("                    }");
        builder.AppendLine("                    else");
        builder.AppendLine("                    {");
        builder.AppendLine("                        addMethod!.Invoke(result, new object?[] { managedKey, managedValue });");
        builder.AppendLine("                    }");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            managedDictionary = result;");
        builder.AppendLine("            return true;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static object? CreateManagedDictionary(object original, System.Type keyType, System.Type valueType)");
        builder.AppendLine("        {");
        builder.AppendLine("            System.Type originalType = original.GetType();");
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                object? recreated = System.Activator.CreateInstance(originalType);");
        builder.AppendLine("                if (recreated is not null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return recreated;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Type dictionaryType = typeof(System.Collections.Generic.Dictionary<,>).MakeGenericType(keyType, valueType);");
        builder.AppendLine("            return System.Activator.CreateInstance(dictionaryType);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryGetDictionaryTypes(System.Type dictionaryType, out System.Type? keyType, out System.Type? valueType)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (dictionaryType.IsGenericType)");
        builder.AppendLine("            {");
        builder.AppendLine("                System.Type[] arguments = dictionaryType.GetGenericArguments();");
        builder.AppendLine("                if (arguments.Length == 2)");
        builder.AppendLine("                {");
        builder.AppendLine("                    keyType = arguments[0];");
        builder.AppendLine("                    valueType = arguments[1];");
        builder.AppendLine("                    return true;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            foreach (System.Type interfaceType in dictionaryType.GetInterfaces())");
        builder.AppendLine("            {");
        builder.AppendLine("                if (interfaceType.IsGenericType && interfaceType.GetGenericTypeDefinition() == typeof(System.Collections.Generic.IDictionary<,>))");
        builder.AppendLine("                {");
        builder.AppendLine("                    System.Type[] arguments = interfaceType.GetGenericArguments();");
        builder.AppendLine("                    keyType = arguments[0];");
        builder.AppendLine("                    valueType = arguments[1];");
        builder.AppendLine("                    return true;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            keyType = null;");
        builder.AppendLine("            valueType = null;");
        builder.AppendLine("            return false;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryConvertBackHashSet(object? original, object converted, out object? managedHashSet)");
        builder.AppendLine("        {");
        builder.AppendLine("            managedHashSet = null;");
        builder.AppendLine("            if (original is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Type convertedType = converted.GetType();");
        builder.AppendLine("            if (convertedType.FullName is null || !convertedType.FullName.StartsWith(\"Il2CppSystem.Collections.Generic.HashSet`1\", System.StringComparison.Ordinal))");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Type? elementType = GetSetElementType(original.GetType());");
        builder.AppendLine("            if (elementType is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            object? result = CreateManagedHashSet(original, elementType);");
        builder.AppendLine("            if (result is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Reflection.MethodInfo? addMethod = result.GetType().GetMethod(\"Add\", new[] { elementType });");
        builder.AppendLine("            if (addMethod is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                object? enumerator = convertedType.GetMethod(\"GetEnumerator\", System.Type.EmptyTypes)?.Invoke(converted, null);");
        builder.AppendLine("                if (enumerator is null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return false;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                System.Type enumeratorType = enumerator.GetType();");
        builder.AppendLine("                System.Reflection.MethodInfo? moveNext = enumeratorType.GetMethod(\"MoveNext\", System.Type.EmptyTypes);");
        builder.AppendLine("                System.Reflection.PropertyInfo? currentProperty = enumeratorType.GetProperty(\"Current\");");
        builder.AppendLine("                if (moveNext is null || currentProperty is null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return false;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                while (moveNext.Invoke(enumerator, null) is true)");
        builder.AppendLine("                {");
        builder.AppendLine("                    object? item = currentProperty.GetValue(enumerator, null);");
        builder.AppendLine("                    if (!TryConvertValue(item, elementType, out object? managedItem))");
        builder.AppendLine("                    {");
        builder.AppendLine("                        return false;");
        builder.AppendLine("                    }");
        builder.AppendLine();
        builder.AppendLine("                    addMethod.Invoke(result, new object?[] { managedItem });");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            managedHashSet = result;");
        builder.AppendLine("            return true;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static object? CreateManagedHashSet(object original, System.Type elementType)");
        builder.AppendLine("        {");
        builder.AppendLine("            System.Type originalType = original.GetType();");
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                object? recreated = System.Activator.CreateInstance(originalType);");
        builder.AppendLine("                if (recreated is not null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return recreated;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Type setType = typeof(System.Collections.Generic.HashSet<>).MakeGenericType(elementType);");
        builder.AppendLine("            return System.Activator.CreateInstance(setType);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static System.Type? GetSetElementType(System.Type setType)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (setType.IsGenericType)");
        builder.AppendLine("            {");
        builder.AppendLine("                System.Type[] arguments = setType.GetGenericArguments();");
        builder.AppendLine("                if (arguments.Length == 1)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return arguments[0];");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            foreach (System.Type interfaceType in setType.GetInterfaces())");
        builder.AppendLine("            {");
        builder.AppendLine("                if (interfaceType.IsGenericType && interfaceType.GetGenericTypeDefinition() == typeof(System.Collections.Generic.ISet<>))");
        builder.AppendLine("                {");
        builder.AppendLine("                    return interfaceType.GetGenericArguments()[0];");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return null;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static System.Reflection.MethodInfo? ResolveMethod(string ownerTypeName, string memberName, string[]? parameterTypeNames)");
        builder.AppendLine("        {");
        builder.AppendLine("            return ResolveMember(ownerTypeName, memberName, parameterTypeNames, S1InteropMemberKind.Method) as System.Reflection.MethodInfo;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static System.Reflection.MemberInfo? ResolveMember(string ownerTypeName, string memberName, string[]? parameterTypeNames, S1InteropMemberKind kind)");
        builder.AppendLine("        {");
        builder.AppendLine("            string cacheKey = ownerTypeName + \"::\" + memberName + \"::\" + ((int)kind).ToString() + \"::\" + (parameterTypeNames is null ? string.Empty : string.Join(\"|\", parameterTypeNames));");
        builder.AppendLine("            if (!Cache.TryGetValue(cacheKey, out System.Reflection.MemberInfo? member))");
        builder.AppendLine("            {");
        builder.AppendLine("                System.Type? ownerType = S1InteropTypeRegistry.Resolve(ownerTypeName);");
        builder.AppendLine("                member = ownerType is null");
        builder.AppendLine("                    ? null");
        builder.AppendLine("                    : ResolveMember(ownerType, memberName, parameterTypeNames, kind);");
        builder.AppendLine("                Cache[cacheKey] = member;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return member;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static System.Reflection.MemberInfo? ResolveMemberCached(System.Type ownerType, string memberName, string[]? parameterTypeNames, S1InteropMemberKind kind)");
        builder.AppendLine("        {");
        builder.AppendLine("            string ownerKey = ownerType.AssemblyQualifiedName ?? ownerType.FullName ?? ownerType.Name;");
        builder.AppendLine("            string cacheKey = ownerKey + \"::\" + memberName + \"::\" + ((int)kind).ToString() + \"::\" + (parameterTypeNames is null ? string.Empty : string.Join(\"|\", parameterTypeNames));");
        builder.AppendLine("            if (!Cache.TryGetValue(cacheKey, out System.Reflection.MemberInfo? member))");
        builder.AppendLine("            {");
        builder.AppendLine("                member = ResolveMember(ownerType, memberName, parameterTypeNames, kind);");
        builder.AppendLine("                Cache[cacheKey] = member;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return member;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static System.Reflection.MemberInfo? ResolveMember(System.Type ownerType, string memberName, string[]? parameterTypeNames, S1InteropMemberKind kind)");
        builder.AppendLine("        {");
        builder.AppendLine("            switch (kind)");
        builder.AppendLine("            {");
        builder.AppendLine("                case S1InteropMemberKind.Method:");
        builder.AppendLine("                    return ResolveMethod(ownerType, memberName, parameterTypeNames);");
        builder.AppendLine("                case S1InteropMemberKind.Field:");
        builder.AppendLine("                    return ownerType.GetField(memberName, AllBindings);");
        builder.AppendLine("                case S1InteropMemberKind.Property:");
        builder.AppendLine("                    return ownerType.GetProperty(memberName, AllBindings);");
        builder.AppendLine("                default:");
        builder.AppendLine("                    return ownerType.GetProperty(memberName, AllBindings) ?? (System.Reflection.MemberInfo?)ownerType.GetField(memberName, AllBindings);");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static System.Reflection.MethodInfo? ResolveMethod(System.Type ownerType, string memberName, string[]? parameterTypeNames)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (parameterTypeNames is null || parameterTypeNames.Length == 0)");
        builder.AppendLine("            {");
        builder.AppendLine("                return ownerType.GetMethod(memberName, AllBindings);");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Type[]? parameterTypes = ResolveParameterTypes(parameterTypeNames);");
        builder.AppendLine("            return parameterTypes is null ? null : ownerType.GetMethod(memberName, AllBindings, binder: null, types: parameterTypes, modifiers: null);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static System.Type[]? ResolveParameterTypes(string[] parameterTypeNames)");
        builder.AppendLine("        {");
        builder.AppendLine("            var parameterTypes = new System.Type[parameterTypeNames.Length];");
        builder.AppendLine("            for (int index = 0; index < parameterTypeNames.Length; index++)");
        builder.AppendLine("            {");
        builder.AppendLine("                string parameterTypeName = parameterTypeNames[index];");
        builder.AppendLine("                bool byRef = parameterTypeName.EndsWith(\"&\", System.StringComparison.Ordinal);");
        builder.AppendLine("                if (byRef)");
        builder.AppendLine("                {");
        builder.AppendLine("                    parameterTypeName = parameterTypeName.Substring(0, parameterTypeName.Length - 1);");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                System.Type? parameterType = ResolveKnownType(parameterTypeName);");
        builder.AppendLine("                if (parameterType is null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return null;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                parameterTypes[index] = byRef ? parameterType.MakeByRefType() : parameterType;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return parameterTypes;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static System.Type? ResolveKnownType(string typeName)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (TryResolveArrayType(typeName, out System.Type? arrayType))");
        builder.AppendLine("            {");
        builder.AppendLine("                return arrayType;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (TryResolveGenericListType(typeName, out System.Type? genericListType))");
        builder.AppendLine("            {");
        builder.AppendLine("                return genericListType;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (TryResolveGenericHashSetType(typeName, out System.Type? genericHashSetType))");
        builder.AppendLine("            {");
        builder.AppendLine("                return genericHashSetType;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (TryResolveGenericDictionaryType(typeName, out System.Type? genericDictionaryType))");
        builder.AppendLine("            {");
        builder.AppendLine("                return genericDictionaryType;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            switch (typeName)");
        builder.AppendLine("            {");
        builder.AppendLine("                case \"System.Guid\": return typeof(System.Guid);");
        builder.AppendLine("                case \"bool\": return typeof(bool);");
        builder.AppendLine("                case \"byte\": return typeof(byte);");
        builder.AppendLine("                case \"char\": return typeof(char);");
        builder.AppendLine("                case \"double\": return typeof(double);");
        builder.AppendLine("                case \"float\": return typeof(float);");
        builder.AppendLine("                case \"int\": return typeof(int);");
        builder.AppendLine("                case \"long\": return typeof(long);");
        builder.AppendLine("                case \"object\": return typeof(object);");
        builder.AppendLine("                case \"short\": return typeof(short);");
        builder.AppendLine("                case \"string\": return typeof(string);");
        builder.AppendLine("                case \"uint\": return typeof(uint);");
        builder.AppendLine("                case \"ulong\": return typeof(ulong);");
        builder.AppendLine("                case \"void\": return typeof(void);");
        builder.AppendLine("                default: return S1InteropTypeRegistry.Resolve(typeName);");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryResolveArrayType(string typeName, out System.Type? resolvedType)");
        builder.AppendLine("        {");
        builder.AppendLine("            resolvedType = null;");
        builder.AppendLine("            const string structArrayPrefix = \"Il2CppInterop.Runtime.InteropTypes.Arrays.Il2CppStructArray<\";");
        builder.AppendLine("            const string referenceArrayPrefix = \"Il2CppInterop.Runtime.InteropTypes.Arrays.Il2CppReferenceArray<\";");
        builder.AppendLine("            if (typeName.EndsWith(\"[]\", System.StringComparison.Ordinal))");
        builder.AppendLine("            {");
        builder.AppendLine("                System.Type? elementType = ResolveKnownType(typeName.Substring(0, typeName.Length - 2));");
        builder.AppendLine("                if (elementType is null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return false;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                resolvedType = elementType.MakeArrayType();");
        builder.AppendLine("                return true;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            string genericDefinitionName;");
        builder.AppendLine("            string elementTypeName;");
        builder.AppendLine("            if (typeName.StartsWith(structArrayPrefix, System.StringComparison.Ordinal) && typeName.EndsWith(\">\", System.StringComparison.Ordinal))");
        builder.AppendLine("            {");
        builder.AppendLine("                genericDefinitionName = \"Il2CppInterop.Runtime.InteropTypes.Arrays.Il2CppStructArray`1\";");
        builder.AppendLine("                elementTypeName = typeName.Substring(structArrayPrefix.Length, typeName.Length - structArrayPrefix.Length - 1);");
        builder.AppendLine("            }");
        builder.AppendLine("            else if (typeName.StartsWith(referenceArrayPrefix, System.StringComparison.Ordinal) && typeName.EndsWith(\">\", System.StringComparison.Ordinal))");
        builder.AppendLine("            {");
        builder.AppendLine("                genericDefinitionName = \"Il2CppInterop.Runtime.InteropTypes.Arrays.Il2CppReferenceArray`1\";");
        builder.AppendLine("                elementTypeName = typeName.Substring(referenceArrayPrefix.Length, typeName.Length - referenceArrayPrefix.Length - 1);");
        builder.AppendLine("            }");
        builder.AppendLine("            else");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Type? genericDefinition = S1InteropTypeRegistry.Resolve(genericDefinitionName);");
        builder.AppendLine("            System.Type? genericElementType = ResolveKnownType(elementTypeName);");
        builder.AppendLine("            if (genericDefinition is null || genericElementType is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            resolvedType = genericDefinition.MakeGenericType(genericElementType);");
        builder.AppendLine("            return true;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryResolveGenericHashSetType(string typeName, out System.Type? resolvedType)");
        builder.AppendLine("        {");
        builder.AppendLine("            resolvedType = null;");
        builder.AppendLine("            const string monoPrefix = \"System.Collections.Generic.HashSet<\";");
        builder.AppendLine("            const string il2CppPrefix = \"Il2CppSystem.Collections.Generic.HashSet<\";");
        builder.AppendLine("            string genericDefinitionName;");
        builder.AppendLine("            string elementTypeName;");
        builder.AppendLine("            if (typeName.StartsWith(monoPrefix, System.StringComparison.Ordinal) && typeName.EndsWith(\">\", System.StringComparison.Ordinal))");
        builder.AppendLine("            {");
        builder.AppendLine("                genericDefinitionName = \"System.Collections.Generic.HashSet`1\";");
        builder.AppendLine("                elementTypeName = typeName.Substring(monoPrefix.Length, typeName.Length - monoPrefix.Length - 1);");
        builder.AppendLine("            }");
        builder.AppendLine("            else if (typeName.StartsWith(il2CppPrefix, System.StringComparison.Ordinal) && typeName.EndsWith(\">\", System.StringComparison.Ordinal))");
        builder.AppendLine("            {");
        builder.AppendLine("                genericDefinitionName = \"Il2CppSystem.Collections.Generic.HashSet`1\";");
        builder.AppendLine("                elementTypeName = typeName.Substring(il2CppPrefix.Length, typeName.Length - il2CppPrefix.Length - 1);");
        builder.AppendLine("            }");
        builder.AppendLine("            else");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Type? genericDefinition = S1InteropTypeRegistry.Resolve(genericDefinitionName);");
        builder.AppendLine("            System.Type? elementType = ResolveKnownType(elementTypeName);");
        builder.AppendLine("            if (genericDefinition is null || elementType is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            resolvedType = genericDefinition.MakeGenericType(elementType);");
        builder.AppendLine("            return true;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryResolveGenericDictionaryType(string typeName, out System.Type? resolvedType)");
        builder.AppendLine("        {");
        builder.AppendLine("            resolvedType = null;");
        builder.AppendLine("            const string monoPrefix = \"System.Collections.Generic.Dictionary<\";");
        builder.AppendLine("            const string il2CppPrefix = \"Il2CppSystem.Collections.Generic.Dictionary<\";");
        builder.AppendLine("            string genericDefinitionName;");
        builder.AppendLine("            string argumentsText;");
        builder.AppendLine("            if (typeName.StartsWith(monoPrefix, System.StringComparison.Ordinal) && typeName.EndsWith(\">\", System.StringComparison.Ordinal))");
        builder.AppendLine("            {");
        builder.AppendLine("                genericDefinitionName = \"System.Collections.Generic.Dictionary`2\";");
        builder.AppendLine("                argumentsText = typeName.Substring(monoPrefix.Length, typeName.Length - monoPrefix.Length - 1);");
        builder.AppendLine("            }");
        builder.AppendLine("            else if (typeName.StartsWith(il2CppPrefix, System.StringComparison.Ordinal) && typeName.EndsWith(\">\", System.StringComparison.Ordinal))");
        builder.AppendLine("            {");
        builder.AppendLine("                genericDefinitionName = \"Il2CppSystem.Collections.Generic.Dictionary`2\";");
        builder.AppendLine("                argumentsText = typeName.Substring(il2CppPrefix.Length, typeName.Length - il2CppPrefix.Length - 1);");
        builder.AppendLine("            }");
        builder.AppendLine("            else");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            string[] genericArguments = SplitGenericArguments(argumentsText);");
        builder.AppendLine("            if (genericArguments.Length != 2)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Type? genericDefinition = S1InteropTypeRegistry.Resolve(genericDefinitionName);");
        builder.AppendLine("            System.Type? keyType = ResolveKnownType(genericArguments[0]);");
        builder.AppendLine("            System.Type? valueType = ResolveKnownType(genericArguments[1]);");
        builder.AppendLine("            if (genericDefinition is null || keyType is null || valueType is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            resolvedType = genericDefinition.MakeGenericType(keyType, valueType);");
        builder.AppendLine("            return true;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static string[] SplitGenericArguments(string argumentsText)");
        builder.AppendLine("        {");
        builder.AppendLine("            System.Collections.Generic.List<string> arguments = new System.Collections.Generic.List<string>();");
        builder.AppendLine("            int depth = 0;");
        builder.AppendLine("            int start = 0;");
        builder.AppendLine("            for (int index = 0; index < argumentsText.Length; index++)");
        builder.AppendLine("            {");
        builder.AppendLine("                char character = argumentsText[index];");
        builder.AppendLine("                if (character == '<')");
        builder.AppendLine("                {");
        builder.AppendLine("                    depth++;");
        builder.AppendLine("                }");
        builder.AppendLine("                else if (character == '>')");
        builder.AppendLine("                {");
        builder.AppendLine("                    depth--;");
        builder.AppendLine("                }");
        builder.AppendLine("                else if (character == ',' && depth == 0)");
        builder.AppendLine("                {");
        builder.AppendLine("                    arguments.Add(argumentsText.Substring(start, index - start).Trim());");
        builder.AppendLine("                    start = index + 1;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            arguments.Add(argumentsText.Substring(start).Trim());");
        builder.AppendLine("            return arguments.ToArray();");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryResolveGenericListType(string typeName, out System.Type? resolvedType)");
        builder.AppendLine("        {");
        builder.AppendLine("            resolvedType = null;");
        builder.AppendLine("            const string monoPrefix = \"System.Collections.Generic.List<\";");
        builder.AppendLine("            const string il2CppPrefix = \"Il2CppSystem.Collections.Generic.List<\";");
        builder.AppendLine("            string genericDefinitionName;");
        builder.AppendLine("            string elementTypeName;");
        builder.AppendLine("            if (typeName.StartsWith(monoPrefix, System.StringComparison.Ordinal) && typeName.EndsWith(\">\", System.StringComparison.Ordinal))");
        builder.AppendLine("            {");
        builder.AppendLine("                genericDefinitionName = \"System.Collections.Generic.List`1\";");
        builder.AppendLine("                elementTypeName = typeName.Substring(monoPrefix.Length, typeName.Length - monoPrefix.Length - 1);");
        builder.AppendLine("            }");
        builder.AppendLine("            else if (typeName.StartsWith(il2CppPrefix, System.StringComparison.Ordinal) && typeName.EndsWith(\">\", System.StringComparison.Ordinal))");
        builder.AppendLine("            {");
        builder.AppendLine("                genericDefinitionName = \"Il2CppSystem.Collections.Generic.List`1\";");
        builder.AppendLine("                elementTypeName = typeName.Substring(il2CppPrefix.Length, typeName.Length - il2CppPrefix.Length - 1);");
        builder.AppendLine("            }");
        builder.AppendLine("            else");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Type? genericDefinition = S1InteropTypeRegistry.Resolve(genericDefinitionName);");
        builder.AppendLine("            System.Type? elementType = ResolveKnownType(elementTypeName);");
        builder.AppendLine("            if (genericDefinition is null || elementType is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            resolvedType = genericDefinition.MakeGenericType(elementType);");
        builder.AppendLine("            return true;");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
    }

    private static string GenerateParameterTypeNamesExpression(
        RuntimeBackend runtime,
        ImmutableArray<S1InteropTypeEntry> entries,
        S1InteropMemberEntry member)
    {
        if (member.ParameterTypeNames.IsDefaultOrEmpty)
        {
            return "null";
        }

        var parts = member.ParameterTypeNames
            .Select(parameter => GenerateParameterTypeNameExpression(runtime, entries, parameter));
        return "new string[] { " + string.Join(", ", parts) + " }";
    }

    private static string GenerateParameterTypeNameExpression(
        RuntimeBackend runtime,
        ImmutableArray<S1InteropTypeEntry> entries,
        string parameterTypeName)
    {
        bool byRef = parameterTypeName.EndsWith("&", StringComparison.Ordinal);
        string normalized = byRef ? parameterTypeName.Substring(0, parameterTypeName.Length - 1) : parameterTypeName;
        string sanitized = SanitizeIdentifier(normalized);
        S1InteropTypeEntry? matchingEntry = FindEntryByAlias(entries, sanitized);
        if (matchingEntry.HasValue)
        {
            return byRef
                ? $"S1InteropTypeRegistry.{matchingEntry.Value.Alias}Name + \"&\""
                : $"S1InteropTypeRegistry.{matchingEntry.Value.Alias}Name";
        }

        if (runtime == RuntimeBackend.Unknown)
        {
            string monoTypeName = normalized;
            string il2CppTypeName = ToIl2CppTypeName(normalized);
            if (string.Equals(monoTypeName, il2CppTypeName, StringComparison.Ordinal))
            {
                return $"\"{Escape(monoTypeName + (byRef ? "&" : string.Empty))}\"";
            }

            string expression = $"S1InteropTypeRegistry.GetRuntimeTypeName(\"{Escape(monoTypeName)}\", \"{Escape(il2CppTypeName)}\")";
            return byRef ? expression + " + \"&\"" : expression;
        }

        string runtimeTypeName = runtime == RuntimeBackend.Il2Cpp
            ? ToIl2CppTypeName(normalized)
            : normalized;
        return $"\"{Escape(runtimeTypeName + (byRef ? "&" : string.Empty))}\"";
    }

    private static S1InteropTypeEntry? FindEntryByAlias(ImmutableArray<S1InteropTypeEntry> entries, string alias)
    {
        foreach (S1InteropTypeEntry entry in entries)
        {
            if (string.Equals(entry.Alias, alias, StringComparison.Ordinal))
            {
                return entry;
            }
        }

        return null;
    }
}
