using System.Text;

namespace S1Interop.Generators;

public sealed partial class S1InteropTypeRegistryGenerator
{
    private static string GenerateAttributeSource()
    {
        return QualifySystemNamespaceReferences(
            """
        // <auto-generated />
        // Generated by S1Interop.Generators. Do not edit by hand.

        #nullable enable

        namespace S1Interop
        {
            [System.AttributeUsage(System.AttributeTargets.Assembly | System.AttributeTargets.Class | System.AttributeTargets.Struct, AllowMultiple = true)]
            internal sealed class S1InteropTypeAttribute : System.Attribute
            {
                public S1InteropTypeAttribute(string monoTypeName)
                {
                    MonoTypeName = monoTypeName;
                }

                public string MonoTypeName { get; }

                public string? Il2CppTypeName { get; set; }

                public string? Alias { get; set; }
            }

            internal enum S1InteropMemberKind
            {
                FieldOrProperty = 0,
                Method = 1,
                Field = 2,
                Property = 3
            }

            [System.AttributeUsage(System.AttributeTargets.Assembly, AllowMultiple = true)]
            internal sealed class S1InteropMemberAttribute : System.Attribute
            {
                public S1InteropMemberAttribute(string ownerAlias, string memberName)
                {
                    OwnerAlias = ownerAlias;
                    MemberName = memberName;
                }

                public string OwnerAlias { get; }

                public string MemberName { get; }

                public string? Alias { get; set; }

                public S1InteropMemberKind Kind { get; set; }

                public bool IsStatic { get; set; }

                public string[] ParameterTypeNames { get; set; } = System.Array.Empty<string>();
            }

            [System.AttributeUsage(System.AttributeTargets.Assembly, AllowMultiple = false)]
            internal sealed class S1InteropGenerateUnityEventBridgeAttribute : System.Attribute
            {
            }

            [System.AttributeUsage(System.AttributeTargets.Assembly, AllowMultiple = false)]
            internal sealed class S1InteropGenerateDelegateEventBridgeAttribute : System.Attribute
            {
            }
        }
        """);
    }

    private static string GenerateUnityEventBridgeSource()
    {
        return QualifySystemNamespaceReferences(
            """
        // <auto-generated />
        // Generated by S1Interop.Generators. Do not edit by hand.

        namespace S1Interop.Generated
        {
        internal static class S1InteropUnityEventBridge
        {
            private static readonly System.Collections.Generic.Dictionary<object, System.Collections.Generic.Dictionary<System.Delegate, System.Delegate>> WrappedListeners =
                new System.Collections.Generic.Dictionary<object, System.Collections.Generic.Dictionary<System.Delegate, System.Delegate>>();

            public static void Add(UnityEngine.Events.UnityEvent unityEvent, System.Action listener)
            {
                if (object.ReferenceEquals(unityEvent, null) || object.ReferenceEquals(listener, null) || HasWrapper(unityEvent, listener))
                {
                    return;
                }

        #if IL2CPP
                System.Action wrapped = new System.Action(listener);
                unityEvent.AddListener(wrapped);
        #else
                UnityEngine.Events.UnityAction wrapped = new UnityEngine.Events.UnityAction(listener);
                unityEvent.AddListener(wrapped);
        #endif
                StoreWrapper(unityEvent, listener, wrapped);
            }

            public static void Remove(UnityEngine.Events.UnityEvent unityEvent, System.Action listener)
            {
                System.Delegate wrapped;
                if (object.ReferenceEquals(unityEvent, null) || object.ReferenceEquals(listener, null) || !TryRemoveWrapper(unityEvent, listener, out wrapped))
                {
                    return;
                }

        #if IL2CPP
                if (wrapped is System.Action action)
                {
                    unityEvent.RemoveListener(action);
                }
        #else
                if (wrapped is UnityEngine.Events.UnityAction action)
                {
                    unityEvent.RemoveListener(action);
                }
        #endif
            }

            public static void Add<T0>(UnityEngine.Events.UnityEvent<T0> unityEvent, System.Action<T0> listener)
            {
                if (object.ReferenceEquals(unityEvent, null) || object.ReferenceEquals(listener, null) || HasWrapper(unityEvent, listener))
                {
                    return;
                }

        #if IL2CPP
                System.Action<T0> wrapped = new System.Action<T0>(listener);
                unityEvent.AddListener(wrapped);
        #else
                UnityEngine.Events.UnityAction<T0> wrapped = new UnityEngine.Events.UnityAction<T0>(listener);
                unityEvent.AddListener(wrapped);
        #endif
                StoreWrapper(unityEvent, listener, wrapped);
            }

            public static void Remove<T0>(UnityEngine.Events.UnityEvent<T0> unityEvent, System.Action<T0> listener)
            {
                System.Delegate wrapped;
                if (object.ReferenceEquals(unityEvent, null) || object.ReferenceEquals(listener, null) || !TryRemoveWrapper(unityEvent, listener, out wrapped))
                {
                    return;
                }

        #if IL2CPP
                if (wrapped is System.Action<T0> action)
                {
                    unityEvent.RemoveListener(action);
                }
        #else
                if (wrapped is UnityEngine.Events.UnityAction<T0> action)
                {
                    unityEvent.RemoveListener(action);
                }
        #endif
            }

            private static bool HasWrapper(object unityEvent, System.Delegate listener) =>
                WrappedListeners.TryGetValue(unityEvent, out System.Collections.Generic.Dictionary<System.Delegate, System.Delegate> listeners) &&
                listeners.ContainsKey(listener);

            private static void StoreWrapper(object unityEvent, System.Delegate listener, System.Delegate wrapped)
            {
                System.Collections.Generic.Dictionary<System.Delegate, System.Delegate> listeners;
                if (!WrappedListeners.TryGetValue(unityEvent, out listeners))
                {
                    listeners = new System.Collections.Generic.Dictionary<System.Delegate, System.Delegate>();
                    WrappedListeners[unityEvent] = listeners;
                }

                listeners[listener] = wrapped;
            }

            private static bool TryRemoveWrapper(object unityEvent, System.Delegate listener, out System.Delegate wrapped)
            {
                wrapped = null;
                System.Collections.Generic.Dictionary<System.Delegate, System.Delegate> listeners;
                if (!WrappedListeners.TryGetValue(unityEvent, out listeners) ||
                    !listeners.TryGetValue(listener, out wrapped))
                {
                    return false;
                }

                listeners.Remove(listener);
                if (listeners.Count == 0)
                {
                    WrappedListeners.Remove(unityEvent);
                }

                return true;
            }
        }
        }
        """);
    }

    private static string GenerateDelegateEventBridgeSource()
    {
        return QualifySystemNamespaceReferences(
            """
        // <auto-generated />
        // Generated by S1Interop.Generators. Do not edit by hand.

        namespace S1Interop.Generated
        {
        internal static class S1InteropDelegateEventBridge
        {
            public static TDelegate Combine<TDelegate>(TDelegate current, System.Delegate listener) where TDelegate : class
            {
                return (TDelegate)(object)System.Delegate.Combine(current as System.Delegate, listener);
            }

            public static TDelegate Remove<TDelegate>(TDelegate current, System.Delegate listener) where TDelegate : class
            {
                return (TDelegate)(object)System.Delegate.Remove(current as System.Delegate, listener);
            }
        }
        }
        """);
    }
}
