using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace S1Interop.Generators;

public sealed partial class S1InteropTypeRegistryGenerator
{
    private static string GenerateHarmonyPatchSource(ImmutableArray<S1InteropPatchEntry> patches)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("// Generated by S1Interop.Generators. Do not edit by hand.");
        builder.AppendLine();
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("#if NETSTANDARD2_0 || NETSTANDARD2_1 || NETFRAMEWORK");
        builder.AppendLine("namespace System.Runtime.CompilerServices");
        builder.AppendLine("{");
        builder.AppendLine("    [System.AttributeUsage(System.AttributeTargets.Method, Inherited = false)]");
        builder.AppendLine("    internal sealed class ModuleInitializerAttribute : System.Attribute");
        builder.AppendLine("    {");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        builder.AppendLine("#endif");
        builder.AppendLine();
        builder.AppendLine("namespace S1Interop.Generated");
        builder.AppendLine("{");
        builder.AppendLine("    internal static class S1InteropHarmonyPatcher");
        builder.AppendLine("    {");
        builder.AppendLine("        private const System.Reflection.BindingFlags PatchMethodBindings = System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static | System.Reflection.BindingFlags.Instance;");
        builder.AppendLine("        private static bool Applied;");
        builder.AppendLine();
        builder.AppendLine("        [System.Runtime.CompilerServices.ModuleInitializer]");
        builder.AppendLine("        internal static void InitializeGeneratedPatches()");
        builder.AppendLine("        {");
        builder.AppendLine("            ApplyGeneratedPatches();");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        internal static void ApplyGeneratedPatches()");
        builder.AppendLine("        {");
        builder.AppendLine("            string harmonyId = System.Reflection.Assembly.GetExecutingAssembly().GetName().Name ?? \"S1Interop.Generated\";");
        builder.AppendLine("            ApplyGeneratedPatches(new HarmonyLib.Harmony(harmonyId + \".S1Interop\"));");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        internal static void ApplyGeneratedPatches(HarmonyLib.Harmony harmony)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (harmony is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                throw new System.ArgumentNullException(nameof(harmony));");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (Applied)");
        builder.AppendLine("            {");
        builder.AppendLine("                return;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            Applied = true;");

        int patchIndex = 0;
        foreach (S1InteropPatchEntry patch in patches)
        {
            builder.AppendLine($"            ApplyPatch{patchIndex.ToString("D4", System.Globalization.CultureInfo.InvariantCulture)}(harmony);");
            patchIndex++;
        }

        builder.AppendLine("        }");
        builder.AppendLine();

        patchIndex = 0;
        foreach (S1InteropPatchEntry patch in patches)
        {
            GeneratePatchMethod(builder, patch, patchIndex);
            patchIndex++;
        }

        builder.AppendLine("        private static HarmonyLib.HarmonyMethod? CreateHarmonyMethod(System.Type declaringType, string methodName)");
        builder.AppendLine("        {");
        builder.AppendLine("            foreach (System.Reflection.MethodInfo method in declaringType.GetMethods(PatchMethodBindings))");
        builder.AppendLine("            {");
        builder.AppendLine("                if (string.Equals(method.Name, methodName, System.StringComparison.Ordinal))");
        builder.AppendLine("                {");
        builder.AppendLine("                    return new HarmonyLib.HarmonyMethod(method);");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return null;");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine("}");

        return QualifySystemNamespaceReferences(builder.ToString());
    }

    private static void GeneratePatchMethod(StringBuilder builder, S1InteropPatchEntry patch, int index)
    {
        string suffix = index.ToString("D4", System.Globalization.CultureInfo.InvariantCulture);
        builder.AppendLine($"        private static void ApplyPatch{suffix}(HarmonyLib.Harmony harmony)");
        builder.AppendLine("        {");
        builder.AppendLine($"            System.Reflection.MethodInfo? original = S1InteropMemberRegistry.{patch.TargetMemberEntry.Alias}Method;");
        builder.AppendLine("            if (original is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine(GenerateHandlerLocal(patch, S1InteropPatchHandlerKind.Prefix, "prefix"));
        builder.AppendLine(GenerateHandlerLocal(patch, S1InteropPatchHandlerKind.Postfix, "postfix"));
        builder.AppendLine(GenerateHandlerLocal(patch, S1InteropPatchHandlerKind.Finalizer, "finalizer"));
        builder.AppendLine("            if (prefix is null && postfix is null && finalizer is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            harmony.Patch(original, prefix: prefix, postfix: postfix, transpiler: null, finalizer: finalizer);");
        builder.AppendLine("        }");
        builder.AppendLine();
    }

    private static string GenerateHandlerLocal(S1InteropPatchEntry patch, S1InteropPatchHandlerKind kind, string localName)
    {
        foreach (S1InteropPatchHandlerEntry handler in patch.Handlers)
        {
            if (handler.Kind == kind)
            {
                return $"            HarmonyLib.HarmonyMethod? {localName} = CreateHarmonyMethod(typeof({patch.PatchTypeName}), \"{Escape(handler.MethodName)}\");";
            }
        }

        return $"            HarmonyLib.HarmonyMethod? {localName} = null;";
    }
}
