using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace S1Interop.Generators;

/// <summary>
/// Emits typed helpers for builds whose runtime is known at compile time. Each helper has the same name and call
/// shape on Mono and IL2CPP, so one source file compiles for both configurations without <c>#if</c> blocks; the
/// generated body is direct code for the current runtime rather than reflection.
/// </summary>
public sealed partial class S1InteropTypeRegistryGenerator
{
    private const string Il2CppObjectBase = "global::Il2CppInterop.Runtime.InteropTypes.Il2CppObjectBase";
    private const string ManagedList = "global::System.Collections.Generic.List";
    private const string ManagedDictionary = "global::System.Collections.Generic.Dictionary";
    private const string ManagedEnumerable = "global::System.Collections.Generic.IEnumerable";
    private const string ManagedKeyValuePair = "global::System.Collections.Generic.KeyValuePair";
    private const string Il2CppList = "global::Il2CppSystem.Collections.Generic.List";
    private const string Il2CppDictionary = "global::Il2CppSystem.Collections.Generic.Dictionary";

    private static void AddRuntimeHelperSources(
        SourceProductionContext context,
        GeneratorBuildOptions options,
        RuntimeHelperCapabilities capabilities)
    {
        if (options.Runtime == RuntimeBackend.Unknown || !options.CanEmitGeneratedCode)
        {
            return;
        }

        if (options.EmitRuntimeHelpers)
        {
            string? helpers = GenerateRuntimeHelperSource(options.Runtime, capabilities);
            if (helpers is not null)
            {
                context.AddSource("S1Interop.RuntimeHelpers.g.cs", SourceText.From(helpers, Encoding.UTF8));
            }
        }

        if (options.EmitPlatformDomain && capabilities.CanDeclarePlatformDomain)
        {
            string domain = options.Runtime == RuntimeBackend.Il2Cpp ? "IL2CPP" : "MONO";
            context.AddSource(
                "S1Interop.PlatformDomain.g.cs",
                SourceText.From(
                    $$"""
                    // <auto-generated />
                    // Generated by S1Interop.Generators because this build sets S1InteropTargetRuntime. Set
                    // S1InteropEmitPlatformDomain to false, or declare MelonPlatformDomain yourself, to opt out.

                    [assembly: global::MelonLoader.MelonPlatformDomain(global::MelonLoader.MelonPlatformDomainAttribute.CompatibleDomains.{{domain}})]

                    """,
                    Encoding.UTF8));
        }
    }

    private static string? GenerateRuntimeHelperSource(RuntimeBackend runtime, RuntimeHelperCapabilities capabilities)
    {
        bool il2Cpp = runtime == RuntimeBackend.Il2Cpp;
        bool emitCasts = !il2Cpp || capabilities.HasIl2CppObjectBase;
        var body = new StringBuilder();

        if (emitCasts)
        {
            AppendCastExtensions(body, il2Cpp, capabilities.HasNotNullWhen);
        }

        AppendCollectionExtensions(body, il2Cpp && capabilities.HasIl2CppList, il2Cpp && capabilities.HasIl2CppDictionary);

        if (capabilities.HasUnityEvent)
        {
            AppendUnityEventExtensions(body, capabilities.UnityActionIsDelegate);
        }

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine($"// Generated by S1Interop.Generators for {(il2Cpp ? "IL2CPP" : "Mono")} builds. Do not edit by hand.");
        builder.AppendLine("// Import with `using S1Interop;`. Set S1InteropEmitRuntimeHelpers to false to opt out.");
        builder.AppendLine();
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("namespace S1Interop");
        builder.AppendLine("{");
        builder.Append(body);
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendCastExtensions(StringBuilder builder, bool il2Cpp, bool hasNotNullWhen)
    {
        string constraint = il2Cpp ? Il2CppObjectBase : "class";
        string notNullWhen = hasNotNullWhen ? "[global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] " : string.Empty;
        string tryCastBody = il2Cpp
            ? $$"""
                        if (value is T typed)
                        {
                            return typed;
                        }

                        // IL2CPP proxies are typed by the declared wrapper, not the native object's runtime class.
                        return value is {{Il2CppObjectBase}} il2CppObject ? il2CppObject.TryCast<T>() : null;
            """
            : """
                        return value as T;
            """;

        builder.AppendLine(
            $$"""
                /// <summary>
                /// Casts game objects with the same calls on both runtimes. IL2CPP builds unwrap Il2CppInterop proxies the
                /// way <c>Il2CppObjectBase.TryCast</c> does; Mono builds use an ordinary C# cast.
                /// </summary>
                internal static class S1InteropCastExtensions
                {
                    /// <summary>
                    /// Returns <paramref name="value"/> as <typeparamref name="T"/>, or <see langword="null"/> when it is not one.
                    /// Use this instead of <c>is</c>, <c>as</c>, or a C# cast, which fail for IL2CPP proxies of derived types.
                    /// </summary>
                    public static T? TryCast<T>(this object? value) where T : {{constraint}}
                    {
            {{tryCastBody}}
                    }

                    /// <summary>
                    /// Returns <paramref name="value"/> as <typeparamref name="T"/>.
                    /// </summary>
                    /// <exception cref="global::System.InvalidCastException">The value is null or is not a <typeparamref name="T"/>.</exception>
                    public static T Cast<T>(this object? value) where T : {{constraint}} =>
                        TryCast<T>(value) ?? throw new global::System.InvalidCastException(
                            $"Cannot cast {value?.GetType().FullName ?? "null"} to {typeof(T).FullName}.");

                    /// <summary>
                    /// Tests whether <paramref name="value"/> is a <typeparamref name="T"/> and returns it when it is.
                    /// </summary>
                    public static bool Is<T>(this object? value, {{notNullWhen}}out T? result) where T : {{constraint}}
                    {
                        result = TryCast<T>(value);
                        return result != null;
                    }
                }

            """);
    }

    private static void AppendCollectionExtensions(StringBuilder builder, bool il2CppList, bool il2CppDictionary)
    {
        builder.AppendLine(
            $$"""
                /// <summary>
                /// Converts between managed collections and the collection types game APIs use: <c>System.Collections.Generic</c>
                /// on Mono and <c>Il2CppSystem.Collections.Generic</c> on IL2CPP.
                /// </summary>
                internal static class S1InteropCollectionExtensions
                {
                    /// <summary>
                    /// Copies a sequence into a new managed list.
                    /// </summary>
                    public static {{ManagedList}}<T> ToManagedList<T>(this {{ManagedEnumerable}}<T>? source) =>
                        source is null ? new {{ManagedList}}<T>() : new {{ManagedList}}<T>(source);

                    /// <summary>
                    /// Copies key/value pairs into a new managed dictionary.
                    /// </summary>
                    public static {{ManagedDictionary}}<TKey, TValue> ToManagedDictionary<TKey, TValue>(
                        this {{ManagedEnumerable}}<{{ManagedKeyValuePair}}<TKey, TValue>>? source)
                        where TKey : notnull
                    {
                        var result = new {{ManagedDictionary}}<TKey, TValue>();
                        if (source != null)
                        {
                            foreach ({{ManagedKeyValuePair}}<TKey, TValue> pair in source)
                            {
                                result[pair.Key] = pair.Value;
                            }
                        }

                        return result;
                    }
            """);

        if (il2CppList)
        {
            builder.AppendLine(
                $$"""

                        /// <summary>
                        /// Enumerates an IL2CPP list so LINQ can query it. Mono lists already support LINQ through the same call.
                        /// </summary>
                        public static {{ManagedEnumerable}}<T> AsEnumerable<T>(this {{Il2CppList}}<T>? list)
                        {
                            if (list is null)
                            {
                                yield break;
                            }

                            for (int index = 0; index < list.Count; index++)
                            {
                                yield return list[index];
                            }
                        }

                        /// <summary>
                        /// Copies an IL2CPP list into a new managed list.
                        /// </summary>
                        public static {{ManagedList}}<T> ToManagedList<T>(this {{Il2CppList}}<T>? list)
                        {
                            var result = new {{ManagedList}}<T>(list?.Count ?? 0);
                            if (list != null)
                            {
                                for (int index = 0; index < list.Count; index++)
                                {
                                    result.Add(list[index]);
                                }
                            }

                            return result;
                        }

                        /// <summary>
                        /// Copies a sequence into the list type IL2CPP game APIs accept.
                        /// </summary>
                        public static {{Il2CppList}}<T> ToNativeList<T>(this {{ManagedEnumerable}}<T>? source)
                        {
                            var result = new {{Il2CppList}}<T>();
                            if (source != null)
                            {
                                foreach (T item in source)
                                {
                                    result.Add(item);
                                }
                            }

                            return result;
                        }
                """);
        }
        else
        {
            builder.AppendLine(
                $$"""

                        /// <summary>
                        /// Copies a sequence into the list type game APIs accept. On Mono that is a managed list.
                        /// </summary>
                        public static {{ManagedList}}<T> ToNativeList<T>(this {{ManagedEnumerable}}<T>? source) => ToManagedList(source);
                """);
        }

        if (il2CppDictionary)
        {
            builder.AppendLine(
                $$"""

                        /// <summary>
                        /// Enumerates an IL2CPP dictionary as managed key/value pairs so LINQ can query it.
                        /// </summary>
                        public static {{ManagedEnumerable}}<{{ManagedKeyValuePair}}<TKey, TValue>> AsEnumerable<TKey, TValue>(
                            this {{Il2CppDictionary}}<TKey, TValue>? dictionary)
                        {
                            if (dictionary is null)
                            {
                                yield break;
                            }

                            foreach (var entry in dictionary)
                            {
                                yield return new {{ManagedKeyValuePair}}<TKey, TValue>(entry.Key, entry.Value);
                            }
                        }

                        /// <summary>
                        /// Copies an IL2CPP dictionary into a new managed dictionary.
                        /// </summary>
                        public static {{ManagedDictionary}}<TKey, TValue> ToManagedDictionary<TKey, TValue>(
                            this {{Il2CppDictionary}}<TKey, TValue>? dictionary)
                            where TKey : notnull =>
                            dictionary.AsEnumerable().ToManagedDictionary();
                """);
        }

        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void AppendUnityEventExtensions(StringBuilder builder, bool unityActionIsDelegate)
    {
        // IL2CPP delegates are wrapper classes with an implicit conversion from the matching System delegate.
        string convert = unityActionIsDelegate ? "new global::UnityEngine.Events.UnityAction(action)" : "action";
        string convertGeneric = unityActionIsDelegate ? "new global::UnityEngine.Events.UnityAction<T0>(action)" : "action";

        builder.AppendLine(
            $$"""
                /// <summary>
                /// Registers UnityEvent listeners with the same calls on both runtimes.
                /// </summary>
                /// <remarks>
                /// IL2CPP cannot convert a lambda to <c>UnityAction</c>, so <c>button.onClick.AddListener(() => ...)</c> only
                /// compiles there through these overloads. Removing an IL2CPP listener needs the exact converted delegate that was
                /// added; use <c>Subscribe</c> and dispose the result instead of calling <c>RemoveListener</c> with a lambda or Action.
                /// </remarks>
                internal static class S1InteropUnityEventExtensions
                {
                    /// <summary>
                    /// Adds a listener written as a lambda or <see cref="global::System.Action"/>.
                    /// </summary>
                    public static void AddListener(this global::UnityEngine.Events.UnityEvent unityEvent, global::System.Action listener) =>
                        unityEvent.AddListener(listener.ToUnityAction());

                    /// <summary>
                    /// Adds a listener written as a lambda or <see cref="global::System.Action{T}"/>.
                    /// </summary>
                    public static void AddListener<T0>(this global::UnityEngine.Events.UnityEvent<T0> unityEvent, global::System.Action<T0> listener) =>
                        unityEvent.AddListener(listener.ToUnityAction());

                    /// <summary>
                    /// Adds a listener and returns a handle that removes exactly that listener when disposed.
                    /// </summary>
                    public static global::System.IDisposable Subscribe(this global::UnityEngine.Events.UnityEvent unityEvent, global::System.Action listener)
                    {
                        global::UnityEngine.Events.UnityAction converted = listener.ToUnityAction();
                        unityEvent.AddListener(converted);
                        return new S1InteropListenerSubscription(() => unityEvent.RemoveListener(converted));
                    }

                    /// <summary>
                    /// Adds a listener and returns a handle that removes exactly that listener when disposed.
                    /// </summary>
                    public static global::System.IDisposable Subscribe<T0>(this global::UnityEngine.Events.UnityEvent<T0> unityEvent, global::System.Action<T0> listener)
                    {
                        global::UnityEngine.Events.UnityAction<T0> converted = listener.ToUnityAction();
                        unityEvent.AddListener(converted);
                        return new S1InteropListenerSubscription(() => unityEvent.RemoveListener(converted));
                    }

                    /// <summary>
                    /// Converts an action to the runtime's <c>UnityAction</c> type.
                    /// </summary>
                    public static global::UnityEngine.Events.UnityAction ToUnityAction(this global::System.Action action)
                    {
                        if (action is null)
                        {
                            throw new global::System.ArgumentNullException(nameof(action));
                        }

                        return {{convert}};
                    }

                    /// <summary>
                    /// Converts an action to the runtime's <c>UnityAction&lt;T0&gt;</c> type.
                    /// </summary>
                    public static global::UnityEngine.Events.UnityAction<T0> ToUnityAction<T0>(this global::System.Action<T0> action)
                    {
                        if (action is null)
                        {
                            throw new global::System.ArgumentNullException(nameof(action));
                        }

                        return {{convertGeneric}};
                    }
                }

                internal sealed class S1InteropListenerSubscription : global::System.IDisposable
                {
                    private global::System.Action? remove;

                    public S1InteropListenerSubscription(global::System.Action remove)
                    {
                        this.remove = remove;
                    }

                    public void Dispose() => global::System.Threading.Interlocked.Exchange(ref remove, null)?.Invoke();
                }
            """);
    }

    private static void AddIl2CppInjectedTypeSource(
        SourceProductionContext context,
        Il2CppInjectedTypeEntry entry,
        GeneratorBuildOptions options)
    {
        if (options.Runtime != RuntimeBackend.Il2Cpp || !options.CanEmitGeneratedCode || entry.HasIntPtrConstructor)
        {
            return;
        }

        if (!entry.CanExtend || !entry.BaseHasIntPtrConstructor)
        {
            context.ReportDiagnostic(Diagnostic.Create(InjectedTypeConstructorDiagnostic, entry.Location, entry.Name));
            return;
        }

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("// Generated by S1Interop.Generators for IL2CPP builds. Do not edit by hand.");
        builder.AppendLine();
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        var openings = new List<string>();
        if (entry.NamespaceName is not null)
        {
            openings.Add($"namespace {entry.NamespaceName}");
        }

        openings.AddRange(entry.ContainingTypeDeclarations);
        openings.Add($"partial class {entry.Name}");
        for (int depth = 0; depth < openings.Count; depth++)
        {
            string indent = new(' ', depth * 4);
            builder.AppendLine($"{indent}{openings[depth]}");
            builder.AppendLine($"{indent}{{");
        }

        string member = new(' ', openings.Count * 4);
        builder.AppendLine($"{member}/// <summary>");
        builder.AppendLine($"{member}/// Wraps a native instance of this injected type. Il2CppInterop calls this; mod code does not.");
        builder.AppendLine($"{member}/// </summary>");
        builder.AppendLine($"{member}public {entry.Name}(global::System.IntPtr pointer) : base(pointer)");
        builder.AppendLine($"{member}{{");
        builder.AppendLine($"{member}}}");
        if (entry.NeedsManagedConstructor)
        {
            builder.AppendLine();
            builder.AppendLine($"{member}/// <summary>");
            builder.AppendLine($"{member}/// Creates a native instance from managed code, replacing the implicit constructor the Mono build has.");
            builder.AppendLine($"{member}/// </summary>");
            builder.AppendLine($"{member}public {entry.Name}()");
            builder.AppendLine($"{member}    : base(global::Il2CppInterop.Runtime.Injection.ClassInjector.DerivedConstructorPointer<{entry.Name}>())");
            builder.AppendLine($"{member}{{");
            builder.AppendLine($"{member}    global::Il2CppInterop.Runtime.Injection.ClassInjector.DerivedConstructorBody(this);");
            builder.AppendLine($"{member}}}");
        }

        for (int depth = openings.Count - 1; depth >= 0; depth--)
        {
            builder.AppendLine($"{new string(' ', depth * 4)}}}");
        }

        context.AddSource(
            $"S1Interop.Il2CppInjected.{SanitizeHintName(entry.MetadataName)}.g.cs",
            SourceText.From(builder.ToString(), Encoding.UTF8));
    }

    private static string SanitizeHintName(string value)
    {
        var builder = new StringBuilder(value.Length);
        foreach (char character in value)
        {
            builder.Append(char.IsLetterOrDigit(character) || character is '.' or '_' ? character : '_');
        }

        return builder.ToString();
    }
}
