using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

namespace S1Interop.Generators;

public sealed partial class S1InteropTypeRegistryGenerator
{
    private static string GenerateRegistrySource(
        RuntimeBackend runtime,
        ImmutableArray<S1InteropTypeEntry> entries,
        ImmutableArray<S1InteropMemberEntry> members)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("// Generated by S1Interop.Generators. Do not edit by hand.");
        builder.AppendLine();
        builder.AppendLine("#nullable enable annotations");
        builder.AppendLine("#nullable disable warnings");
        builder.AppendLine();
        builder.AppendLine("namespace S1Interop.Generated");
        builder.AppendLine("{");
        builder.AppendLine("    internal enum S1InteropRuntimeBackend");
        builder.AppendLine("    {");
        builder.AppendLine("        Unknown = 0,");
        builder.AppendLine("        Mono = 1,");
        builder.AppendLine("        Il2Cpp = 2");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    internal static class S1InteropRuntime");
        builder.AppendLine("    {");
        if (runtime == RuntimeBackend.Unknown)
        {
            builder.AppendLine("        private static S1InteropRuntimeBackend? cachedBackend;");
            builder.AppendLine("        public static S1InteropRuntimeBackend Backend");
            builder.AppendLine("        {");
            builder.AppendLine("            get");
            builder.AppendLine("            {");
            builder.AppendLine("                if (cachedBackend is null || cachedBackend == S1InteropRuntimeBackend.Unknown)");
            builder.AppendLine("                {");
            builder.AppendLine("                    cachedBackend = DetectBackend();");
            builder.AppendLine("                }");
            builder.AppendLine();
            builder.AppendLine("                return cachedBackend.Value;");
            builder.AppendLine("            }");
            builder.AppendLine("        }");
            builder.AppendLine("        public static bool IsMono => Backend == S1InteropRuntimeBackend.Mono;");
            builder.AppendLine("        public static bool IsIl2Cpp => Backend == S1InteropRuntimeBackend.Il2Cpp;");
            builder.AppendLine();
            builder.AppendLine("        private static S1InteropRuntimeBackend DetectBackend()");
            builder.AppendLine("        {");
            foreach (S1InteropTypeEntry entry in entries.OrderBy(entry => entry.Alias, StringComparer.Ordinal))
            {
                builder.AppendLine($"            if (S1InteropTypeRegistry.Resolve(\"{Escape(entry.Il2CppTypeName)}\") is not null)");
                builder.AppendLine("            {");
                builder.AppendLine("                return S1InteropRuntimeBackend.Il2Cpp;");
                builder.AppendLine("            }");
            }

            foreach (S1InteropTypeEntry entry in entries.OrderBy(entry => entry.Alias, StringComparer.Ordinal))
            {
                builder.AppendLine($"            if (S1InteropTypeRegistry.Resolve(\"{Escape(entry.MonoTypeName)}\") is not null)");
                builder.AppendLine("            {");
                builder.AppendLine("                return S1InteropRuntimeBackend.Mono;");
                builder.AppendLine("            }");
            }

            foreach (string typeName in DefaultIl2CppRuntimeProbeTypeNames)
            {
                builder.AppendLine($"            if (S1InteropTypeRegistry.Resolve(\"{Escape(typeName)}\") is not null)");
                builder.AppendLine("            {");
                builder.AppendLine("                return S1InteropRuntimeBackend.Il2Cpp;");
                builder.AppendLine("            }");
            }

            foreach (string typeName in DefaultMonoRuntimeProbeTypeNames)
            {
                builder.AppendLine($"            if (S1InteropTypeRegistry.Resolve(\"{Escape(typeName)}\") is not null)");
                builder.AppendLine("            {");
                builder.AppendLine("                return S1InteropRuntimeBackend.Mono;");
                builder.AppendLine("            }");
            }

            foreach (string assemblyName in DefaultIl2CppRuntimeProbeAssemblyNames)
            {
                builder.AppendLine($"            if (S1InteropTypeRegistry.IsAssemblyLoaded(\"{Escape(assemblyName)}\"))");
                builder.AppendLine("            {");
                builder.AppendLine("                return S1InteropRuntimeBackend.Il2Cpp;");
                builder.AppendLine("            }");
            }

            foreach (string assemblyName in DefaultMonoRuntimeProbeAssemblyNames)
            {
                builder.AppendLine($"            if (S1InteropTypeRegistry.IsAssemblyLoaded(\"{Escape(assemblyName)}\"))");
                builder.AppendLine("            {");
                builder.AppendLine("                return S1InteropRuntimeBackend.Mono;");
                builder.AppendLine("            }");
            }

            builder.AppendLine();
            builder.AppendLine("            return S1InteropRuntimeBackend.Unknown;");
            builder.AppendLine("        }");
        }
        else
        {
            builder.AppendLine($"        public const S1InteropRuntimeBackend Backend = S1InteropRuntimeBackend.{runtime};");
            builder.AppendLine($"        public const bool IsMono = {ToCSharpBoolean(runtime == RuntimeBackend.Mono)};");
            builder.AppendLine($"        public const bool IsIl2Cpp = {ToCSharpBoolean(runtime == RuntimeBackend.Il2Cpp)};");
        }

        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    internal static class S1InteropTypeRegistry");
        builder.AppendLine("    {");
        builder.AppendLine("        private static readonly System.Collections.Generic.Dictionary<string, System.Type?> Cache = new System.Collections.Generic.Dictionary<string, System.Type?>(System.StringComparer.Ordinal);");
        builder.AppendLine();

        foreach (S1InteropTypeEntry entry in entries.OrderBy(entry => entry.Alias, StringComparer.Ordinal))
        {
            builder.AppendLine($"        public readonly struct {entry.Alias}Tag");
            builder.AppendLine("        {");
            builder.AppendLine("        }");
            builder.AppendLine();

            if (runtime == RuntimeBackend.Unknown)
            {
                builder.AppendLine($"        public const string {entry.Alias}MonoName = \"{Escape(entry.MonoTypeName)}\";");
                builder.AppendLine($"        public const string {entry.Alias}Il2CppName = \"{Escape(entry.Il2CppTypeName)}\";");
                builder.AppendLine($"        public static string {entry.Alias}Name => GetRuntimeTypeName({entry.Alias}MonoName, {entry.Alias}Il2CppName);");
            }
            else
            {
                string runtimeName = runtime == RuntimeBackend.Il2Cpp ? entry.Il2CppTypeName : entry.MonoTypeName;
                builder.AppendLine($"        public const string {entry.Alias}Name = \"{Escape(runtimeName)}\";");
            }

            builder.AppendLine($"        public static System.Type? {entry.Alias} => Resolve({entry.Alias}Name);");
            builder.AppendLine($"        public static object? Create{entry.Alias}(params object?[] args) => Create({entry.Alias}Name, args);");
            builder.AppendLine($"        public static T? Create{entry.Alias}<T>(params object?[] args) where T : class => Create{entry.Alias}(args) as T;");
            builder.AppendLine($"        public static object? Get{entry.Alias}Static(string memberName) => S1InteropMemberRegistry.GetValue({entry.Alias}Name, memberName, null);");
            builder.AppendLine($"        public static bool TrySet{entry.Alias}Static(string memberName, object? value) => S1InteropMemberRegistry.TrySetValue({entry.Alias}Name, memberName, null, value);");
            builder.AppendLine($"        public static object? Invoke{entry.Alias}Static(string methodName, params object?[] args) => S1InteropMemberRegistry.Invoke({entry.Alias}Name, methodName, parameterTypeNames: null, null, args);");
            builder.AppendLine($"        public static T? Invoke{entry.Alias}Static<T>(string methodName, params object?[] args) => S1InteropMemberRegistry.CastResult<T>(Invoke{entry.Alias}Static(methodName, args));");
            builder.AppendLine($"        public static object? Invoke{entry.Alias}Static(string methodName, string[]? parameterTypeNames, params object?[] args) => S1InteropMemberRegistry.Invoke({entry.Alias}Name, methodName, parameterTypeNames, null, args);");
            builder.AppendLine($"        public static T? Invoke{entry.Alias}Static<T>(string methodName, string[]? parameterTypeNames, params object?[] args) => S1InteropMemberRegistry.CastResult<T>(Invoke{entry.Alias}Static(methodName, parameterTypeNames, args));");
            builder.AppendLine($"        public static bool Is{entry.Alias}(object? instance) => IsInstance(instance, {entry.Alias}Name);");
            builder.AppendLine($"        public static bool TryAs{entry.Alias}(object? instance, out S1InteropObject<{entry.Alias}Tag> value)");
            builder.AppendLine("        {");
            builder.AppendLine($"            if (!Is{entry.Alias}(instance))");
            builder.AppendLine("            {");
            builder.AppendLine($"                value = default(S1InteropObject<{entry.Alias}Tag>);");
            builder.AppendLine("                return false;");
            builder.AppendLine("            }");
            builder.AppendLine();
            builder.AppendLine($"            value = new S1InteropObject<{entry.Alias}Tag>(instance);");
            builder.AppendLine("            return true;");
            builder.AppendLine("        }");
            builder.AppendLine($"        public static S1InteropObject<{entry.Alias}Tag> As{entry.Alias}(object? instance) => TryAs{entry.Alias}(instance, out S1InteropObject<{entry.Alias}Tag> value) ? value : default(S1InteropObject<{entry.Alias}Tag>);");
            builder.AppendLine($"        public static object? Get{entry.Alias}(object? instance, string memberName) => S1InteropMemberRegistry.GetInstanceValue(instance, memberName);");
            builder.AppendLine($"        public static object? Get{entry.Alias}(S1InteropObject<{entry.Alias}Tag> instance, string memberName) => S1InteropMemberRegistry.GetInstanceValue(instance.Instance, memberName);");
            builder.AppendLine($"        public static bool TrySet{entry.Alias}(object? instance, string memberName, object? value) => S1InteropMemberRegistry.TrySetInstanceValue(instance, memberName, value);");
            builder.AppendLine($"        public static bool TrySet{entry.Alias}(S1InteropObject<{entry.Alias}Tag> instance, string memberName, object? value) => S1InteropMemberRegistry.TrySetInstanceValue(instance.Instance, memberName, value);");
            builder.AppendLine($"        public static object? Invoke{entry.Alias}(object? instance, string methodName, params object?[] args) => S1InteropMemberRegistry.InvokeInstance(instance, methodName, args);");
            builder.AppendLine($"        public static object? Invoke{entry.Alias}(S1InteropObject<{entry.Alias}Tag> instance, string methodName, params object?[] args) => S1InteropMemberRegistry.InvokeInstance(instance.Instance, methodName, args);");
            builder.AppendLine($"        public static T? Invoke{entry.Alias}<T>(object? instance, string methodName, params object?[] args) => S1InteropMemberRegistry.CastResult<T>(Invoke{entry.Alias}(instance, methodName, args));");
            builder.AppendLine($"        public static T? Invoke{entry.Alias}<T>(S1InteropObject<{entry.Alias}Tag> instance, string methodName, params object?[] args) => S1InteropMemberRegistry.CastResult<T>(Invoke{entry.Alias}(instance, methodName, args));");
            builder.AppendLine($"        public static object? Invoke{entry.Alias}(object? instance, string methodName, string[]? parameterTypeNames, params object?[] args) => S1InteropMemberRegistry.InvokeInstance(instance, methodName, parameterTypeNames, args);");
            builder.AppendLine($"        public static object? Invoke{entry.Alias}(S1InteropObject<{entry.Alias}Tag> instance, string methodName, string[]? parameterTypeNames, params object?[] args) => S1InteropMemberRegistry.InvokeInstance(instance.Instance, methodName, parameterTypeNames, args);");
            builder.AppendLine($"        public static T? Invoke{entry.Alias}<T>(object? instance, string methodName, string[]? parameterTypeNames, params object?[] args) => S1InteropMemberRegistry.CastResult<T>(Invoke{entry.Alias}(instance, methodName, parameterTypeNames, args));");
            builder.AppendLine($"        public static T? Invoke{entry.Alias}<T>(S1InteropObject<{entry.Alias}Tag> instance, string methodName, string[]? parameterTypeNames, params object?[] args) => S1InteropMemberRegistry.CastResult<T>(Invoke{entry.Alias}(instance, methodName, parameterTypeNames, args));");
            builder.AppendLine();
        }

        builder.AppendLine("        public static string GetRuntimeTypeName(string monoTypeName, string il2CppTypeName)");
        builder.AppendLine("        {");
        builder.AppendLine("            return S1InteropRuntime.Backend == S1InteropRuntimeBackend.Il2Cpp ? il2CppTypeName : monoTypeName;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static System.Type? Resolve(string runtimeTypeName)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (!Cache.TryGetValue(runtimeTypeName, out System.Type? type))");
        builder.AppendLine("            {");
        builder.AppendLine("                type = System.Type.GetType(runtimeTypeName, throwOnError: false);");
        builder.AppendLine("                if (type is null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    type = ResolveFromLoadedAssemblies(runtimeTypeName);");
        builder.AppendLine("                }");
        builder.AppendLine("                if (type is null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    type = ResolveFromKnownGameAssemblies(runtimeTypeName);");
        builder.AppendLine("                }");
        builder.AppendLine("                Cache[runtimeTypeName] = type;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return type;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static object? Create(string runtimeTypeName, params object?[] args)");
        builder.AppendLine("        {");
        builder.AppendLine("            System.Type? type = Resolve(runtimeTypeName);");
        builder.AppendLine("            if (type is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return null;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            foreach (System.Reflection.ConstructorInfo constructor in type.GetConstructors(System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance))");
        builder.AppendLine("            {");
        builder.AppendLine("                System.Reflection.ParameterInfo[] parameters = constructor.GetParameters();");
        builder.AppendLine("                if (parameters.Length != args.Length)");
        builder.AppendLine("                {");
        builder.AppendLine("                    continue;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                object?[] converted = new object?[args.Length];");
        builder.AppendLine("                bool compatible = true;");
        builder.AppendLine("                for (int index = 0; index < args.Length; index++)");
        builder.AppendLine("                {");
        builder.AppendLine("                    if (!S1InteropMemberRegistry.TryConvertValue(args[index], parameters[index].ParameterType, out object? convertedValue))");
        builder.AppendLine("                    {");
        builder.AppendLine("                        compatible = false;");
        builder.AppendLine("                        break;");
        builder.AppendLine("                    }");
        builder.AppendLine();
        builder.AppendLine("                    converted[index] = convertedValue;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                if (!compatible)");
        builder.AppendLine("                {");
        builder.AppendLine("                    continue;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                return constructor.Invoke(converted);");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return null;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static bool IsInstance(object? instance, string runtimeTypeName)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (instance is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Type? runtimeType = Resolve(runtimeTypeName);");
        builder.AppendLine("            return runtimeType is not null && runtimeType.IsInstanceOfType(instance);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static bool IsAssemblyLoaded(string assemblyName)");
        builder.AppendLine("        {");
        builder.AppendLine("            foreach (System.Reflection.Assembly assembly in System.AppDomain.CurrentDomain.GetAssemblies())");
        builder.AppendLine("            {");
        builder.AppendLine("                if (string.Equals(assembly.GetName().Name, assemblyName, System.StringComparison.OrdinalIgnoreCase))");
        builder.AppendLine("                {");
        builder.AppendLine("                    return true;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return false;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static System.Type? ResolveFromLoadedAssemblies(string runtimeTypeName)");
        builder.AppendLine("        {");
        builder.AppendLine("            foreach (System.Reflection.Assembly assembly in System.AppDomain.CurrentDomain.GetAssemblies())");
        builder.AppendLine("            {");
        builder.AppendLine("                System.Type? type = assembly.GetType(runtimeTypeName, throwOnError: false);");
        builder.AppendLine("                if (type is not null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return type;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (runtimeTypeName.IndexOf('.') >= 0)");
        builder.AppendLine("            {");
        builder.AppendLine("                return null;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            foreach (System.Reflection.Assembly assembly in System.AppDomain.CurrentDomain.GetAssemblies())");
        builder.AppendLine("            {");
        builder.AppendLine("                foreach (System.Type type in GetLoadableTypes(assembly))");
        builder.AppendLine("                {");
        builder.AppendLine("                    if (string.Equals(type.Name, runtimeTypeName, System.StringComparison.Ordinal))");
        builder.AppendLine("                    {");
        builder.AppendLine("                        return type;");
        builder.AppendLine("                    }");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return null;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static System.Type? ResolveFromKnownGameAssemblies(string runtimeTypeName)");
        builder.AppendLine("        {");
        foreach (string assemblyName in DefaultGameAssemblyProbeNames)
        {
            builder.AppendLine($"            System.Type? {SanitizeLocalName(assemblyName)}Type = ResolveFromAssembly(\"{Escape(assemblyName)}\", runtimeTypeName);");
            builder.AppendLine($"            if ({SanitizeLocalName(assemblyName)}Type is not null)");
            builder.AppendLine("            {");
            builder.AppendLine($"                return {SanitizeLocalName(assemblyName)}Type;");
            builder.AppendLine("            }");
            builder.AppendLine();
        }

        builder.AppendLine("            return null;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static System.Type? ResolveFromAssembly(string assemblyName, string runtimeTypeName)");
        builder.AppendLine("        {");
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                System.Reflection.Assembly assembly = System.Reflection.Assembly.Load(assemblyName);");
        builder.AppendLine("                System.Type? type = assembly.GetType(runtimeTypeName, throwOnError: false);");
        builder.AppendLine("                return type;");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("                return null;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static System.Collections.Generic.IEnumerable<System.Type> GetLoadableTypes(System.Reflection.Assembly assembly)");
        builder.AppendLine("        {");
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                return assembly.GetTypes();");
        builder.AppendLine("            }");
        builder.AppendLine("            catch (System.Reflection.ReflectionTypeLoadException ex)");
        builder.AppendLine("            {");
        builder.AppendLine("                System.Collections.Generic.List<System.Type> types = new System.Collections.Generic.List<System.Type>();");
        builder.AppendLine("                foreach (System.Type? type in ex.Types)");
        builder.AppendLine("                {");
        builder.AppendLine("                    if (type is not null)");
        builder.AppendLine("                    {");
        builder.AppendLine("                        types.Add(type);");
        builder.AppendLine("                    }");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                return types;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        GenerateObjectHandle(builder);
        GenerateObjectCastRegistry(builder);
        GenerateDelegateBridge(builder);
        GenerateMemberRegistry(builder, runtime, entries, members);
        builder.AppendLine("}");
        GenerateTypeFacades(builder, entries, members);
        return QualifySystemNamespaceReferences(builder.ToString());
    }

    private static string QualifySystemNamespaceReferences(string source)
    {
        string qualified = Regex.Replace(source, @"(?<!global::)\bSystem\.", "global::System.");
        return qualified
            .Replace("Il2Cppglobal::System.", "Il2CppSystem.")
            .Replace("\"global::System.", "\"System.");
    }

}
