using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace S1Interop.Generators;

public sealed partial class S1InteropTypeRegistryGenerator
{
    private static string GenerateHarmonyPatchSource(ImmutableArray<S1InteropPatchEntry> patches)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("// Generated by S1Interop.Generators. Do not edit by hand.");
        builder.AppendLine();
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("#if NETSTANDARD2_0 || NETSTANDARD2_1 || NETFRAMEWORK");
        builder.AppendLine("namespace System.Runtime.CompilerServices");
        builder.AppendLine("{");
        builder.AppendLine("    [System.AttributeUsage(System.AttributeTargets.Method, Inherited = false)]");
        builder.AppendLine("    internal sealed class ModuleInitializerAttribute : System.Attribute");
        builder.AppendLine("    {");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        builder.AppendLine("#endif");
        builder.AppendLine();
        builder.AppendLine("namespace S1Interop.Generated");
        builder.AppendLine("{");
        builder.AppendLine("    internal enum S1InteropPatchStatus");
        builder.AppendLine("    {");
        builder.AppendLine("        Applied,");
        builder.AppendLine("        SkippedMissingTarget,");
        builder.AppendLine("        SkippedMissingHandler,");
        builder.AppendLine("        PatchFailed");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    internal readonly struct S1InteropPatchReport");
        builder.AppendLine("    {");
        builder.AppendLine("        public S1InteropPatchReport(S1InteropPatchStatus status, string targetTypeName, string targetMethodName, string patchTypeName, string? message, string? exceptionTypeName)");
        builder.AppendLine("        {");
        builder.AppendLine("            Status = status;");
        builder.AppendLine("            TargetTypeName = targetTypeName;");
        builder.AppendLine("            TargetMethodName = targetMethodName;");
        builder.AppendLine("            PatchTypeName = patchTypeName;");
        builder.AppendLine("            Message = message;");
        builder.AppendLine("            ExceptionTypeName = exceptionTypeName;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public S1InteropPatchStatus Status { get; }");
        builder.AppendLine();
        builder.AppendLine("        public string TargetTypeName { get; }");
        builder.AppendLine();
        builder.AppendLine("        public string TargetMethodName { get; }");
        builder.AppendLine();
        builder.AppendLine("        public string PatchTypeName { get; }");
        builder.AppendLine();
        builder.AppendLine("        public string? Message { get; }");
        builder.AppendLine();
        builder.AppendLine("        public string? ExceptionTypeName { get; }");
        builder.AppendLine();
        builder.AppendLine("        public override string ToString()");
        builder.AppendLine("        {");
        builder.AppendLine("            string value = Status + \": \" + PatchTypeName + \" -> \" + TargetTypeName + \".\" + TargetMethodName;");
        builder.AppendLine("            if (!string.IsNullOrWhiteSpace(Message))");
        builder.AppendLine("            {");
        builder.AppendLine("                value += \" (\" + Message + \")\";");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (!string.IsNullOrWhiteSpace(ExceptionTypeName))");
        builder.AppendLine("            {");
        builder.AppendLine("                value += \" [\" + ExceptionTypeName + \"]\";");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return value;");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    internal static class S1InteropHarmonyPatcher");
        builder.AppendLine("    {");
        builder.AppendLine("        private const System.Reflection.BindingFlags PatchMethodBindings = System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static | System.Reflection.BindingFlags.Instance;");
        builder.AppendLine("        private static readonly System.Collections.Generic.List<S1InteropPatchReport> MutableReports = new System.Collections.Generic.List<S1InteropPatchReport>();");
        builder.AppendLine("        private static bool Applied;");
        builder.AppendLine();
        builder.AppendLine("        internal static System.Collections.Generic.IReadOnlyList<S1InteropPatchReport> Reports => MutableReports;");
        builder.AppendLine();
        builder.AppendLine("        [System.Runtime.CompilerServices.ModuleInitializer]");
        builder.AppendLine("        internal static void InitializeGeneratedPatches()");
        builder.AppendLine("        {");
        builder.AppendLine("            ApplyGeneratedPatches();");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        internal static void ApplyGeneratedPatches()");
        builder.AppendLine("        {");
        builder.AppendLine("            string harmonyId = System.Reflection.Assembly.GetExecutingAssembly().GetName().Name ?? \"S1Interop.Generated\";");
        builder.AppendLine("            ApplyGeneratedPatches(new HarmonyLib.Harmony(harmonyId + \".S1Interop\"));");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        internal static void ApplyGeneratedPatches(HarmonyLib.Harmony harmony)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (harmony is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                throw new System.ArgumentNullException(nameof(harmony));");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (Applied)");
        builder.AppendLine("            {");
        builder.AppendLine("                return;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            Applied = true;");

        int patchIndex = 0;
        foreach (S1InteropPatchEntry patch in patches)
        {
            builder.AppendLine($"            ApplyPatch{patchIndex.ToString("D4", System.Globalization.CultureInfo.InvariantCulture)}(harmony);");
            patchIndex++;
        }

        builder.AppendLine("        }");
        builder.AppendLine();

        patchIndex = 0;
        foreach (S1InteropPatchEntry patch in patches)
        {
            GeneratePatchMethod(builder, patch, patchIndex);
            patchIndex++;
        }

        builder.AppendLine("        private static HarmonyLib.HarmonyMethod? CreateHarmonyMethod(System.Type declaringType, string methodName)");
        builder.AppendLine("        {");
        builder.AppendLine("            foreach (System.Reflection.MethodInfo method in declaringType.GetMethods(PatchMethodBindings))");
        builder.AppendLine("            {");
        builder.AppendLine("                if (string.Equals(method.Name, methodName, System.StringComparison.Ordinal))");
        builder.AppendLine("                {");
        builder.AppendLine("                    return new HarmonyLib.HarmonyMethod(method);");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return null;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static void Record(S1InteropPatchStatus status, string targetTypeName, string targetMethodName, string patchTypeName, string? message, bool required, System.Exception? exception = null)");
        builder.AppendLine("        {");
        builder.AppendLine("            var report = new S1InteropPatchReport(status, targetTypeName, targetMethodName, patchTypeName, message, exception?.GetType().FullName);");
        builder.AppendLine("            MutableReports.Add(report);");
        builder.AppendLine("            if (status != S1InteropPatchStatus.Applied)");
        builder.AppendLine("            {");
        builder.AppendLine("                Log(report);");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (required && status != S1InteropPatchStatus.Applied)");
        builder.AppendLine("            {");
        builder.AppendLine("                throw new System.InvalidOperationException(\"Required S1Interop patch failed: \" + report, exception);");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static void Log(S1InteropPatchReport report)");
        builder.AppendLine("        {");
        builder.AppendLine("            string message = \"[S1Interop] \" + report;");
        builder.AppendLine("            if (TryLogWithMelonLoader(message))");
        builder.AppendLine("            {");
        builder.AppendLine("                return;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                System.Diagnostics.Trace.TraceWarning(message);");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                System.Console.Error.WriteLine(message);");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryLogWithMelonLoader(string message)");
        builder.AppendLine("        {");
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                foreach (System.Reflection.Assembly assembly in System.AppDomain.CurrentDomain.GetAssemblies())");
        builder.AppendLine("                {");
        builder.AppendLine("                    System.Type? loggerType = assembly.GetType(\"MelonLoader.MelonLogger\", throwOnError: false);");
        builder.AppendLine("                    System.Reflection.MethodInfo? warningMethod = GetLoggerMethod(loggerType, \"Warning\") ?? GetLoggerMethod(loggerType, \"Msg\");");
        builder.AppendLine("                    if (warningMethod is not null)");
        builder.AppendLine("                    {");
        builder.AppendLine("                        warningMethod.Invoke(null, new object?[] { message });");
        builder.AppendLine("                        return true;");
        builder.AppendLine("                    }");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return false;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static System.Reflection.MethodInfo? GetLoggerMethod(System.Type? loggerType, string methodName)");
        builder.AppendLine("        {");
        builder.AppendLine("            return loggerType?.GetMethod(methodName, new[] { typeof(string) }) ??");
        builder.AppendLine("                   loggerType?.GetMethod(methodName, new[] { typeof(object) });");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine("}");

        return QualifySystemNamespaceReferences(builder.ToString());
    }

    private static void GeneratePatchMethod(StringBuilder builder, S1InteropPatchEntry patch, int index)
    {
        string suffix = index.ToString("D4", System.Globalization.CultureInfo.InvariantCulture);
        string targetTypeExpression = $"S1InteropTypeRegistry.{patch.OwnerEntry.Alias}Name";
        string targetMethodExpression = $"S1InteropMemberRegistry.{patch.TargetMemberEntry.Alias}Name";
        string patchTypeExpression = $"typeof({patch.PatchTypeName}).FullName ?? \"{Escape(patch.PatchTypeName)}\"";
        string requiredLiteral = patch.Required ? "true" : "false";
        builder.AppendLine($"        private static void ApplyPatch{suffix}(HarmonyLib.Harmony harmony)");
        builder.AppendLine("        {");
        builder.AppendLine($"            string targetTypeName = {targetTypeExpression};");
        builder.AppendLine($"            string targetMethodName = {targetMethodExpression};");
        builder.AppendLine($"            string patchTypeName = {patchTypeExpression};");
        builder.AppendLine($"            bool required = {requiredLiteral};");
        builder.AppendLine($"            System.Reflection.MethodInfo? original = S1InteropMemberRegistry.{patch.TargetMemberEntry.Alias}Method;");
        builder.AppendLine("            if (original is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                Record(S1InteropPatchStatus.SkippedMissingTarget, targetTypeName, targetMethodName, patchTypeName, \"Target method could not be resolved for the active backend.\", required);");
        builder.AppendLine("                return;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine(GenerateHandlerLocal(patch, S1InteropPatchHandlerKind.Prefix, "prefix"));
        builder.AppendLine(GenerateHandlerLocal(patch, S1InteropPatchHandlerKind.Postfix, "postfix"));
        builder.AppendLine(GenerateHandlerLocal(patch, S1InteropPatchHandlerKind.Finalizer, "finalizer"));
        builder.AppendLine("            if (prefix is null && postfix is null && finalizer is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                Record(S1InteropPatchStatus.SkippedMissingHandler, targetTypeName, targetMethodName, patchTypeName, \"No S1Interop prefix, postfix, or finalizer handler could be resolved.\", required);");
        builder.AppendLine("                return;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                harmony.Patch(original, prefix: prefix, postfix: postfix, transpiler: null, finalizer: finalizer);");
        builder.AppendLine("                Record(S1InteropPatchStatus.Applied, targetTypeName, targetMethodName, patchTypeName, null, required);");
        builder.AppendLine("            }");
        builder.AppendLine("            catch (System.Exception exception)");
        builder.AppendLine("            {");
        builder.AppendLine("                Record(S1InteropPatchStatus.PatchFailed, targetTypeName, targetMethodName, patchTypeName, \"Harmony failed to apply the patch for the active backend.\", required, exception);");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
    }

    private static string GenerateHandlerLocal(S1InteropPatchEntry patch, S1InteropPatchHandlerKind kind, string localName)
    {
        foreach (S1InteropPatchHandlerEntry handler in patch.Handlers)
        {
            if (handler.Kind == kind)
            {
                return $"            HarmonyLib.HarmonyMethod? {localName} = CreateHarmonyMethod(typeof({patch.PatchTypeName}), \"{Escape(handler.MethodName)}\");";
            }
        }

        return $"            HarmonyLib.HarmonyMethod? {localName} = null;";
    }
}
