using System.Text;

namespace S1Interop.Generators;

public sealed partial class S1InteropTypeRegistryGenerator
{
    private static void GenerateMemberForwardConversionHelpers(StringBuilder builder)
    {
        builder.AppendLine("        public static bool TryConvertValue(object? value, System.Type targetType, out object? converted)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (value is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                converted = targetType.IsValueType && System.Nullable.GetUnderlyingType(targetType) is null ? System.Activator.CreateInstance(targetType) : null;");
        builder.AppendLine("                return true;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Type conversionType = System.Nullable.GetUnderlyingType(targetType) ?? targetType;");
        builder.AppendLine("            if (conversionType.IsInstanceOfType(value))");
        builder.AppendLine("            {");
        builder.AppendLine("                converted = value;");
        builder.AppendLine("                return true;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                if (TryConvertIl2CppGuid(value, conversionType, out converted))");
        builder.AppendLine("                {");
        builder.AppendLine("                    return true;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                if (TryConvertIl2CppList(value, conversionType, out converted))");
        builder.AppendLine("                {");
        builder.AppendLine("                    return true;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                if (TryConvertIl2CppHashSet(value, conversionType, out converted))");
        builder.AppendLine("                {");
        builder.AppendLine("                    return true;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                if (TryConvertIl2CppDictionary(value, conversionType, out converted))");
        builder.AppendLine("                {");
        builder.AppendLine("                    return true;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                if (TryConvertIl2CppArray(value, conversionType, out converted))");
        builder.AppendLine("                {");
        builder.AppendLine("                    return true;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                if (conversionType.IsEnum)");
        builder.AppendLine("                {");
        builder.AppendLine("                    converted = value is string text ? System.Enum.Parse(conversionType, text, ignoreCase: true) : System.Enum.ToObject(conversionType, value);");
        builder.AppendLine("                    return true;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                converted = System.Convert.ChangeType(value, conversionType, System.Globalization.CultureInfo.InvariantCulture);");
        builder.AppendLine("                return true;");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("                converted = null;");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryConvertIl2CppGuid(object value, System.Type targetType, out object? converted)");
        builder.AppendLine("        {");
        builder.AppendLine("            converted = null;");
        builder.AppendLine("            if (!string.Equals(targetType.FullName, \"Il2CppSystem.Guid\", System.StringComparison.Ordinal) || value is not System.Guid guid)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                System.Reflection.ConstructorInfo? stringConstructor = targetType.GetConstructor(new[] { typeof(string) });");
        builder.AppendLine("                if (stringConstructor is not null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    converted = stringConstructor.Invoke(new object[] { guid.ToString() });");
        builder.AppendLine("                    return true;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                System.Reflection.ConstructorInfo? byteArrayConstructor = targetType.GetConstructor(new[] { typeof(byte[]) });");
        builder.AppendLine("                if (byteArrayConstructor is not null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    converted = byteArrayConstructor.Invoke(new object[] { guid.ToByteArray() });");
        builder.AppendLine("                    return true;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("                converted = null;");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return false;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryConvertIl2CppList(object value, System.Type targetType, out object? converted)");
        builder.AppendLine("        {");
        builder.AppendLine("            converted = null;");
        builder.AppendLine("            if (targetType.FullName is null || !targetType.FullName.StartsWith(\"Il2CppSystem.Collections.Generic.List`1\", System.StringComparison.Ordinal))");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (value is string || value is not System.Collections.IEnumerable enumerable)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Type[] genericArguments = targetType.GetGenericArguments();");
        builder.AppendLine("            if (genericArguments.Length != 1)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Reflection.MethodInfo? addMethod = targetType.GetMethod(\"Add\", new[] { genericArguments[0] });");
        builder.AppendLine("            if (addMethod is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                object? list = System.Activator.CreateInstance(targetType);");
        builder.AppendLine("                if (list is null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return false;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                foreach (object? item in enumerable)");
        builder.AppendLine("                {");
        builder.AppendLine("                    if (!TryConvertValue(item, genericArguments[0], out object? convertedItem))");
        builder.AppendLine("                    {");
        builder.AppendLine("                        return false;");
        builder.AppendLine("                    }");
        builder.AppendLine();
        builder.AppendLine("                    addMethod.Invoke(list, new object?[] { convertedItem });");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                converted = list;");
        builder.AppendLine("                return true;");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("                converted = null;");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryConvertIl2CppHashSet(object value, System.Type targetType, out object? converted)");
        builder.AppendLine("        {");
        builder.AppendLine("            converted = null;");
        builder.AppendLine("            if (targetType.FullName is null || !targetType.FullName.StartsWith(\"Il2CppSystem.Collections.Generic.HashSet`1\", System.StringComparison.Ordinal))");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (value is string || value is not System.Collections.IEnumerable enumerable)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Type[] genericArguments = targetType.GetGenericArguments();");
        builder.AppendLine("            if (genericArguments.Length != 1)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Reflection.MethodInfo? addMethod = targetType.GetMethod(\"Add\", new[] { genericArguments[0] });");
        builder.AppendLine("            if (addMethod is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                object? set = System.Activator.CreateInstance(targetType);");
        builder.AppendLine("                if (set is null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return false;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                foreach (object? item in enumerable)");
        builder.AppendLine("                {");
        builder.AppendLine("                    if (!TryConvertValue(item, genericArguments[0], out object? convertedItem))");
        builder.AppendLine("                    {");
        builder.AppendLine("                        return false;");
        builder.AppendLine("                    }");
        builder.AppendLine();
        builder.AppendLine("                    addMethod.Invoke(set, new object?[] { convertedItem });");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                converted = set;");
        builder.AppendLine("                return true;");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("                converted = null;");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryConvertIl2CppDictionary(object value, System.Type targetType, out object? converted)");
        builder.AppendLine("        {");
        builder.AppendLine("            converted = null;");
        builder.AppendLine("            if (targetType.FullName is null || !targetType.FullName.StartsWith(\"Il2CppSystem.Collections.Generic.Dictionary`2\", System.StringComparison.Ordinal))");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (value is not System.Collections.IEnumerable enumerable)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Type[] genericArguments = targetType.GetGenericArguments();");
        builder.AppendLine("            if (genericArguments.Length != 2)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Reflection.MethodInfo? addMethod = targetType.GetMethod(\"Add\", new[] { genericArguments[0], genericArguments[1] });");
        builder.AppendLine("            if (addMethod is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                object? il2CppDictionary = System.Activator.CreateInstance(targetType);");
        builder.AppendLine("                if (il2CppDictionary is null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return false;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                foreach (object? entry in enumerable)");
        builder.AppendLine("                {");
        builder.AppendLine("                    if (!TryGetDictionaryEntry(entry, out object? key, out object? entryValue) ||");
        builder.AppendLine("                        !TryConvertValue(key, genericArguments[0], out object? convertedKey) ||");
        builder.AppendLine("                        !TryConvertValue(entryValue, genericArguments[1], out object? convertedValue))");
        builder.AppendLine("                    {");
        builder.AppendLine("                        return false;");
        builder.AppendLine("                    }");
        builder.AppendLine();
        builder.AppendLine("                    addMethod.Invoke(il2CppDictionary, new object?[] { convertedKey, convertedValue });");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                converted = il2CppDictionary;");
        builder.AppendLine("                return true;");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("                converted = null;");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryGetDictionaryEntry(object? entry, out object? key, out object? value)");
        builder.AppendLine("        {");
        builder.AppendLine("            key = null;");
        builder.AppendLine("            value = null;");
        builder.AppendLine("            if (entry is System.Collections.DictionaryEntry dictionaryEntry)");
        builder.AppendLine("            {");
        builder.AppendLine("                key = dictionaryEntry.Key;");
        builder.AppendLine("                value = dictionaryEntry.Value;");
        builder.AppendLine("                return true;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (entry is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Type entryType = entry.GetType();");
        builder.AppendLine("            System.Reflection.PropertyInfo? keyProperty = entryType.GetProperty(\"Key\");");
        builder.AppendLine("            System.Reflection.PropertyInfo? valueProperty = entryType.GetProperty(\"Value\");");
        builder.AppendLine("            if (keyProperty is null || valueProperty is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            key = keyProperty.GetValue(entry, null);");
        builder.AppendLine("            value = valueProperty.GetValue(entry, null);");
        builder.AppendLine("            return true;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryConvertIl2CppArray(object value, System.Type targetType, out object? converted)");
        builder.AppendLine("        {");
        builder.AppendLine("            converted = null;");
        builder.AppendLine("            if (targetType.FullName is null ||");
        builder.AppendLine("                (!targetType.FullName.StartsWith(\"Il2CppInterop.Runtime.InteropTypes.Arrays.Il2CppStructArray`1\", System.StringComparison.Ordinal) &&");
        builder.AppendLine("                 !targetType.FullName.StartsWith(\"Il2CppInterop.Runtime.InteropTypes.Arrays.Il2CppReferenceArray`1\", System.StringComparison.Ordinal)))");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (value is string || value is not System.Collections.IEnumerable enumerable)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Type[] genericArguments = targetType.GetGenericArguments();");
        builder.AppendLine("            if (genericArguments.Length != 1)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                System.Collections.Generic.List<object?> items = new System.Collections.Generic.List<object?>();");
        builder.AppendLine("                foreach (object? item in enumerable)");
        builder.AppendLine("                {");
        builder.AppendLine("                    if (!TryConvertValue(item, genericArguments[0], out object? convertedItem))");
        builder.AppendLine("                    {");
        builder.AppendLine("                        return false;");
        builder.AppendLine("                    }");
        builder.AppendLine();
        builder.AppendLine("                    items.Add(convertedItem);");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                object? array = CreateIl2CppArray(targetType, items.Count);");
        builder.AppendLine("                if (array is null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return false;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                System.Reflection.PropertyInfo? indexer = targetType.GetProperty(\"Item\", new[] { typeof(int) });");
        builder.AppendLine("                System.Reflection.MethodInfo? setItem = targetType.GetMethod(\"set_Item\", new[] { typeof(int), genericArguments[0] });");
        builder.AppendLine("                if (indexer is null && setItem is null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return false;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                for (int index = 0; index < items.Count; index++)");
        builder.AppendLine("                {");
        builder.AppendLine("                    if (indexer is not null)");
        builder.AppendLine("                    {");
        builder.AppendLine("                        indexer.SetValue(array, items[index], new object[] { index });");
        builder.AppendLine("                    }");
        builder.AppendLine("                    else");
        builder.AppendLine("                    {");
        builder.AppendLine("                        setItem!.Invoke(array, new object?[] { index, items[index] });");
        builder.AppendLine("                    }");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                converted = array;");
        builder.AppendLine("                return true;");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("                converted = null;");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static object? CreateIl2CppArray(System.Type targetType, int count)");
        builder.AppendLine("        {");
        builder.AppendLine("            System.Reflection.ConstructorInfo? intConstructor = targetType.GetConstructor(new[] { typeof(int) });");
        builder.AppendLine("            if (intConstructor is not null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return intConstructor.Invoke(new object[] { count });");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Reflection.ConstructorInfo? longConstructor = targetType.GetConstructor(new[] { typeof(long) });");
        builder.AppendLine("            return longConstructor?.Invoke(new object[] { (long)count });");
        builder.AppendLine("        }");
        builder.AppendLine();
    }
}