using System.Text;

namespace S1Interop.Generators;

public sealed partial class S1InteropTypeRegistryGenerator
{
    private static void GenerateMemberBackConversionHelpers(StringBuilder builder)
    {
        builder.AppendLine("        private static object? ConvertBackValue(object? original, object? converted)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (converted is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return null;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (original is System.Guid && TryConvertBackGuid(converted, out System.Guid guid))");
        builder.AppendLine("            {");
        builder.AppendLine("                return guid;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (original is System.Array originalArray && TryConvertBackArray(originalArray, converted, out System.Array? managedArray))");
        builder.AppendLine("            {");
        builder.AppendLine("                return managedArray;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (original is System.Collections.IList originalList && TryConvertBackList(originalList, converted, out System.Collections.IList? managedList))");
        builder.AppendLine("            {");
        builder.AppendLine("                return managedList;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (TryConvertBackDictionary(original, converted, out object? managedDictionary))");
        builder.AppendLine("            {");
        builder.AppendLine("                return managedDictionary;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (TryConvertBackHashSet(original, converted, out object? managedHashSet))");
        builder.AppendLine("            {");
        builder.AppendLine("                return managedHashSet;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return converted;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryConvertBackGuid(object converted, out System.Guid guid)");
        builder.AppendLine("        {");
        builder.AppendLine("            guid = default;");
        builder.AppendLine("            if (!string.Equals(converted.GetType().FullName, \"Il2CppSystem.Guid\", System.StringComparison.Ordinal))");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            object? value = converted.GetType().GetProperty(\"Value\")?.GetValue(converted, null);");
        builder.AppendLine("            string? text = value as string ?? converted.ToString();");
        builder.AppendLine("            return text is not null && System.Guid.TryParse(text, out guid);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryConvertBackArray(System.Array original, object converted, out System.Array? managedArray)");
        builder.AppendLine("        {");
        builder.AppendLine("            managedArray = null;");
        builder.AppendLine("            System.Type convertedType = converted.GetType();");
        builder.AppendLine("            if (convertedType.FullName is null ||");
        builder.AppendLine("                (!convertedType.FullName.StartsWith(\"Il2CppInterop.Runtime.InteropTypes.Arrays.Il2CppStructArray`1\", System.StringComparison.Ordinal) &&");
        builder.AppendLine("                 !convertedType.FullName.StartsWith(\"Il2CppInterop.Runtime.InteropTypes.Arrays.Il2CppReferenceArray`1\", System.StringComparison.Ordinal)))");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Reflection.PropertyInfo? lengthProperty = convertedType.GetProperty(\"Length\");");
        builder.AppendLine("            System.Reflection.PropertyInfo? indexer = convertedType.GetProperty(\"Item\", new[] { typeof(int) });");
        builder.AppendLine("            if (lengthProperty?.GetValue(converted, null) is not int length || indexer is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Type elementType = original.GetType().GetElementType() ?? typeof(object);");
        builder.AppendLine("            System.Array result = System.Array.CreateInstance(elementType, length);");
        builder.AppendLine("            for (int index = 0; index < length; index++)");
        builder.AppendLine("            {");
        builder.AppendLine("                object? item = indexer.GetValue(converted, new object[] { index });");
        builder.AppendLine("                if (!TryConvertValue(item, elementType, out object? managedItem))");
        builder.AppendLine("                {");
        builder.AppendLine("                    return false;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                result.SetValue(managedItem, index);");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            managedArray = result;");
        builder.AppendLine("            return true;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryConvertBackList(System.Collections.IList original, object converted, out System.Collections.IList? managedList)");
        builder.AppendLine("        {");
        builder.AppendLine("            managedList = null;");
        builder.AppendLine("            System.Type convertedType = converted.GetType();");
        builder.AppendLine("            if (convertedType.FullName is null || !convertedType.FullName.StartsWith(\"Il2CppSystem.Collections.Generic.List`1\", System.StringComparison.Ordinal))");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Reflection.PropertyInfo? countProperty = convertedType.GetProperty(\"Count\");");
        builder.AppendLine("            System.Reflection.PropertyInfo? indexer = convertedType.GetProperty(\"Item\", new[] { typeof(int) });");
        builder.AppendLine("            if (countProperty?.GetValue(converted, null) is not int count || indexer is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Collections.IList? result = CreateManagedList(original);");
        builder.AppendLine("            if (result is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Type elementType = GetListElementType(result.GetType()) ?? typeof(object);");
        builder.AppendLine("            for (int index = 0; index < count; index++)");
        builder.AppendLine("            {");
        builder.AppendLine("                object? item = indexer.GetValue(converted, new object[] { index });");
        builder.AppendLine("                if (!TryConvertValue(item, elementType, out object? managedItem))");
        builder.AppendLine("                {");
        builder.AppendLine("                    return false;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                result.Add(managedItem);");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            managedList = result;");
        builder.AppendLine("            return true;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static System.Collections.IList? CreateManagedList(System.Collections.IList original)");
        builder.AppendLine("        {");
        builder.AppendLine("            System.Type originalType = original.GetType();");
        builder.AppendLine("            if (!original.IsFixedSize && !original.IsReadOnly)");
        builder.AppendLine("            {");
        builder.AppendLine("                System.Collections.IList? recreated = System.Activator.CreateInstance(originalType) as System.Collections.IList;");
        builder.AppendLine("                if (recreated is not null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return recreated;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Type elementType = GetListElementType(originalType) ?? typeof(object);");
        builder.AppendLine("            System.Type listType = typeof(System.Collections.Generic.List<>).MakeGenericType(elementType);");
        builder.AppendLine("            return System.Activator.CreateInstance(listType) as System.Collections.IList;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static System.Type? GetListElementType(System.Type listType)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (listType.IsGenericType)");
        builder.AppendLine("            {");
        builder.AppendLine("                System.Type[] arguments = listType.GetGenericArguments();");
        builder.AppendLine("                if (arguments.Length == 1)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return arguments[0];");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            foreach (System.Type interfaceType in listType.GetInterfaces())");
        builder.AppendLine("            {");
        builder.AppendLine("                if (interfaceType.IsGenericType && interfaceType.GetGenericTypeDefinition() == typeof(System.Collections.Generic.IList<>))");
        builder.AppendLine("                {");
        builder.AppendLine("                    return interfaceType.GetGenericArguments()[0];");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return null;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryConvertBackDictionary(object? original, object converted, out object? managedDictionary)");
        builder.AppendLine("        {");
        builder.AppendLine("            managedDictionary = null;");
        builder.AppendLine("            if (original is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Type convertedType = converted.GetType();");
        builder.AppendLine("            if (convertedType.FullName is null || !convertedType.FullName.StartsWith(\"Il2CppSystem.Collections.Generic.Dictionary`2\", System.StringComparison.Ordinal))");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (!TryGetDictionaryTypes(original.GetType(), out System.Type? keyType, out System.Type? valueType))");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine("            if (keyType is null || valueType is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            object? result = CreateManagedDictionary(original, keyType, valueType);");
        builder.AppendLine("            if (result is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Reflection.MethodInfo? addMethod = result.GetType().GetMethod(\"Add\", new[] { keyType, valueType });");
        builder.AppendLine("            if (addMethod is null && result is not System.Collections.IDictionary)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                object? enumerator = convertedType.GetMethod(\"GetEnumerator\", System.Type.EmptyTypes)?.Invoke(converted, null);");
        builder.AppendLine("                if (enumerator is null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return false;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                System.Type enumeratorType = enumerator.GetType();");
        builder.AppendLine("                System.Reflection.MethodInfo? moveNext = enumeratorType.GetMethod(\"MoveNext\", System.Type.EmptyTypes);");
        builder.AppendLine("                System.Reflection.PropertyInfo? currentProperty = enumeratorType.GetProperty(\"Current\");");
        builder.AppendLine("                if (moveNext is null || currentProperty is null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return false;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                while (moveNext.Invoke(enumerator, null) is true)");
        builder.AppendLine("                {");
        builder.AppendLine("                    object? entry = currentProperty.GetValue(enumerator, null);");
        builder.AppendLine("                    if (!TryGetDictionaryEntry(entry, out object? key, out object? value) ||");
        builder.AppendLine("                        !TryConvertValue(key, keyType, out object? managedKey) ||");
        builder.AppendLine("                        !TryConvertValue(value, valueType, out object? managedValue))");
        builder.AppendLine("                    {");
        builder.AppendLine("                        return false;");
        builder.AppendLine("                    }");
        builder.AppendLine();
        builder.AppendLine("                    if (result is System.Collections.IDictionary dictionary)");
        builder.AppendLine("                    {");
        builder.AppendLine("                        dictionary.Add(managedKey, managedValue);");
        builder.AppendLine("                    }");
        builder.AppendLine("                    else");
        builder.AppendLine("                    {");
        builder.AppendLine("                        addMethod!.Invoke(result, new object?[] { managedKey, managedValue });");
        builder.AppendLine("                    }");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            managedDictionary = result;");
        builder.AppendLine("            return true;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static object? CreateManagedDictionary(object original, System.Type keyType, System.Type valueType)");
        builder.AppendLine("        {");
        builder.AppendLine("            System.Type originalType = original.GetType();");
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                object? recreated = System.Activator.CreateInstance(originalType);");
        builder.AppendLine("                if (recreated is not null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return recreated;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Type dictionaryType = typeof(System.Collections.Generic.Dictionary<,>).MakeGenericType(keyType, valueType);");
        builder.AppendLine("            return System.Activator.CreateInstance(dictionaryType);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryGetDictionaryTypes(System.Type dictionaryType, out System.Type? keyType, out System.Type? valueType)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (dictionaryType.IsGenericType)");
        builder.AppendLine("            {");
        builder.AppendLine("                System.Type[] arguments = dictionaryType.GetGenericArguments();");
        builder.AppendLine("                if (arguments.Length == 2)");
        builder.AppendLine("                {");
        builder.AppendLine("                    keyType = arguments[0];");
        builder.AppendLine("                    valueType = arguments[1];");
        builder.AppendLine("                    return true;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            foreach (System.Type interfaceType in dictionaryType.GetInterfaces())");
        builder.AppendLine("            {");
        builder.AppendLine("                if (interfaceType.IsGenericType && interfaceType.GetGenericTypeDefinition() == typeof(System.Collections.Generic.IDictionary<,>))");
        builder.AppendLine("                {");
        builder.AppendLine("                    System.Type[] arguments = interfaceType.GetGenericArguments();");
        builder.AppendLine("                    keyType = arguments[0];");
        builder.AppendLine("                    valueType = arguments[1];");
        builder.AppendLine("                    return true;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            keyType = null;");
        builder.AppendLine("            valueType = null;");
        builder.AppendLine("            return false;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryConvertBackHashSet(object? original, object converted, out object? managedHashSet)");
        builder.AppendLine("        {");
        builder.AppendLine("            managedHashSet = null;");
        builder.AppendLine("            if (original is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Type convertedType = converted.GetType();");
        builder.AppendLine("            if (convertedType.FullName is null || !convertedType.FullName.StartsWith(\"Il2CppSystem.Collections.Generic.HashSet`1\", System.StringComparison.Ordinal))");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Type? elementType = GetSetElementType(original.GetType());");
        builder.AppendLine("            if (elementType is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            object? result = CreateManagedHashSet(original, elementType);");
        builder.AppendLine("            if (result is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Reflection.MethodInfo? addMethod = result.GetType().GetMethod(\"Add\", new[] { elementType });");
        builder.AppendLine("            if (addMethod is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                object? enumerator = convertedType.GetMethod(\"GetEnumerator\", System.Type.EmptyTypes)?.Invoke(converted, null);");
        builder.AppendLine("                if (enumerator is null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return false;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                System.Type enumeratorType = enumerator.GetType();");
        builder.AppendLine("                System.Reflection.MethodInfo? moveNext = enumeratorType.GetMethod(\"MoveNext\", System.Type.EmptyTypes);");
        builder.AppendLine("                System.Reflection.PropertyInfo? currentProperty = enumeratorType.GetProperty(\"Current\");");
        builder.AppendLine("                if (moveNext is null || currentProperty is null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return false;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                while (moveNext.Invoke(enumerator, null) is true)");
        builder.AppendLine("                {");
        builder.AppendLine("                    object? item = currentProperty.GetValue(enumerator, null);");
        builder.AppendLine("                    if (!TryConvertValue(item, elementType, out object? managedItem))");
        builder.AppendLine("                    {");
        builder.AppendLine("                        return false;");
        builder.AppendLine("                    }");
        builder.AppendLine();
        builder.AppendLine("                    addMethod.Invoke(result, new object?[] { managedItem });");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            managedHashSet = result;");
        builder.AppendLine("            return true;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static object? CreateManagedHashSet(object original, System.Type elementType)");
        builder.AppendLine("        {");
        builder.AppendLine("            System.Type originalType = original.GetType();");
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                object? recreated = System.Activator.CreateInstance(originalType);");
        builder.AppendLine("                if (recreated is not null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return recreated;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Type setType = typeof(System.Collections.Generic.HashSet<>).MakeGenericType(elementType);");
        builder.AppendLine("            return System.Activator.CreateInstance(setType);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static System.Type? GetSetElementType(System.Type setType)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (setType.IsGenericType)");
        builder.AppendLine("            {");
        builder.AppendLine("                System.Type[] arguments = setType.GetGenericArguments();");
        builder.AppendLine("                if (arguments.Length == 1)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return arguments[0];");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            foreach (System.Type interfaceType in setType.GetInterfaces())");
        builder.AppendLine("            {");
        builder.AppendLine("                if (interfaceType.IsGenericType && interfaceType.GetGenericTypeDefinition() == typeof(System.Collections.Generic.ISet<>))");
        builder.AppendLine("                {");
        builder.AppendLine("                    return interfaceType.GetGenericArguments()[0];");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return null;");
        builder.AppendLine("        }");
        builder.AppendLine();
    }
}