using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using System.Text;

namespace S1Interop.Generators;

public sealed partial class S1InteropTypeRegistryGenerator
{
    private static void GenerateObjectHandle(StringBuilder builder)
    {
        builder.AppendLine();
        builder.AppendLine("    internal readonly struct S1InteropObject<TTag>");
        builder.AppendLine("    {");
        builder.AppendLine("        private readonly object? instance;");
        builder.AppendLine();
        builder.AppendLine("        public S1InteropObject(object? instance)");
        builder.AppendLine("        {");
        builder.AppendLine("            this.instance = instance;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public object? Instance => instance;");
        builder.AppendLine("        public bool HasValue => instance is not null;");
        builder.AppendLine("        public override string ToString() => instance?.ToString() ?? string.Empty;");
        builder.AppendLine("    }");
    }

    private static void GenerateObjectCastRegistry(StringBuilder builder)
    {
        builder.AppendLine();
        builder.AppendLine("    internal static class S1InteropObjectCast");
        builder.AppendLine("    {");
        builder.AppendLine("        private static readonly System.Collections.Generic.Dictionary<string, System.Reflection.MethodInfo?> TryCastCache = new System.Collections.Generic.Dictionary<string, System.Reflection.MethodInfo?>(System.StringComparer.Ordinal);");
        builder.AppendLine();
        builder.AppendLine("        public static bool Is<T>(object? value, out T? result) where T : class");
        builder.AppendLine("        {");
        builder.AppendLine("            result = As<T>(value);");
        builder.AppendLine("            return result is not null;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static T? As<T>(object? value) where T : class");
        builder.AppendLine("        {");
        builder.AppendLine("            if (value is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return null;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (value is T typed)");
        builder.AppendLine("            {");
        builder.AppendLine("                return typed;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Type valueType = value.GetType();");
        builder.AppendLine("            if (!IsIl2CppObjectBase(valueType))");
        builder.AppendLine("            {");
        builder.AppendLine("                return null;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Reflection.MethodInfo? tryCast = ResolveTryCastMethod(valueType, typeof(T));");
        builder.AppendLine("            if (tryCast is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return null;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                return tryCast.Invoke(value, null) as T;");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("                return null;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static System.Reflection.MethodInfo? ResolveTryCastMethod(System.Type valueType, System.Type targetType)");
        builder.AppendLine("        {");
        builder.AppendLine("            string cacheKey = (valueType.AssemblyQualifiedName ?? valueType.FullName ?? valueType.Name) + \"|\" + (targetType.AssemblyQualifiedName ?? targetType.FullName ?? targetType.Name);");
        builder.AppendLine("            if (!TryCastCache.TryGetValue(cacheKey, out System.Reflection.MethodInfo? method))");
        builder.AppendLine("            {");
        builder.AppendLine("                method = FindTryCastMethod(valueType, targetType);");
        builder.AppendLine("                TryCastCache[cacheKey] = method;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return method;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static System.Reflection.MethodInfo? FindTryCastMethod(System.Type valueType, System.Type targetType)");
        builder.AppendLine("        {");
        builder.AppendLine("            for (System.Type? current = valueType; current is not null; current = current.BaseType)");
        builder.AppendLine("            {");
        builder.AppendLine("                foreach (System.Reflection.MethodInfo method in current.GetMethods(System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance))");
        builder.AppendLine("                {");
        builder.AppendLine("                    if (!method.Name.Equals(\"TryCast\", System.StringComparison.Ordinal) ||");
        builder.AppendLine("                        !method.IsGenericMethodDefinition ||");
        builder.AppendLine("                        method.GetGenericArguments().Length != 1 ||");
        builder.AppendLine("                        method.GetParameters().Length != 0)");
        builder.AppendLine("                    {");
        builder.AppendLine("                        continue;");
        builder.AppendLine("                    }");
        builder.AppendLine();
        builder.AppendLine("                    return method.MakeGenericMethod(targetType);");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return null;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool IsIl2CppObjectBase(System.Type valueType)");
        builder.AppendLine("        {");
        builder.AppendLine("            for (System.Type? current = valueType; current is not null; current = current.BaseType)");
        builder.AppendLine("            {");
        builder.AppendLine("                if (string.Equals(current.FullName, \"Il2CppInterop.Runtime.InteropTypes.Il2CppObjectBase\", System.StringComparison.Ordinal))");
        builder.AppendLine("                {");
        builder.AppendLine("                    return true;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return false;");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
    }

    private static void GenerateUnityRuntimeHelpers(StringBuilder builder)
    {
        builder.AppendLine();
        builder.AppendLine("    internal static class S1InteropUnity");
        builder.AppendLine("    {");
        builder.AppendLine("        private static global::System.Reflection.MethodInfo? cachedGameObjectGetComponentGeneric;");
        builder.AppendLine("        private static global::System.Reflection.MethodInfo? cachedGameObjectGetComponentsGeneric;");
        builder.AppendLine("        private static global::System.Reflection.MethodInfo? cachedObjectFindObjectsOfTypeGeneric;");
        builder.AppendLine();
        builder.AppendLine("        public static T? As<T>(object? value) where T : class => S1InteropObjectCast.As<T>(value);");
        builder.AppendLine();
        builder.AppendLine("        public static object? GetComponent(object? gameObject, global::System.Type? componentType)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (gameObject is null || componentType is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return null;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                global::System.Reflection.MethodInfo? method = cachedGameObjectGetComponentGeneric ??= FindGenericGetComponent(gameObject.GetType());");
        builder.AppendLine("                if (method is null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return null;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                return method.MakeGenericMethod(componentType).Invoke(gameObject, null);"); 
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("                return null;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static global::System.Collections.IEnumerable GetComponents(object? gameObject, global::System.Type? componentType)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (gameObject is null || componentType is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return global::System.Array.Empty<object>();");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                global::System.Reflection.MethodInfo? method = cachedGameObjectGetComponentsGeneric ??= FindGenericGetComponents(gameObject.GetType());");
        builder.AppendLine("                if (method is null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return global::System.Array.Empty<object>();");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                return method.MakeGenericMethod(componentType).Invoke(gameObject, null) as global::System.Collections.IEnumerable ?? global::System.Array.Empty<object>();");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("                return global::System.Array.Empty<object>();");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static global::System.Collections.IEnumerable FindObjectsOfType(global::System.Type? objectType)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (objectType is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return global::System.Array.Empty<object>();");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                global::System.Reflection.MethodInfo? method = cachedObjectFindObjectsOfTypeGeneric ??= FindGenericFindObjectsOfType();");
        builder.AppendLine("                if (method is null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return global::System.Array.Empty<object>();");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                return method.MakeGenericMethod(objectType).Invoke(null, null) as global::System.Collections.IEnumerable ?? global::System.Array.Empty<object>();");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("                return global::System.Array.Empty<object>();");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static global::System.Reflection.MethodInfo? FindGenericGetComponent(global::System.Type gameObjectType)");
        builder.AppendLine("        {");
        builder.AppendLine("            foreach (global::System.Reflection.MethodInfo method in gameObjectType.GetMethods(global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.Instance))");
        builder.AppendLine("            {");
        builder.AppendLine("                if (method.Name == \"GetComponent\" && method.IsGenericMethodDefinition && method.GetParameters().Length == 0)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return method;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return null;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static global::System.Reflection.MethodInfo? FindGenericGetComponents(global::System.Type gameObjectType)");
        builder.AppendLine("        {");
        builder.AppendLine("            foreach (global::System.Reflection.MethodInfo method in gameObjectType.GetMethods(global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.Instance))");
        builder.AppendLine("            {");
        builder.AppendLine("                if (method.Name == \"GetComponents\" && method.IsGenericMethodDefinition && method.GetParameters().Length == 0)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return method;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return null;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static global::System.Reflection.MethodInfo? FindGenericFindObjectsOfType()");
        builder.AppendLine("        {");
        builder.AppendLine("            global::System.Type? unityObjectType = S1InteropTypeRegistry.Resolve(\"UnityEngine.Object\");");
        builder.AppendLine("            if (unityObjectType is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return null;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            foreach (global::System.Reflection.MethodInfo method in unityObjectType.GetMethods(global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.Static))");
        builder.AppendLine("            {");
        builder.AppendLine("                if (method.Name == \"FindObjectsOfType\" && method.IsGenericMethodDefinition && method.GetParameters().Length == 0)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return method;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return null;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static global::System.Collections.IEnumerable FindObjectsOfTypeAll(global::System.Type? objectType)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (objectType is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return global::System.Array.Empty<object>();");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                object? objects = S1InteropTypeRegistry.Resolve(\"UnityEngine.Resources\")");
        builder.AppendLine("                    ?.GetMethod(\"FindObjectsOfTypeAll\", new[] { typeof(global::System.Type) })");
        builder.AppendLine("                    ?.Invoke(null, new object[] { objectType });");
        builder.AppendLine();
        builder.AppendLine("                return objects as global::System.Collections.IEnumerable ?? global::System.Array.Empty<object>();");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("                return global::System.Array.Empty<object>();");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
    }

    private static void GenerateSteamNetworkingRuntimeHelpers(StringBuilder builder)
    {
        builder.AppendLine();
        builder.AppendLine("    internal static class S1InteropSteamNetworking");
        builder.AppendLine("    {");
        builder.AppendLine("        private static global::System.Type? cachedSteamNetworkingType;");
        builder.AppendLine("        private static global::System.Type? cachedSteamApiType;");
        builder.AppendLine("        private static global::System.Type? cachedP2PSendType;");
        builder.AppendLine("        private static global::System.Reflection.MethodInfo? cachedIsSteamRunning;");
        builder.AppendLine("        private static global::System.Reflection.MethodInfo? cachedRunCallbacks;");
        builder.AppendLine("        private static global::System.Reflection.MethodInfo? cachedAllowP2PPacketRelay;");
        builder.AppendLine("        private static global::System.Reflection.MethodInfo? cachedAcceptP2PSessionWithUser;");
        builder.AppendLine("        private static global::System.Reflection.MethodInfo? cachedIsP2PPacketAvailable;");
        builder.AppendLine("        private static global::System.Reflection.MethodInfo? cachedReadP2PPacket;");
        builder.AppendLine("        private static global::System.Reflection.MethodInfo? cachedSendP2PPacket;");
        builder.AppendLine("        private static global::System.Type? cachedIl2CppStructArrayByteType;");
        builder.AppendLine();
        builder.AppendLine("        public static bool IsAvailable => ResolveSteamNetworkingType() is not null;");
        builder.AppendLine();
        builder.AppendLine("        public static bool IsSteamRunning()");
        builder.AppendLine("        {");
        builder.AppendLine("            object? result = InvokeSteamApi(ref cachedIsSteamRunning, \"IsSteamRunning\");");
        builder.AppendLine("            return result is bool running && running;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static void RunCallbacks()");
        builder.AppendLine("        {");
        builder.AppendLine("            InvokeSteamApi(ref cachedRunCallbacks, \"RunCallbacks\");");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static bool AllowP2PPacketRelay(bool allow)");
        builder.AppendLine("        {");
        builder.AppendLine("            object? result = InvokeSteamNetworking(ref cachedAllowP2PPacketRelay, \"AllowP2PPacketRelay\", allow);");
        builder.AppendLine("            return result is bool value && value;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static bool AcceptP2PSessionWithUser(object? target)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (target is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            object? result = InvokeSteamNetworking(ref cachedAcceptP2PSessionWithUser, \"AcceptP2PSessionWithUser\", target);");
        builder.AppendLine("            return result is bool value && value;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static object? GetReliableP2PSendMode() => GetP2PSendMode(\"k_EP2PSendReliable\");");
        builder.AppendLine();
        builder.AppendLine("        public static object? GetP2PSendMode(string enumName)");
        builder.AppendLine("        {");
        builder.AppendLine("            global::System.Type? enumType = cachedP2PSendType ??= ResolveP2PSendType();");
        builder.AppendLine("            if (enumType?.IsEnum != true || global::System.String.IsNullOrWhiteSpace(enumName))");
        builder.AppendLine("            {");
        builder.AppendLine("                return null;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                return global::System.Enum.Parse(enumType, enumName);");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("                return null;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static bool TryGetAvailableP2PPacketSize(int channel, out uint packetSize)");
        builder.AppendLine("        {");
        builder.AppendLine("            packetSize = 0;");
        builder.AppendLine("            global::System.Reflection.MethodInfo? method = cachedIsP2PPacketAvailable ??= FindSteamNetworkingMethod(\"IsP2PPacketAvailable\", 2);");
        builder.AppendLine("            if (method is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            global::System.Reflection.ParameterInfo[] parameters = method.GetParameters();");
        builder.AppendLine("            object?[] args = { CreateOutValue(parameters[0].ParameterType), channel };");
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                if (method.Invoke(null, args) is bool available && available)");
        builder.AppendLine("                {");
        builder.AppendLine("                    packetSize = global::System.Convert.ToUInt32(args[0], global::System.Globalization.CultureInfo.InvariantCulture);");
        builder.AppendLine("                    return true;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return false;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static bool TryReadP2PPacket(int channel, uint maxPacketSize, out object? sender, out byte[] data, out uint packetSize, out bool discarded)");
        builder.AppendLine("        {");
        builder.AppendLine("            sender = null;");
        builder.AppendLine("            data = global::System.Array.Empty<byte>();");
        builder.AppendLine("            packetSize = 0;");
        builder.AppendLine("            discarded = false;");
        builder.AppendLine("            if (!TryGetAvailableP2PPacketSize(channel, out packetSize) || packetSize == 0)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (packetSize > maxPacketSize)");
        builder.AppendLine("            {");
        builder.AppendLine("                discarded = true;");
        builder.AppendLine("                return TryDiscardP2PPacket(packetSize, channel);");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            object? buffer;");
        builder.AppendLine("            global::System.Reflection.MethodInfo? method = cachedReadP2PPacket;");
        builder.AppendLine("            if (method is null || !TryCreateReadBuffer(method, packetSize, out buffer))");
        builder.AppendLine("            {");
        builder.AppendLine("                method = FindReadP2PPacket(packetSize, out buffer);");
        builder.AppendLine("                if (method is null || buffer is null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return false;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                cachedReadP2PPacket = method;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            global::System.Reflection.ParameterInfo[] parameters = method.GetParameters();");
        builder.AppendLine("            if (buffer is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            object?[] args =");
        builder.AppendLine("            {");
        builder.AppendLine("                buffer,");
        builder.AppendLine("                packetSize,");
        builder.AppendLine("                CreateOutValue(parameters[2].ParameterType),");
        builder.AppendLine("                CreateOutValue(parameters[3].ParameterType),");
        builder.AppendLine("                channel");
        builder.AppendLine("            };");
        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                if (method.Invoke(null, args) is not bool success || !success)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return false;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                uint bytesRead = global::System.Convert.ToUInt32(args[2], global::System.Globalization.CultureInfo.InvariantCulture);");
        builder.AppendLine("                sender = args[3];");
        builder.AppendLine("                data = CopyByteBuffer(buffer, bytesRead);");
        builder.AppendLine("                return true;");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static bool SendP2PPacket(object? target, byte[]? data, object? sendType, int channel)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (target is null || data is null || sendType is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            object? packetBuffer;");
        builder.AppendLine("            global::System.Reflection.MethodInfo? method = cachedSendP2PPacket;");
        builder.AppendLine("            if (method is null || !TryCreateSendBuffer(method, target, data, sendType, out packetBuffer))");
        builder.AppendLine("            {");
        builder.AppendLine("                method = FindSendP2PPacket(target, data, sendType, out packetBuffer);");
        builder.AppendLine("                if (method is null || packetBuffer is null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return false;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                cachedSendP2PPacket = method;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (!CopyToByteBuffer(data, packetBuffer))");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            object?[] args = { target, packetBuffer, (uint)data.Length, sendType, channel };");
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                return method.Invoke(null, args) is bool result && result;");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static ulong GetSteamIdValue(object? steamId)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (steamId is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return 0UL;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (steamId is ulong numeric)");
        builder.AppendLine("            {");
        builder.AppendLine("                return numeric;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            global::System.Reflection.FieldInfo? field = steamId.GetType().GetField(\"m_SteamID\", global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic);");
        builder.AppendLine("            object? value = field?.GetValue(steamId);");
        builder.AppendLine("            if (value is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                global::System.Reflection.PropertyInfo? property = steamId.GetType().GetProperty(\"SteamId\", global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic);");
        builder.AppendLine("                value = property?.GetValue(steamId, null);");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                return value is null ? 0UL : global::System.Convert.ToUInt64(value, global::System.Globalization.CultureInfo.InvariantCulture);");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("                return 0UL;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryDiscardP2PPacket(uint packetSize, int channel)");
        builder.AppendLine("        {");
        builder.AppendLine("            object? buffer;");
        builder.AppendLine("            global::System.Reflection.MethodInfo? method = cachedReadP2PPacket;");
        builder.AppendLine("            if (method is null || !TryCreateReadBuffer(method, packetSize, out buffer))");
        builder.AppendLine("            {");
        builder.AppendLine("                method = FindReadP2PPacket(packetSize, out buffer);");
        builder.AppendLine("                if (method is null || buffer is null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return false;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                cachedReadP2PPacket = method;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            global::System.Reflection.ParameterInfo[] parameters = method.GetParameters();");
        builder.AppendLine("            if (buffer is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            object?[] args = { buffer, packetSize, CreateOutValue(parameters[2].ParameterType), CreateOutValue(parameters[3].ParameterType), channel };");
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                return method.Invoke(null, args) is bool result && result;");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static global::System.Reflection.MethodInfo? FindSteamNetworkingMethod(string methodName, int parameterCount)");
        builder.AppendLine("        {");
        builder.AppendLine("            global::System.Type? type = cachedSteamNetworkingType ??= ResolveSteamNetworkingType();");
        builder.AppendLine("            if (type is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return null;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            foreach (global::System.Reflection.MethodInfo method in type.GetMethods(global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.Static))");
        builder.AppendLine("            {");
        builder.AppendLine("                if (global::System.String.Equals(method.Name, methodName, global::System.StringComparison.Ordinal) && method.GetParameters().Length == parameterCount)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return method;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return null;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static global::System.Reflection.MethodInfo? FindReadP2PPacket(uint packetSize, out object? buffer)");
        builder.AppendLine("        {");
        builder.AppendLine("            buffer = null;");
        builder.AppendLine("            global::System.Type? type = cachedSteamNetworkingType ??= ResolveSteamNetworkingType();");
        builder.AppendLine("            if (type is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return null;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            foreach (global::System.Reflection.MethodInfo method in type.GetMethods(global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.Static))");
        builder.AppendLine("            {");
        builder.AppendLine("                if (global::System.String.Equals(method.Name, \"ReadP2PPacket\", global::System.StringComparison.Ordinal) && TryCreateReadBuffer(method, packetSize, out buffer))");
        builder.AppendLine("                {");
        builder.AppendLine("                    return method;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return null;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryCreateReadBuffer(global::System.Reflection.MethodInfo method, uint packetSize, out object? buffer)");
        builder.AppendLine("        {");
        builder.AppendLine("            buffer = null;");
        builder.AppendLine("            global::System.Reflection.ParameterInfo[] parameters = method.GetParameters();");
        builder.AppendLine("            if (parameters.Length != 5)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            buffer = CreateByteBuffer(parameters[0].ParameterType, packetSize);");
        builder.AppendLine("            return buffer is not null;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static global::System.Reflection.MethodInfo? FindSendP2PPacket(object target, byte[] data, object sendType, out object? packetBuffer)");
        builder.AppendLine("        {");
        builder.AppendLine("            packetBuffer = null;");
        builder.AppendLine("            global::System.Type? type = cachedSteamNetworkingType ??= ResolveSteamNetworkingType();");
        builder.AppendLine("            if (type is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return null;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            foreach (global::System.Reflection.MethodInfo method in type.GetMethods(global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.Static))");
        builder.AppendLine("            {");
        builder.AppendLine("                if (global::System.String.Equals(method.Name, \"SendP2PPacket\", global::System.StringComparison.Ordinal) && TryCreateSendBuffer(method, target, data, sendType, out packetBuffer))");
        builder.AppendLine("                {");
        builder.AppendLine("                    return method;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return null;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryCreateSendBuffer(global::System.Reflection.MethodInfo method, object target, byte[] data, object sendType, out object? packetBuffer)");
        builder.AppendLine("        {");
        builder.AppendLine("            packetBuffer = null;");
        builder.AppendLine("            global::System.Reflection.ParameterInfo[] parameters = method.GetParameters();");
        builder.AppendLine("            if (parameters.Length != 5 || !parameters[0].ParameterType.IsInstanceOfType(target) || !parameters[3].ParameterType.IsInstanceOfType(sendType))");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            packetBuffer = CreateByteBuffer(parameters[1].ParameterType, (uint)data.Length);");
        builder.AppendLine("            return packetBuffer is not null;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static global::System.Type? ResolveSteamNetworkingType()");
        builder.AppendLine("        {");
        builder.AppendLine("            string typeName = S1InteropTypeRegistry.GetRuntimeTypeName(\"Steamworks.SteamNetworking\", \"Il2CppSteamworks.SteamNetworking\");");
        builder.AppendLine("            return S1InteropTypeRegistry.Resolve(typeName);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static global::System.Type? ResolveSteamApiType()");
        builder.AppendLine("        {");
        builder.AppendLine("            string typeName = S1InteropTypeRegistry.GetRuntimeTypeName(\"Steamworks.SteamAPI\", \"Il2CppSteamworks.SteamAPI\");");
        builder.AppendLine("            return S1InteropTypeRegistry.Resolve(typeName);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static global::System.Type? ResolveP2PSendType()");
        builder.AppendLine("        {");
        builder.AppendLine("            string typeName = S1InteropTypeRegistry.GetRuntimeTypeName(\"Steamworks.EP2PSend\", \"Il2CppSteamworks.EP2PSend\");");
        builder.AppendLine("            return S1InteropTypeRegistry.Resolve(typeName);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static object? InvokeSteamApi(ref global::System.Reflection.MethodInfo? cachedMethod, string methodName, params object?[] args)");
        builder.AppendLine("        {");
        builder.AppendLine("            global::System.Type? type = cachedSteamApiType ??= ResolveSteamApiType();");
        builder.AppendLine("            return InvokeStatic(type, ref cachedMethod, methodName, args);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static object? InvokeSteamNetworking(ref global::System.Reflection.MethodInfo? cachedMethod, string methodName, params object?[] args)");
        builder.AppendLine("        {");
        builder.AppendLine("            global::System.Type? type = cachedSteamNetworkingType ??= ResolveSteamNetworkingType();");
        builder.AppendLine("            return InvokeStatic(type, ref cachedMethod, methodName, args);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static object? InvokeStatic(global::System.Type? ownerType, ref global::System.Reflection.MethodInfo? cachedMethod, string methodName, params object?[] args)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (ownerType is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return null;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            global::System.Reflection.MethodInfo? method = cachedMethod;");
        builder.AppendLine("            object?[]? convertedArgs;");
        builder.AppendLine("            if (method is null || !TryConvertArguments(method, args, out convertedArgs))");
        builder.AppendLine("            {");
        builder.AppendLine("                method = FindStaticMethod(ownerType, methodName, args, out convertedArgs);");
        builder.AppendLine("                if (method is null || convertedArgs is null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return null;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                cachedMethod = method;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                return method.Invoke(null, convertedArgs);");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("                return null;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static global::System.Reflection.MethodInfo? FindStaticMethod(global::System.Type ownerType, string methodName, object?[] args, out object?[]? convertedArgs)");
        builder.AppendLine("        {");
        builder.AppendLine("            convertedArgs = null;");
        builder.AppendLine("            foreach (global::System.Reflection.MethodInfo method in ownerType.GetMethods(global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.Static))");
        builder.AppendLine("            {");
        builder.AppendLine("                if (global::System.String.Equals(method.Name, methodName, global::System.StringComparison.Ordinal) && TryConvertArguments(method, args, out convertedArgs))");
        builder.AppendLine("                {");
        builder.AppendLine("                    return method;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return null;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryConvertArguments(global::System.Reflection.MethodInfo method, object?[] args, out object?[]? convertedArgs)");
        builder.AppendLine("        {");
        builder.AppendLine("            convertedArgs = null;");
        builder.AppendLine("            global::System.Reflection.ParameterInfo[] parameters = method.GetParameters();");
        builder.AppendLine("            if (parameters.Length != args.Length)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            object?[] converted = new object?[args.Length];");
        builder.AppendLine("            for (int index = 0; index < args.Length; index++)");
        builder.AppendLine("            {");
        builder.AppendLine("                if (!TryConvertArgument(args[index], parameters[index].ParameterType, out converted[index]))");
        builder.AppendLine("                {");
        builder.AppendLine("                    return false;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            convertedArgs = converted;");
        builder.AppendLine("            return true;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryConvertArgument(object? value, global::System.Type parameterType, out object? converted)");
        builder.AppendLine("        {");
        builder.AppendLine("            converted = value;");
        builder.AppendLine("            if (value is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return !parameterType.IsValueType || global::System.Nullable.GetUnderlyingType(parameterType) is not null;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (parameterType.IsInstanceOfType(value))");
        builder.AppendLine("            {");
        builder.AppendLine("                return true;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                global::System.Type targetType = global::System.Nullable.GetUnderlyingType(parameterType) ?? parameterType;");
        builder.AppendLine("                if (targetType.IsEnum)");
        builder.AppendLine("                {");
        builder.AppendLine("                    converted = value is string name ? global::System.Enum.Parse(targetType, name) : global::System.Enum.ToObject(targetType, value);");
        builder.AppendLine("                    return true;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                if (value is global::System.IConvertible)");
        builder.AppendLine("                {");
        builder.AppendLine("                    converted = global::System.Convert.ChangeType(value, targetType, global::System.Globalization.CultureInfo.InvariantCulture);");
        builder.AppendLine("                    return true;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return false;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static object? CreateByteBuffer(global::System.Type parameterType, uint size)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (parameterType == typeof(byte[]) || parameterType.IsAssignableFrom(typeof(byte[])))");
        builder.AppendLine("            {");
        builder.AppendLine("                return new byte[size];");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            global::System.Type? il2CppArrayType = cachedIl2CppStructArrayByteType ??= S1InteropTypeRegistry.Resolve(\"Il2CppInterop.Runtime.InteropTypes.Arrays.Il2CppStructArray`1\")?.MakeGenericType(typeof(byte));");
        builder.AppendLine("            if (il2CppArrayType is not null && parameterType.IsAssignableFrom(il2CppArrayType))");
        builder.AppendLine("            {");
        builder.AppendLine("                return global::System.Activator.CreateInstance(il2CppArrayType, size);");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return null;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static object? CreateOutValue(global::System.Type byRefType)");
        builder.AppendLine("        {");
        builder.AppendLine("            global::System.Type valueType = byRefType.IsByRef ? byRefType.GetElementType()! : byRefType;");
        builder.AppendLine("            return valueType.IsValueType ? global::System.Activator.CreateInstance(valueType) : null;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool CopyToByteBuffer(byte[] source, object buffer)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (buffer is byte[] bytes)");
        builder.AppendLine("            {");
        builder.AppendLine("                global::System.Array.Copy(source, bytes, source.Length);");
        builder.AppendLine("                return true;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            global::System.Reflection.PropertyInfo? itemProperty = buffer.GetType().GetProperty(\"Item\");");
        builder.AppendLine("            global::System.Reflection.MethodInfo? setter = itemProperty?.GetSetMethod();");
        builder.AppendLine("            global::System.Reflection.ParameterInfo[]? indexParameters = itemProperty?.GetIndexParameters();");
        builder.AppendLine("            if (setter is null || indexParameters is null || indexParameters.Length == 0)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            global::System.Type indexType = indexParameters[0].ParameterType;");
        builder.AppendLine("            for (int index = 0; index < source.Length; index++)");
        builder.AppendLine("            {");
        builder.AppendLine("                object convertedIndex = global::System.Convert.ChangeType(index, indexType, global::System.Globalization.CultureInfo.InvariantCulture);");
        builder.AppendLine("                setter.Invoke(buffer, new object[] { convertedIndex, source[index] });");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return true;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static byte[] CopyByteBuffer(object buffer, uint bytesRead)");
        builder.AppendLine("        {");
        builder.AppendLine("            int count = checked((int)bytesRead);");
        builder.AppendLine("            if (buffer is byte[] bytes)");
        builder.AppendLine("            {");
        builder.AppendLine("                if (bytes.Length == count)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return bytes;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                byte[] trimmed = new byte[count];");
        builder.AppendLine("                global::System.Array.Copy(bytes, trimmed, count);");
        builder.AppendLine("                return trimmed;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            byte[] result = new byte[count];");
        builder.AppendLine("            global::System.Reflection.PropertyInfo? itemProperty = buffer.GetType().GetProperty(\"Item\");");
        builder.AppendLine("            global::System.Reflection.MethodInfo? getter = itemProperty?.GetGetMethod();");
        builder.AppendLine("            global::System.Reflection.ParameterInfo[]? indexParameters = itemProperty?.GetIndexParameters();");
        builder.AppendLine("            if (getter is null || indexParameters is null || indexParameters.Length == 0)");
        builder.AppendLine("            {");
        builder.AppendLine("                return result;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            global::System.Type indexType = indexParameters[0].ParameterType;");
        builder.AppendLine("            for (int index = 0; index < count; index++)");
        builder.AppendLine("            {");
        builder.AppendLine("                object convertedIndex = global::System.Convert.ChangeType(index, indexType, global::System.Globalization.CultureInfo.InvariantCulture);");
        builder.AppendLine("                object? value = getter.Invoke(buffer, new object[] { convertedIndex });");
        builder.AppendLine("                result[index] = value is null ? (byte)0 : global::System.Convert.ToByte(value, global::System.Globalization.CultureInfo.InvariantCulture);");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return result;");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
    }

    private static void GenerateSteamLobbyRuntimeHelpers(StringBuilder builder)
    {
        builder.AppendLine();
        builder.AppendLine("    internal readonly struct S1InteropSteamLobbySnapshot");
        builder.AppendLine("    {");
        builder.AppendLine("        public S1InteropSteamLobbySnapshot(object? lobby, bool isInLobby, bool isHost, int playerCount, object? lobbySteamId, object? localPlayerId)");
        builder.AppendLine("        {");
        builder.AppendLine("            Lobby = lobby;");
        builder.AppendLine("            IsInLobby = isInLobby;");
        builder.AppendLine("            IsHost = isHost;");
        builder.AppendLine("            PlayerCount = playerCount;");
        builder.AppendLine("            LobbySteamId = lobbySteamId;");
        builder.AppendLine("            LocalPlayerId = localPlayerId;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public object? Lobby { get; }");
        builder.AppendLine("        public bool HasValue => Lobby is not null;");
        builder.AppendLine("        public bool IsInLobby { get; }");
        builder.AppendLine("        public bool IsHost { get; }");
        builder.AppendLine("        public int PlayerCount { get; }");
        builder.AppendLine("        public object? LobbySteamId { get; }");
        builder.AppendLine("        public object? LocalPlayerId { get; }");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    internal static class S1InteropSteamLobby");
        builder.AppendLine("    {");
        builder.AppendLine("        private static global::System.Type? cachedSteamMatchmakingType;");
        builder.AppendLine("        private static global::System.Reflection.MethodInfo? cachedGetLobbyOwner;");
        builder.AppendLine("        private static global::System.Reflection.MethodInfo? cachedGetNumLobbyMembers;");
        builder.AppendLine("        private static global::System.Reflection.MethodInfo? cachedGetLobbyMemberByIndex;");
        builder.AppendLine();
        builder.AppendLine("        public static bool TryGetCurrentLobby(out S1InteropSteamLobbySnapshot snapshot)");
        builder.AppendLine("        {");
        builder.AppendLine("            snapshot = default;");
        builder.AppendLine("            object? lobby = S1InteropTypeRegistry.GetSingletonInstance(\"ScheduleOne.Networking.Lobby\");");
        builder.AppendLine("            if (lobby is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            bool isInLobby = S1InteropMemberRegistry.GetInstanceValue(lobby, \"IsInLobby\") is bool inLobby && inLobby;");
        builder.AppendLine("            bool isHost = S1InteropMemberRegistry.GetInstanceValue(lobby, \"IsHost\") is bool host && host;");
        builder.AppendLine("            int playerCount = ToInt32(S1InteropMemberRegistry.GetInstanceValue(lobby, \"PlayerCount\"));");
        builder.AppendLine("            snapshot = new S1InteropSteamLobbySnapshot(");
        builder.AppendLine("                lobby,");
        builder.AppendLine("                isInLobby,");
        builder.AppendLine("                isHost,");
        builder.AppendLine("                playerCount,");
        builder.AppendLine("                S1InteropMemberRegistry.GetInstanceValue(lobby, \"LobbySteamID\"),");
        builder.AppendLine("                S1InteropMemberRegistry.GetInstanceValue(lobby, \"LocalPlayerID\"));");
        builder.AppendLine("            return true;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static bool TryGetHostId(S1InteropSteamLobbySnapshot lobby, out object? hostId)");
        builder.AppendLine("        {");
        builder.AppendLine("            hostId = null;");
        builder.AppendLine("            if (!lobby.HasValue || lobby.LobbySteamId is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            hostId = InvokeSteamMatchmaking(ref cachedGetLobbyOwner, \"GetLobbyOwner\", lobby.LobbySteamId);");
        builder.AppendLine("            return GetSteamIdValue(hostId) != 0UL;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static global::System.Collections.Generic.IEnumerable<object> GetLobbyMembers(S1InteropSteamLobbySnapshot lobby)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (!lobby.HasValue || lobby.LobbySteamId is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                yield break;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            int count = ToInt32(InvokeSteamMatchmaking(ref cachedGetNumLobbyMembers, \"GetNumLobbyMembers\", lobby.LobbySteamId));");
        builder.AppendLine("            if (count <= 0)");
        builder.AppendLine("            {");
        builder.AppendLine("                count = lobby.PlayerCount;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            for (int index = 0; index < count; index++)");
        builder.AppendLine("            {");
        builder.AppendLine("                object? member = InvokeSteamMatchmaking(ref cachedGetLobbyMemberByIndex, \"GetLobbyMemberByIndex\", lobby.LobbySteamId, index);");
        builder.AppendLine("                if (member is not null && GetSteamIdValue(member) != 0UL)");
        builder.AppendLine("                {");
        builder.AppendLine("                    yield return member;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static ulong GetSteamIdValue(object? steamId) => S1InteropSteamNetworking.GetSteamIdValue(steamId);");
        builder.AppendLine();
        builder.AppendLine("        public static bool SameSteamId(object? left, object? right) => GetSteamIdValue(left) == GetSteamIdValue(right);");
        builder.AppendLine();
        builder.AppendLine("        private static object? InvokeSteamMatchmaking(ref global::System.Reflection.MethodInfo? cachedMethod, string methodName, params object?[] args)");
        builder.AppendLine("        {");
        builder.AppendLine("            global::System.Reflection.MethodInfo? method = cachedMethod;");
        builder.AppendLine("            object?[]? convertedArgs;");
        builder.AppendLine("            if (method is null || !TryConvertArguments(method, args, out convertedArgs))");
        builder.AppendLine("            {");
        builder.AppendLine("                method = FindSteamMatchmakingMethod(methodName, args, out convertedArgs);");
        builder.AppendLine("                if (method is null || convertedArgs is null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return null;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                cachedMethod = method;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                return method.Invoke(null, convertedArgs);");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("                return null;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static global::System.Reflection.MethodInfo? FindSteamMatchmakingMethod(string methodName, object?[] args, out object?[]? convertedArgs)");
        builder.AppendLine("        {");
        builder.AppendLine("            convertedArgs = null;");
        builder.AppendLine("            global::System.Type? type = cachedSteamMatchmakingType ??= ResolveSteamMatchmakingType();");
        builder.AppendLine("            if (type is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return null;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            foreach (global::System.Reflection.MethodInfo method in type.GetMethods(global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.Static))");
        builder.AppendLine("            {");
        builder.AppendLine("                if (global::System.String.Equals(method.Name, methodName, global::System.StringComparison.Ordinal) && TryConvertArguments(method, args, out convertedArgs))");
        builder.AppendLine("                {");
        builder.AppendLine("                    return method;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return null;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryConvertArguments(global::System.Reflection.MethodInfo method, object?[] args, out object?[]? convertedArgs)");
        builder.AppendLine("        {");
        builder.AppendLine("            convertedArgs = null;");
        builder.AppendLine("            global::System.Reflection.ParameterInfo[] parameters = method.GetParameters();");
        builder.AppendLine("            if (parameters.Length != args.Length)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            object?[] converted = new object?[args.Length];");
        builder.AppendLine("            for (int index = 0; index < args.Length; index++)");
        builder.AppendLine("            {");
        builder.AppendLine("                if (!TryConvertArgument(args[index], parameters[index].ParameterType, out converted[index]))");
        builder.AppendLine("                {");
        builder.AppendLine("                    return false;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            convertedArgs = converted;");
        builder.AppendLine("            return true;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryConvertArgument(object? value, global::System.Type parameterType, out object? converted)");
        builder.AppendLine("        {");
        builder.AppendLine("            converted = value;");
        builder.AppendLine("            if (value is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return !parameterType.IsValueType || global::System.Nullable.GetUnderlyingType(parameterType) is not null;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (parameterType.IsInstanceOfType(value))");
        builder.AppendLine("            {");
        builder.AppendLine("                return true;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                global::System.Type targetType = global::System.Nullable.GetUnderlyingType(parameterType) ?? parameterType;");
        builder.AppendLine("                if (targetType.IsEnum)");
        builder.AppendLine("                {");
        builder.AppendLine("                    converted = value is string name ? global::System.Enum.Parse(targetType, name) : global::System.Enum.ToObject(targetType, value);");
        builder.AppendLine("                    return true;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                if (value is global::System.IConvertible)");
        builder.AppendLine("                {");
        builder.AppendLine("                    converted = global::System.Convert.ChangeType(value, targetType, global::System.Globalization.CultureInfo.InvariantCulture);");
        builder.AppendLine("                    return true;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return false;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static int ToInt32(object? value)");
        builder.AppendLine("        {");
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                return value is null ? 0 : global::System.Convert.ToInt32(value, global::System.Globalization.CultureInfo.InvariantCulture);");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("                return 0;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static global::System.Type? ResolveSteamMatchmakingType()");
        builder.AppendLine("        {");
        builder.AppendLine("            string typeName = S1InteropTypeRegistry.GetRuntimeTypeName(\"Steamworks.SteamMatchmaking\", \"Il2CppSteamworks.SteamMatchmaking\");");
        builder.AppendLine("            return S1InteropTypeRegistry.Resolve(typeName);");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
    }

    private static string SanitizeLocalName(string value)
    {
        var builder = new StringBuilder();
        foreach (char character in value)
        {
            builder.Append(char.IsLetterOrDigit(character) ? character : '_');
        }

        return builder.ToString();
    }

    private static void GenerateDelegateBridge(StringBuilder builder)
    {
        builder.AppendLine();
        builder.AppendLine("    internal static class S1InteropDelegateBridge");
        builder.AppendLine("    {");
        builder.AppendLine("        private static readonly System.Collections.Generic.Dictionary<string, System.Reflection.MethodInfo?> ConvertDelegateCache = new System.Collections.Generic.Dictionary<string, System.Reflection.MethodInfo?>(System.StringComparer.Ordinal);");
        builder.AppendLine();
        builder.AppendLine("        public static TDelegate? Convert<TDelegate>(TDelegate? listener) where TDelegate : class");
        builder.AppendLine("        {");
        builder.AppendLine("            if (listener is null || !S1InteropRuntime.IsIl2Cpp || listener is not System.Delegate delegateValue)");
        builder.AppendLine("            {");
        builder.AppendLine("                return listener;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Reflection.MethodInfo? convertDelegate = ResolveConvertDelegate(typeof(TDelegate));");
        builder.AppendLine("            if (convertDelegate is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return listener;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                return convertDelegate.Invoke(null, new object[] { delegateValue }) as TDelegate ?? listener;");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("                return listener;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static System.Reflection.MethodInfo? ResolveConvertDelegate(System.Type delegateType)");
        builder.AppendLine("        {");
        builder.AppendLine("            string cacheKey = delegateType.AssemblyQualifiedName ?? delegateType.FullName ?? delegateType.Name;");
        builder.AppendLine("            if (!ConvertDelegateCache.TryGetValue(cacheKey, out System.Reflection.MethodInfo? method))");
        builder.AppendLine("            {");
        builder.AppendLine("                method = FindConvertDelegateMethod(delegateType);");
        builder.AppendLine("                ConvertDelegateCache[cacheKey] = method;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return method;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static System.Reflection.MethodInfo? FindConvertDelegateMethod(System.Type delegateType)");
        builder.AppendLine("        {");
        builder.AppendLine("            System.Type? delegateSupport = ResolveType(\"Il2CppInterop.Runtime.DelegateSupport\");");
        builder.AppendLine("            if (delegateSupport is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return null;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            foreach (System.Reflection.MethodInfo method in delegateSupport.GetMethods(System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Static))");
        builder.AppendLine("            {");
        builder.AppendLine("                if (!method.Name.Equals(\"ConvertDelegate\", System.StringComparison.Ordinal) ||");
        builder.AppendLine("                    !method.IsGenericMethodDefinition ||");
        builder.AppendLine("                    method.GetGenericArguments().Length != 1 ||");
        builder.AppendLine("                    method.GetParameters().Length != 1)");
        builder.AppendLine("                {");
        builder.AppendLine("                    continue;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                return method.MakeGenericMethod(delegateType);");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return null;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static System.Type? ResolveType(string typeName)");
        builder.AppendLine("        {");
        builder.AppendLine("            System.Type? type = System.Type.GetType(typeName, throwOnError: false);");
        builder.AppendLine("            if (type is not null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return type;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            foreach (System.Reflection.Assembly assembly in System.AppDomain.CurrentDomain.GetAssemblies())");
        builder.AppendLine("            {");
        builder.AppendLine("                type = assembly.GetType(typeName, throwOnError: false);");
        builder.AppendLine("                if (type is not null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return type;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return null;");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
    }
}
