using System.Text;

namespace S1Interop.Generators;

public sealed partial class S1InteropTypeRegistryGenerator
{
    private static void GenerateMemberInvocationHelpers(StringBuilder builder)
    {
        builder.AppendLine("        public static object? Invoke(string ownerTypeName, string memberName, string[]? parameterTypeNames, object? instance, params object?[] args)");
        builder.AppendLine("        {");
        builder.AppendLine("            return Invoke(ResolveMethod(ownerTypeName, memberName, parameterTypeNames), instance, args);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static object? InvokeInstance(object? instance, string memberName, params object?[] args)");
        builder.AppendLine("        {");
        builder.AppendLine("            return InvokeInstance(instance, memberName, null, args);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static object? InvokeInstance(object? instance, string memberName, string[]? parameterTypeNames, params object?[] args)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (instance is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return null;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return Invoke(ResolveMemberCached(instance.GetType(), memberName, parameterTypeNames, S1InteropMemberKind.Method) as System.Reflection.MethodInfo, instance, args);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static bool TryInvokeInstance(object? instance, string memberName, out object? result, params object?[] args)");
        builder.AppendLine("        {");
        builder.AppendLine("            return TryInvokeInstance(instance, memberName, null, out result, args);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static bool TryInvokeInstance(object? instance, string memberName, string[]? parameterTypeNames, out object? result, params object?[] args)");
        builder.AppendLine("        {");
        builder.AppendLine("            result = null;");
        builder.AppendLine("            if (instance is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return TryInvoke(ResolveMemberCached(instance.GetType(), memberName, parameterTypeNames, S1InteropMemberKind.Method) as System.Reflection.MethodInfo, instance, out result, args);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static object? InvokeStatic(System.Type? ownerType, string memberName, params object?[] args)");
        builder.AppendLine("        {");
        builder.AppendLine("            return InvokeStatic(ownerType, memberName, parameterTypeNames: null, args);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static object? InvokeStatic(System.Type? ownerType, string memberName, string[]? parameterTypeNames, params object?[] args)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (ownerType is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return null;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return Invoke(ResolveMemberCached(ownerType, memberName, parameterTypeNames, S1InteropMemberKind.Method) as System.Reflection.MethodInfo, null, args);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static bool TryInvokeStatic(System.Type? ownerType, string memberName, out object? result, params object?[] args)");
        builder.AppendLine("        {");
        builder.AppendLine("            return TryInvokeStatic(ownerType, memberName, null, out result, args);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static bool TryInvokeStatic(System.Type? ownerType, string memberName, string[]? parameterTypeNames, out object? result, params object?[] args)");
        builder.AppendLine("        {");
        builder.AppendLine("            result = null;");
        builder.AppendLine("            if (ownerType is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return TryInvoke(ResolveMemberCached(ownerType, memberName, parameterTypeNames, S1InteropMemberKind.Method) as System.Reflection.MethodInfo, null, out result, args);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static object? Invoke(System.Reflection.MethodInfo? method, object? instance, params object?[] args)");
        builder.AppendLine("        {");
        builder.AppendLine("            return TryInvoke(method, instance, out object? result, args) ? result : null;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryInvoke(System.Reflection.MethodInfo? method, object? instance, out object? result, params object?[] args)");
        builder.AppendLine("        {");
        builder.AppendLine("            result = null;");
        builder.AppendLine("            if (method is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Reflection.ParameterInfo[] parameters = method.GetParameters();");
        builder.AppendLine("            string ownerTypeName = method.DeclaringType is null ? \"<unknown>\" : GetOwnerTypeName(method.DeclaringType);");
        builder.AppendLine("            string[] parameterTypeNames = GetParameterTypeNames(parameters);");
        builder.AppendLine("            if (!TryConvertArguments(parameters, args, out object?[] converted))");
        builder.AppendLine("            {");
        builder.AppendLine("                Record(S1InteropMemberResolutionStatus.ArgumentConversionFailed, ownerTypeName, method.Name, S1InteropMemberKind.Method, parameterTypeNames, \"Arguments could not be converted to the runtime method signature.\");");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                result = method.Invoke(instance, converted);");
        builder.AppendLine("                CopyByRefArguments(parameters, converted, args);");
        builder.AppendLine("                return true;");
        builder.AppendLine("            }");
        builder.AppendLine("            catch (System.Exception exception)");
        builder.AppendLine("            {");
        builder.AppendLine("                Record(S1InteropMemberResolutionStatus.InvocationFailed, ownerTypeName, method.Name, S1InteropMemberKind.Method, parameterTypeNames, \"Runtime method invocation failed.\", exception);");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryConvertArguments(System.Reflection.ParameterInfo[] parameters, object?[] args, out object?[] converted)");
        builder.AppendLine("        {");
        builder.AppendLine("            converted = System.Array.Empty<object?>();");
        builder.AppendLine("            if (parameters.Length != args.Length)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            converted = new object?[args.Length];");
        builder.AppendLine("            for (int index = 0; index < args.Length; index++)");
        builder.AppendLine("            {");
        builder.AppendLine("                System.Type parameterType = parameters[index].ParameterType;");
        builder.AppendLine("                System.Type conversionType = parameterType.IsByRef && parameterType.GetElementType() is System.Type elementType");
        builder.AppendLine("                    ? elementType");
        builder.AppendLine("                    : parameterType;");
        builder.AppendLine("                if (!TryConvertValue(args[index], conversionType, out object? convertedValue))");
        builder.AppendLine("                {");
        builder.AppendLine("                    return false;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                converted[index] = convertedValue;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return true;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static void CopyByRefArguments(System.Reflection.ParameterInfo[] parameters, object?[] converted, object?[] args)");
        builder.AppendLine("        {");
        builder.AppendLine("            int count = System.Math.Min(System.Math.Min(parameters.Length, converted.Length), args.Length);");
        builder.AppendLine("            for (int index = 0; index < count; index++)");
        builder.AppendLine("            {");
        builder.AppendLine("                if (parameters[index].ParameterType.IsByRef)");
        builder.AppendLine("                {");
        builder.AppendLine("                    args[index] = ConvertBackValue(args[index], converted[index]);");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static string[] GetParameterTypeNames(System.Reflection.ParameterInfo[] parameters)");
        builder.AppendLine("        {");
        builder.AppendLine("            var names = new string[parameters.Length];");
        builder.AppendLine("            for (int index = 0; index < parameters.Length; index++)");
        builder.AppendLine("            {");
        builder.AppendLine("                System.Type parameterType = parameters[index].ParameterType;");
        builder.AppendLine("                names[index] = parameterType.FullName ?? parameterType.Name;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return names;");
        builder.AppendLine("        }");
        builder.AppendLine();
    }
}
