using System.Text;

namespace S1Interop.Generators;

public sealed partial class S1InteropTypeRegistryGenerator
{
    private static void GenerateMemberValueAccessHelpers(StringBuilder builder)
    {
        builder.AppendLine("        public static object? GetValue(string ownerTypeName, string memberName, object? instance)");
        builder.AppendLine("        {");
        builder.AppendLine("            return GetValue(ownerTypeName, memberName, instance, S1InteropMemberKind.FieldOrProperty);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static T? CastResult<T>(object? value)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (value is T typed)");
        builder.AppendLine("            {");
        builder.AppendLine("                return typed;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (value is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return default;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Type targetType = System.Nullable.GetUnderlyingType(typeof(T)) ?? typeof(T);");
        builder.AppendLine("            if (targetType.IsEnum)");
        builder.AppendLine("            {");
        builder.AppendLine("                try");
        builder.AppendLine("                {");
        builder.AppendLine("                    return value is string text ? (T)System.Enum.Parse(targetType, text, ignoreCase: true) : (T)System.Enum.ToObject(targetType, value);");
        builder.AppendLine("                }");
        builder.AppendLine("                catch");
        builder.AppendLine("                {");
        builder.AppendLine("                    return default;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                return (T)System.Convert.ChangeType(value, targetType, System.Globalization.CultureInfo.InvariantCulture);");
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("                return default;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static object? GetInstanceValue(object? instance, string memberName)");
        builder.AppendLine("        {");
        builder.AppendLine("            return GetInstanceValue(instance, memberName, S1InteropMemberKind.FieldOrProperty);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static object? GetStaticValue(System.Type? ownerType, string memberName)");
        builder.AppendLine("        {");
        builder.AppendLine("            return GetStaticValue(ownerType, memberName, S1InteropMemberKind.FieldOrProperty);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static object? GetStaticValue(System.Type? ownerType, string memberName, S1InteropMemberKind kind)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (ownerType is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return null;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return GetResolvedValue(ResolveMemberCached(ownerType, memberName, parameterTypeNames: null, kind), null);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static object? GetInstanceValue(object? instance, string memberName, S1InteropMemberKind kind)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (instance is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return null;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            string ownerTypeName = GetOwnerTypeName(instance.GetType());");
        builder.AppendLine("            System.Reflection.MemberInfo? member = ResolveMemberCached(instance.GetType(), memberName, parameterTypeNames: null, kind);");
        builder.AppendLine("            return GetResolvedValue(member, instance);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static object? GetResolvedValue(System.Reflection.MemberInfo? member, object? instance)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (member is System.Reflection.PropertyInfo property)");
        builder.AppendLine("            {");
        builder.AppendLine("                try");
        builder.AppendLine("                {");
        builder.AppendLine("                    return property.GetValue(instance, null);");
        builder.AppendLine("                }");
        builder.AppendLine("                catch (System.Exception exception)");
        builder.AppendLine("                {");
        builder.AppendLine("                    string ownerTypeName = property.DeclaringType is null ? \"<unknown>\" : GetOwnerTypeName(property.DeclaringType);");
        builder.AppendLine("                    Record(S1InteropMemberResolutionStatus.ValueAccessFailed, ownerTypeName, property.Name, S1InteropMemberKind.Property, parameterTypeNames: null, \"Property getter failed for the active backend.\", exception);");
        builder.AppendLine("                    throw;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (member is System.Reflection.FieldInfo field)");
        builder.AppendLine("            {");
        builder.AppendLine("                try");
        builder.AppendLine("                {");
        builder.AppendLine("                    return field.GetValue(instance);");
        builder.AppendLine("                }");
        builder.AppendLine("                catch (System.Exception exception)");
        builder.AppendLine("                {");
        builder.AppendLine("                    string ownerTypeName = field.DeclaringType is null ? \"<unknown>\" : GetOwnerTypeName(field.DeclaringType);");
        builder.AppendLine("                    Record(S1InteropMemberResolutionStatus.ValueAccessFailed, ownerTypeName, field.Name, S1InteropMemberKind.Field, parameterTypeNames: null, \"Field getter failed for the active backend.\", exception);");
        builder.AppendLine("                    throw;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return null;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static object? GetValue(string ownerTypeName, string memberName, object? instance, S1InteropMemberKind kind)");
        builder.AppendLine("        {");
        builder.AppendLine("            System.Reflection.MemberInfo? member = ResolveMember(ownerTypeName, memberName, parameterTypeNames: null, kind);");
        builder.AppendLine("            if (member is System.Reflection.PropertyInfo property)");
        builder.AppendLine("            {");
        builder.AppendLine("                try");
        builder.AppendLine("                {");
        builder.AppendLine("                    return property.GetValue(instance, null);");
        builder.AppendLine("                }");
        builder.AppendLine("                catch (System.Exception exception)");
        builder.AppendLine("                {");
        builder.AppendLine("                    Record(S1InteropMemberResolutionStatus.ValueAccessFailed, ownerTypeName, memberName, kind, parameterTypeNames: null, \"Property getter failed for the active backend.\", exception);");
        builder.AppendLine("                    throw;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (member is System.Reflection.FieldInfo field)");
        builder.AppendLine("            {");
        builder.AppendLine("                try");
        builder.AppendLine("                {");
        builder.AppendLine("                    return field.GetValue(instance);");
        builder.AppendLine("                }");
        builder.AppendLine("                catch (System.Exception exception)");
        builder.AppendLine("                {");
        builder.AppendLine("                    Record(S1InteropMemberResolutionStatus.ValueAccessFailed, ownerTypeName, memberName, kind, parameterTypeNames: null, \"Field getter failed for the active backend.\", exception);");
        builder.AppendLine("                    throw;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return null;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static bool TrySetValue(string ownerTypeName, string memberName, object? instance, object? value)");
        builder.AppendLine("        {");
        builder.AppendLine("            return TrySetValue(ownerTypeName, memberName, instance, value, S1InteropMemberKind.FieldOrProperty);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static bool TrySetInstanceValue(object? instance, string memberName, object? value)");
        builder.AppendLine("        {");
        builder.AppendLine("            return TrySetInstanceValue(instance, memberName, value, S1InteropMemberKind.FieldOrProperty);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static bool TrySetStaticValue(System.Type? ownerType, string memberName, object? value)");
        builder.AppendLine("        {");
        builder.AppendLine("            return TrySetStaticValue(ownerType, memberName, value, S1InteropMemberKind.FieldOrProperty);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static bool TrySetStaticValue(System.Type? ownerType, string memberName, object? value, S1InteropMemberKind kind)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (ownerType is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return TrySetValue(ResolveMemberCached(ownerType, memberName, parameterTypeNames: null, kind), null, value);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static bool TrySetInstanceValue(object? instance, string memberName, object? value, S1InteropMemberKind kind)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (instance is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return TrySetValue(ResolveMemberCached(instance.GetType(), memberName, parameterTypeNames: null, kind), instance, value);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static bool TrySetValue(string ownerTypeName, string memberName, object? instance, object? value, S1InteropMemberKind kind)");
        builder.AppendLine("        {");
        builder.AppendLine("            System.Reflection.MemberInfo? member = ResolveMember(ownerTypeName, memberName, parameterTypeNames: null, kind);");
        builder.AppendLine("            return TrySetValue(member, instance, value);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TrySetValue(System.Reflection.MemberInfo? member, object? instance, object? value)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (member is System.Reflection.PropertyInfo property && property.CanWrite)");
        builder.AppendLine("            {");
        builder.AppendLine("                if (!TryConvertValue(value, property.PropertyType, out object? converted))");
        builder.AppendLine("                {");
        builder.AppendLine("                    string ownerTypeName = property.DeclaringType is null ? \"<unknown>\" : GetOwnerTypeName(property.DeclaringType);");
        builder.AppendLine("                    Record(S1InteropMemberResolutionStatus.ArgumentConversionFailed, ownerTypeName, property.Name, S1InteropMemberKind.Property, parameterTypeNames: null, \"Value could not be converted to the runtime property type.\");");
        builder.AppendLine("                    return false;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                try");
        builder.AppendLine("                {");
        builder.AppendLine("                    property.SetValue(instance, converted, null);");
        builder.AppendLine("                    return true;");
        builder.AppendLine("                }");
        builder.AppendLine("                catch (System.Exception exception)");
        builder.AppendLine("                {");
        builder.AppendLine("                    string ownerTypeName = property.DeclaringType is null ? \"<unknown>\" : GetOwnerTypeName(property.DeclaringType);");
        builder.AppendLine("                    Record(S1InteropMemberResolutionStatus.ValueSetFailed, ownerTypeName, property.Name, S1InteropMemberKind.Property, parameterTypeNames: null, \"Property setter failed for the active backend.\", exception);");
        builder.AppendLine("                    return false;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (member is System.Reflection.FieldInfo field)");
        builder.AppendLine("            {");
        builder.AppendLine("                if (!TryConvertValue(value, field.FieldType, out object? converted))");
        builder.AppendLine("                {");
        builder.AppendLine("                    string ownerTypeName = field.DeclaringType is null ? \"<unknown>\" : GetOwnerTypeName(field.DeclaringType);");
        builder.AppendLine("                    Record(S1InteropMemberResolutionStatus.ArgumentConversionFailed, ownerTypeName, field.Name, S1InteropMemberKind.Field, parameterTypeNames: null, \"Value could not be converted to the runtime field type.\");");
        builder.AppendLine("                    return false;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                try");
        builder.AppendLine("                {");
        builder.AppendLine("                    field.SetValue(instance, converted);");
        builder.AppendLine("                    return true;");
        builder.AppendLine("                }");
        builder.AppendLine("                catch (System.Exception exception)");
        builder.AppendLine("                {");
        builder.AppendLine("                    string ownerTypeName = field.DeclaringType is null ? \"<unknown>\" : GetOwnerTypeName(field.DeclaringType);");
        builder.AppendLine("                    Record(S1InteropMemberResolutionStatus.ValueSetFailed, ownerTypeName, field.Name, S1InteropMemberKind.Field, parameterTypeNames: null, \"Field setter failed for the active backend.\", exception);");
        builder.AppendLine("                    return false;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return false;");
        builder.AppendLine("        }");
        builder.AppendLine();
    }
}
