using System.Text;

namespace S1Interop.Generators;

public sealed partial class S1InteropTypeRegistryGenerator
{
    private static void GenerateMemberResolutionHelpers(StringBuilder builder)
    {
        builder.AppendLine("        public static System.Reflection.MethodInfo? ResolveMethod(string ownerTypeName, string memberName, string[]? parameterTypeNames)");
        builder.AppendLine("        {");
        builder.AppendLine("            return ResolveMember(ownerTypeName, memberName, parameterTypeNames, S1InteropMemberKind.Method) as System.Reflection.MethodInfo;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static System.Reflection.MemberInfo? ResolveMember(string ownerTypeName, string memberName, string[]? parameterTypeNames, S1InteropMemberKind kind)");
        builder.AppendLine("        {");
        builder.AppendLine("            string cacheKey = ownerTypeName + \"::\" + memberName + \"::\" + ((int)kind).ToString() + \"::\" + (parameterTypeNames is null ? string.Empty : string.Join(\"|\", parameterTypeNames));");
        builder.AppendLine("            if (!Cache.TryGetValue(cacheKey, out System.Reflection.MemberInfo? member))");
        builder.AppendLine("            {");
        builder.AppendLine("                System.Type? ownerType = S1InteropTypeRegistry.Resolve(ownerTypeName);");
        builder.AppendLine("                if (ownerType is null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    Record(S1InteropMemberResolutionStatus.MissingOwnerType, ownerTypeName, memberName, kind, parameterTypeNames, \"Owner type could not be resolved for the active backend.\");");
        builder.AppendLine("                    member = null;");
        builder.AppendLine("                }");
        builder.AppendLine("                else");
        builder.AppendLine("                {");
        builder.AppendLine("                    member = ResolveMember(ownerType, memberName, parameterTypeNames, kind);");
        builder.AppendLine("                }");
        builder.AppendLine("                Cache[cacheKey] = member;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return member;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static System.Reflection.MemberInfo? ResolveMemberCached(System.Type ownerType, string memberName, string[]? parameterTypeNames, S1InteropMemberKind kind)");
        builder.AppendLine("        {");
        builder.AppendLine("            string ownerKey = ownerType.AssemblyQualifiedName ?? ownerType.FullName ?? ownerType.Name;");
        builder.AppendLine("            string cacheKey = ownerKey + \"::\" + memberName + \"::\" + ((int)kind).ToString() + \"::\" + (parameterTypeNames is null ? string.Empty : string.Join(\"|\", parameterTypeNames));");
        builder.AppendLine("            if (!Cache.TryGetValue(cacheKey, out System.Reflection.MemberInfo? member))");
        builder.AppendLine("            {");
        builder.AppendLine("                member = ResolveMember(ownerType, memberName, parameterTypeNames, kind);");
        builder.AppendLine("                Cache[cacheKey] = member;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return member;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static System.Reflection.MemberInfo? ResolveMember(System.Type ownerType, string memberName, string[]? parameterTypeNames, S1InteropMemberKind kind)");
        builder.AppendLine("        {");
        builder.AppendLine("            string ownerTypeName = GetOwnerTypeName(ownerType);");
        builder.AppendLine();
        builder.AppendLine("            switch (kind)");
        builder.AppendLine("            {");
        builder.AppendLine("                case S1InteropMemberKind.Method:");
        builder.AppendLine("                    return ResolveMethod(ownerType, memberName, parameterTypeNames);");
        builder.AppendLine("                case S1InteropMemberKind.Field:");
        builder.AppendLine("                    return ResolveField(ownerType, ownerTypeName, memberName, kind);");
        builder.AppendLine("                case S1InteropMemberKind.Property:");
        builder.AppendLine("                    return ResolveProperty(ownerType, ownerTypeName, memberName, kind);");
        builder.AppendLine("                default:");
        builder.AppendLine("                    return ResolveProperty(ownerType, ownerTypeName, memberName, kind) ?? (System.Reflection.MemberInfo?)ResolveField(ownerType, ownerTypeName, memberName, kind);");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static System.Reflection.FieldInfo? ResolveField(System.Type ownerType, string ownerTypeName, string memberName, S1InteropMemberKind kind)");
        builder.AppendLine("        {");
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                System.Reflection.FieldInfo? field = ownerType.GetField(memberName, AllBindings);");
        builder.AppendLine("                if (field is null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    Record(S1InteropMemberResolutionStatus.MissingMember, ownerTypeName, memberName, kind, parameterTypeNames: null, \"Field could not be resolved for the active backend.\");");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                return field;");
        builder.AppendLine("            }");
        builder.AppendLine("            catch (System.Exception exception)");
        builder.AppendLine("            {");
        builder.AppendLine("                Record(S1InteropMemberResolutionStatus.ResolutionFailed, ownerTypeName, memberName, kind, parameterTypeNames: null, \"Field resolution failed for the active backend.\", exception);");
        builder.AppendLine("                return null;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static System.Reflection.PropertyInfo? ResolveProperty(System.Type ownerType, string ownerTypeName, string memberName, S1InteropMemberKind kind)");
        builder.AppendLine("        {");
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                System.Reflection.PropertyInfo? property = ownerType.GetProperty(memberName, AllBindings);");
        builder.AppendLine("                if (property is null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    Record(S1InteropMemberResolutionStatus.MissingMember, ownerTypeName, memberName, kind, parameterTypeNames: null, \"Property could not be resolved for the active backend.\");");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                return property;");
        builder.AppendLine("            }");
        builder.AppendLine("            catch (System.Reflection.AmbiguousMatchException exception)");
        builder.AppendLine("            {");
        builder.AppendLine("                Record(S1InteropMemberResolutionStatus.AmbiguousMember, ownerTypeName, memberName, kind, parameterTypeNames: null, \"Property name matched more than one member.\", exception);");
        builder.AppendLine("                return null;");
        builder.AppendLine("            }");
        builder.AppendLine("            catch (System.Exception exception)");
        builder.AppendLine("            {");
        builder.AppendLine("                Record(S1InteropMemberResolutionStatus.ResolutionFailed, ownerTypeName, memberName, kind, parameterTypeNames: null, \"Property resolution failed for the active backend.\", exception);");
        builder.AppendLine("                return null;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static System.Reflection.MethodInfo? ResolveMethod(System.Type ownerType, string memberName, string[]? parameterTypeNames)");
        builder.AppendLine("        {");
        builder.AppendLine("            string ownerTypeName = GetOwnerTypeName(ownerType);");
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                System.Reflection.MethodInfo? method;");
        builder.AppendLine("                if (parameterTypeNames is null || parameterTypeNames.Length == 0)");
        builder.AppendLine("                {");
        builder.AppendLine("                    method = ownerType.GetMethod(memberName, AllBindings);");
        builder.AppendLine("                }");
        builder.AppendLine("                else");
        builder.AppendLine("                {");
        builder.AppendLine("                    System.Type[]? parameterTypes = ResolveParameterTypes(ownerTypeName, memberName, parameterTypeNames);");
        builder.AppendLine("                    if (parameterTypes is null)");
        builder.AppendLine("                    {");
        builder.AppendLine("                        return null;");
        builder.AppendLine("                    }");
        builder.AppendLine();
        builder.AppendLine("                    method = ownerType.GetMethod(memberName, AllBindings, binder: null, types: parameterTypes, modifiers: null);");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                if (method is null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    Record(S1InteropMemberResolutionStatus.MissingMember, ownerTypeName, memberName, S1InteropMemberKind.Method, parameterTypeNames, \"Method could not be resolved for the active backend.\");");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                return method;");
        builder.AppendLine("            }");
        builder.AppendLine("            catch (System.Reflection.AmbiguousMatchException exception)");
        builder.AppendLine("            {");
        builder.AppendLine("                Record(S1InteropMemberResolutionStatus.AmbiguousMember, ownerTypeName, memberName, S1InteropMemberKind.Method, parameterTypeNames, \"Method name matched multiple overloads. Add ParameterTypeNames to the declaration or call.\", exception);");
        builder.AppendLine("                return null;");
        builder.AppendLine("            }");
        builder.AppendLine("            catch (System.Exception exception)");
        builder.AppendLine("            {");
        builder.AppendLine("                Record(S1InteropMemberResolutionStatus.ResolutionFailed, ownerTypeName, memberName, S1InteropMemberKind.Method, parameterTypeNames, \"Method resolution failed for the active backend.\", exception);");
        builder.AppendLine("                return null;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static System.Type[]? ResolveParameterTypes(string ownerTypeName, string memberName, string[] parameterTypeNames)");
        builder.AppendLine("        {");
        builder.AppendLine("            var parameterTypes = new System.Type[parameterTypeNames.Length];");
        builder.AppendLine("            for (int index = 0; index < parameterTypeNames.Length; index++)");
        builder.AppendLine("            {");
        builder.AppendLine("                string parameterTypeName = parameterTypeNames[index];");
        builder.AppendLine("                bool byRef = parameterTypeName.EndsWith(\"&\", System.StringComparison.Ordinal);");
        builder.AppendLine("                if (byRef)");
        builder.AppendLine("                {");
        builder.AppendLine("                    parameterTypeName = parameterTypeName.Substring(0, parameterTypeName.Length - 1);");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                System.Type? parameterType = ResolveKnownType(parameterTypeName);");
        builder.AppendLine("                if (parameterType is null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    Record(S1InteropMemberResolutionStatus.MissingParameterType, ownerTypeName, memberName, S1InteropMemberKind.Method, parameterTypeNames, \"Parameter type '\" + parameterTypeName + \"' could not be resolved for the active backend.\");");
        builder.AppendLine("                    return null;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                parameterTypes[index] = byRef ? parameterType.MakeByRefType() : parameterType;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return parameterTypes;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static System.Type? ResolveKnownType(string typeName)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (TryResolveArrayType(typeName, out System.Type? arrayType))");
        builder.AppendLine("            {");
        builder.AppendLine("                return arrayType;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (TryResolveGenericListType(typeName, out System.Type? genericListType))");
        builder.AppendLine("            {");
        builder.AppendLine("                return genericListType;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (TryResolveGenericHashSetType(typeName, out System.Type? genericHashSetType))");
        builder.AppendLine("            {");
        builder.AppendLine("                return genericHashSetType;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (TryResolveGenericDictionaryType(typeName, out System.Type? genericDictionaryType))");
        builder.AppendLine("            {");
        builder.AppendLine("                return genericDictionaryType;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            switch (typeName)");
        builder.AppendLine("            {");
        builder.AppendLine("                case \"System.Guid\": return typeof(System.Guid);");
        builder.AppendLine("                case \"bool\": return typeof(bool);");
        builder.AppendLine("                case \"byte\": return typeof(byte);");
        builder.AppendLine("                case \"char\": return typeof(char);");
        builder.AppendLine("                case \"double\": return typeof(double);");
        builder.AppendLine("                case \"float\": return typeof(float);");
        builder.AppendLine("                case \"int\": return typeof(int);");
        builder.AppendLine("                case \"long\": return typeof(long);");
        builder.AppendLine("                case \"object\": return typeof(object);");
        builder.AppendLine("                case \"short\": return typeof(short);");
        builder.AppendLine("                case \"string\": return typeof(string);");
        builder.AppendLine("                case \"uint\": return typeof(uint);");
        builder.AppendLine("                case \"ulong\": return typeof(ulong);");
        builder.AppendLine("                case \"void\": return typeof(void);");
        builder.AppendLine("                default: return S1InteropTypeRegistry.Resolve(typeName);");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryResolveArrayType(string typeName, out System.Type? resolvedType)");
        builder.AppendLine("        {");
        builder.AppendLine("            resolvedType = null;");
        builder.AppendLine("            const string structArrayPrefix = \"Il2CppInterop.Runtime.InteropTypes.Arrays.Il2CppStructArray<\";");
        builder.AppendLine("            const string referenceArrayPrefix = \"Il2CppInterop.Runtime.InteropTypes.Arrays.Il2CppReferenceArray<\";");
        builder.AppendLine("            if (typeName.EndsWith(\"[]\", System.StringComparison.Ordinal))");
        builder.AppendLine("            {");
        builder.AppendLine("                System.Type? elementType = ResolveKnownType(typeName.Substring(0, typeName.Length - 2));");
        builder.AppendLine("                if (elementType is null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return false;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                resolvedType = elementType.MakeArrayType();");
        builder.AppendLine("                return true;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            string genericDefinitionName;");
        builder.AppendLine("            string elementTypeName;");
        builder.AppendLine("            if (typeName.StartsWith(structArrayPrefix, System.StringComparison.Ordinal) && typeName.EndsWith(\">\", System.StringComparison.Ordinal))");
        builder.AppendLine("            {");
        builder.AppendLine("                genericDefinitionName = \"Il2CppInterop.Runtime.InteropTypes.Arrays.Il2CppStructArray`1\";");
        builder.AppendLine("                elementTypeName = typeName.Substring(structArrayPrefix.Length, typeName.Length - structArrayPrefix.Length - 1);");
        builder.AppendLine("            }");
        builder.AppendLine("            else if (typeName.StartsWith(referenceArrayPrefix, System.StringComparison.Ordinal) && typeName.EndsWith(\">\", System.StringComparison.Ordinal))");
        builder.AppendLine("            {");
        builder.AppendLine("                genericDefinitionName = \"Il2CppInterop.Runtime.InteropTypes.Arrays.Il2CppReferenceArray`1\";");
        builder.AppendLine("                elementTypeName = typeName.Substring(referenceArrayPrefix.Length, typeName.Length - referenceArrayPrefix.Length - 1);");
        builder.AppendLine("            }");
        builder.AppendLine("            else");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Type? genericDefinition = S1InteropTypeRegistry.Resolve(genericDefinitionName);");
        builder.AppendLine("            System.Type? genericElementType = ResolveKnownType(elementTypeName);");
        builder.AppendLine("            if (genericDefinition is null || genericElementType is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            resolvedType = genericDefinition.MakeGenericType(genericElementType);");
        builder.AppendLine("            return true;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryResolveGenericHashSetType(string typeName, out System.Type? resolvedType)");
        builder.AppendLine("        {");
        builder.AppendLine("            resolvedType = null;");
        builder.AppendLine("            const string monoPrefix = \"System.Collections.Generic.HashSet<\";");
        builder.AppendLine("            const string il2CppPrefix = \"Il2CppSystem.Collections.Generic.HashSet<\";");
        builder.AppendLine("            string genericDefinitionName;");
        builder.AppendLine("            string elementTypeName;");
        builder.AppendLine("            if (typeName.StartsWith(monoPrefix, System.StringComparison.Ordinal) && typeName.EndsWith(\">\", System.StringComparison.Ordinal))");
        builder.AppendLine("            {");
        builder.AppendLine("                genericDefinitionName = \"System.Collections.Generic.HashSet`1\";");
        builder.AppendLine("                elementTypeName = typeName.Substring(monoPrefix.Length, typeName.Length - monoPrefix.Length - 1);");
        builder.AppendLine("            }");
        builder.AppendLine("            else if (typeName.StartsWith(il2CppPrefix, System.StringComparison.Ordinal) && typeName.EndsWith(\">\", System.StringComparison.Ordinal))");
        builder.AppendLine("            {");
        builder.AppendLine("                genericDefinitionName = \"Il2CppSystem.Collections.Generic.HashSet`1\";");
        builder.AppendLine("                elementTypeName = typeName.Substring(il2CppPrefix.Length, typeName.Length - il2CppPrefix.Length - 1);");
        builder.AppendLine("            }");
        builder.AppendLine("            else");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Type? genericDefinition = S1InteropTypeRegistry.Resolve(genericDefinitionName);");
        builder.AppendLine("            System.Type? elementType = ResolveKnownType(elementTypeName);");
        builder.AppendLine("            if (genericDefinition is null || elementType is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            resolvedType = genericDefinition.MakeGenericType(elementType);");
        builder.AppendLine("            return true;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryResolveGenericDictionaryType(string typeName, out System.Type? resolvedType)");
        builder.AppendLine("        {");
        builder.AppendLine("            resolvedType = null;");
        builder.AppendLine("            const string monoPrefix = \"System.Collections.Generic.Dictionary<\";");
        builder.AppendLine("            const string il2CppPrefix = \"Il2CppSystem.Collections.Generic.Dictionary<\";");
        builder.AppendLine("            string genericDefinitionName;");
        builder.AppendLine("            string argumentsText;");
        builder.AppendLine("            if (typeName.StartsWith(monoPrefix, System.StringComparison.Ordinal) && typeName.EndsWith(\">\", System.StringComparison.Ordinal))");
        builder.AppendLine("            {");
        builder.AppendLine("                genericDefinitionName = \"System.Collections.Generic.Dictionary`2\";");
        builder.AppendLine("                argumentsText = typeName.Substring(monoPrefix.Length, typeName.Length - monoPrefix.Length - 1);");
        builder.AppendLine("            }");
        builder.AppendLine("            else if (typeName.StartsWith(il2CppPrefix, System.StringComparison.Ordinal) && typeName.EndsWith(\">\", System.StringComparison.Ordinal))");
        builder.AppendLine("            {");
        builder.AppendLine("                genericDefinitionName = \"Il2CppSystem.Collections.Generic.Dictionary`2\";");
        builder.AppendLine("                argumentsText = typeName.Substring(il2CppPrefix.Length, typeName.Length - il2CppPrefix.Length - 1);");
        builder.AppendLine("            }");
        builder.AppendLine("            else");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            string[] genericArguments = SplitGenericArguments(argumentsText);");
        builder.AppendLine("            if (genericArguments.Length != 2)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Type? genericDefinition = S1InteropTypeRegistry.Resolve(genericDefinitionName);");
        builder.AppendLine("            System.Type? keyType = ResolveKnownType(genericArguments[0]);");
        builder.AppendLine("            System.Type? valueType = ResolveKnownType(genericArguments[1]);");
        builder.AppendLine("            if (genericDefinition is null || keyType is null || valueType is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            resolvedType = genericDefinition.MakeGenericType(keyType, valueType);");
        builder.AppendLine("            return true;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static string[] SplitGenericArguments(string argumentsText)");
        builder.AppendLine("        {");
        builder.AppendLine("            System.Collections.Generic.List<string> arguments = new System.Collections.Generic.List<string>();");
        builder.AppendLine("            int depth = 0;");
        builder.AppendLine("            int start = 0;");
        builder.AppendLine("            for (int index = 0; index < argumentsText.Length; index++)");
        builder.AppendLine("            {");
        builder.AppendLine("                char character = argumentsText[index];");
        builder.AppendLine("                if (character == '<')");
        builder.AppendLine("                {");
        builder.AppendLine("                    depth++;");
        builder.AppendLine("                }");
        builder.AppendLine("                else if (character == '>')");
        builder.AppendLine("                {");
        builder.AppendLine("                    depth--;");
        builder.AppendLine("                }");
        builder.AppendLine("                else if (character == ',' && depth == 0)");
        builder.AppendLine("                {");
        builder.AppendLine("                    arguments.Add(argumentsText.Substring(start, index - start).Trim());");
        builder.AppendLine("                    start = index + 1;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            arguments.Add(argumentsText.Substring(start).Trim());");
        builder.AppendLine("            return arguments.ToArray();");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static bool TryResolveGenericListType(string typeName, out System.Type? resolvedType)");
        builder.AppendLine("        {");
        builder.AppendLine("            resolvedType = null;");
        builder.AppendLine("            const string monoPrefix = \"System.Collections.Generic.List<\";");
        builder.AppendLine("            const string il2CppPrefix = \"Il2CppSystem.Collections.Generic.List<\";");
        builder.AppendLine("            string genericDefinitionName;");
        builder.AppendLine("            string elementTypeName;");
        builder.AppendLine("            if (typeName.StartsWith(monoPrefix, System.StringComparison.Ordinal) && typeName.EndsWith(\">\", System.StringComparison.Ordinal))");
        builder.AppendLine("            {");
        builder.AppendLine("                genericDefinitionName = \"System.Collections.Generic.List`1\";");
        builder.AppendLine("                elementTypeName = typeName.Substring(monoPrefix.Length, typeName.Length - monoPrefix.Length - 1);");
        builder.AppendLine("            }");
        builder.AppendLine("            else if (typeName.StartsWith(il2CppPrefix, System.StringComparison.Ordinal) && typeName.EndsWith(\">\", System.StringComparison.Ordinal))");
        builder.AppendLine("            {");
        builder.AppendLine("                genericDefinitionName = \"Il2CppSystem.Collections.Generic.List`1\";");
        builder.AppendLine("                elementTypeName = typeName.Substring(il2CppPrefix.Length, typeName.Length - il2CppPrefix.Length - 1);");
        builder.AppendLine("            }");
        builder.AppendLine("            else");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            System.Type? genericDefinition = S1InteropTypeRegistry.Resolve(genericDefinitionName);");
        builder.AppendLine("            System.Type? elementType = ResolveKnownType(elementTypeName);");
        builder.AppendLine("            if (genericDefinition is null || elementType is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return false;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            resolvedType = genericDefinition.MakeGenericType(elementType);");
        builder.AppendLine("            return true;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static void Record(S1InteropMemberResolutionStatus status, string ownerTypeName, string memberName, S1InteropMemberKind kind, string[]? parameterTypeNames, string? message, System.Exception? exception = null)");
        builder.AppendLine("        {");
        builder.AppendLine("            MutableReports.Add(new S1InteropMemberResolutionReport(status, ownerTypeName, memberName, kind, FormatParameterTypeNames(parameterTypeNames), message, exception?.GetType().FullName));");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static string? FormatParameterTypeNames(string[]? parameterTypeNames)");
        builder.AppendLine("        {");
        builder.AppendLine("            return parameterTypeNames is null || parameterTypeNames.Length == 0");
        builder.AppendLine("                ? null");
        builder.AppendLine("                : string.Join(\"|\", parameterTypeNames);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static string GetOwnerTypeName(System.Type ownerType) => ownerType.FullName ?? ownerType.Name;");
        builder.AppendLine("    }");
    }
}
