global using System.Collections.Immutable;
global using System.Diagnostics;
global using System.Reflection;
global using System.Security.Cryptography;
global using System.Text;
global using System.Xml.Linq;
global using Microsoft.CodeAnalysis;
global using Microsoft.CodeAnalysis.CSharp;
global using S1Interop.Core.Analysis;
global using S1Interop.Core.CodeGeneration;
global using S1Interop.Core.Contracts;
global using S1Interop.Core.Migration;
global using S1Interop.Core.Packaging;
global using S1Interop.Core.Rewriting;
global using S1Interop.Generators;
global using CoreDiagnosticSeverity = S1Interop.Core.Contracts.DiagnosticSeverity;
global using RoslynDiagnosticSeverity = Microsoft.CodeAnalysis.DiagnosticSeverity;
