using System.Text;

namespace S1Interop.Core.CodeGeneration;

/// <summary>
/// Generates S1Interop type and member declarations for discovered field and property accesses.
/// </summary>
public sealed class MemberAccessTargetGenerator
{
    /// <summary>
    /// Gets the generated member access declaration file name.
    /// </summary>
    public const string SourceFileName = "S1Interop.MemberAccessTargets.g.cs";

    /// <summary>
    /// Gets the generated member access declaration path for a project.
    /// </summary>
    /// <param name="projectPath">The path to the owning <c>.csproj</c> file.</param>
    /// <returns>The path under the project's <c>S1Interop.Generated</c> directory.</returns>
    public static string GetSourcePath(string projectPath)
    {
        string projectDirectory = Path.GetDirectoryName(projectPath)!;
        return Path.Combine(projectDirectory, "S1Interop.Generated", SourceFileName);
    }

    /// <summary>
    /// Generates type and member declarations for the supplied access targets.
    /// </summary>
    /// <param name="targets">The discovered field and property access targets to declare.</param>
    /// <returns>The complete generated C# source.</returns>
    public string GenerateSource(IReadOnlyList<MemberAccessTarget> targets)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("// Generated by S1Interop. Do not edit by hand.");
        builder.AppendLine();

        foreach (MemberAccessTarget target in targets
                     .DistinctBy(target => (target.OwnerAlias, target.OwnerTypeName))
                     .OrderBy(target => target.OwnerAlias, StringComparer.Ordinal))
        {
            builder.AppendLine($"[assembly: S1Interop.S1InteropType(\"{Escape(target.OwnerTypeName)}\", Alias = \"{Escape(target.OwnerAlias)}\")]");
        }

        foreach (MemberAccessTarget target in targets.OrderBy(target => target.MemberAlias, StringComparer.Ordinal))
        {
            builder.Append("[assembly: S1Interop.S1InteropMember(");
            builder.Append($"\"{Escape(target.OwnerAlias)}\", ");
            builder.Append($"\"{Escape(target.MemberName)}\", ");
            builder.Append($"Alias = \"{Escape(target.MemberAlias)}\"");
            if (target.Kind == MemberAccessKind.Property)
            {
                builder.Append(", Kind = S1Interop.S1InteropMemberKind.Property");
            }

            if (target.IsStatic)
            {
                builder.Append(", IsStatic = true");
            }

            builder.AppendLine(")]");
        }

        builder.AppendLine();
        builder.AppendLine("namespace S1Interop.Generated");
        builder.AppendLine("{");
        builder.AppendLine("    internal static class S1InteropMemberAccessTargets");
        builder.AppendLine("    {");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string Escape(string value) =>
        value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal);
}
