using System.Text;

namespace S1Interop.Core.CodeGeneration;

public sealed partial class SdkFacadeGenerator
{
    /// <summary>
    /// Generates assembly-level declarations for an SDK facade plan.
    /// </summary>
    /// <param name="plan">The planned namespaces and type aliases to emit.</param>
    /// <returns>The complete generated C# source.</returns>
    public string GenerateSource(SdkFacadePlan plan)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("// Generated by S1Interop. Do not edit by hand.");
        builder.AppendLine();
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        AppendNamespaceUsings(builder, plan);
        AppendTypeAliasUsings(builder, plan);
        AppendTypeDeclarations(builder, plan);

        return builder.ToString();
    }

    private static void AppendNamespaceUsings(StringBuilder builder, SdkFacadePlan plan)
    {
        foreach (string ns in plan.ScheduleOneNamespaces.OrderBy(value => value, StringComparer.OrdinalIgnoreCase))
        {
            string il2CppNamespace = $"Il2Cpp{ns}";
            builder.AppendLine("#if MONO");
            builder.AppendLine($"global using {ns};");
            builder.AppendLine("#elif IL2CPP");
            builder.AppendLine($"global using {il2CppNamespace};");
            builder.AppendLine("#endif");
            builder.AppendLine();
        }
    }

    private static void AppendTypeAliasUsings(StringBuilder builder, SdkFacadePlan plan)
    {
        foreach (SdkTypeAlias alias in plan.TypeAliases
                     .Where(alias => alias.GenerateGlobalUsing)
                     .OrderBy(value => value.Alias, StringComparer.OrdinalIgnoreCase))
        {
            builder.AppendLine("#if MONO");
            builder.AppendLine($"global using {alias.Alias} = {alias.MonoType};");
            builder.AppendLine("#elif IL2CPP");
            builder.AppendLine($"global using {alias.Alias} = {alias.Il2CppType};");
            builder.AppendLine("#endif");
            builder.AppendLine();
        }
    }

    private static void AppendTypeDeclarations(StringBuilder builder, SdkFacadePlan plan)
    {
        foreach (SdkNamespaceImport import in plan.NamespaceImports.OrderBy(value => value.Namespace, StringComparer.OrdinalIgnoreCase))
        {
            builder.Append($"[assembly: S1Interop.S1InteropNamespace(\"{Escape(import.Namespace)}\", IncludeSubnamespaces = {import.IncludeSubnamespaces.ToString().ToLowerInvariant()}");
            if (import.IncludeMembers)
            {
                builder.Append(", IncludeMembers = true");
            }

            builder.AppendLine(")]");
        }

        if (plan.NamespaceImports.Count > 0)
        {
            builder.AppendLine();
        }

        foreach (SdkTypeAlias alias in plan.TypeAliases.OrderBy(value => value.Alias, StringComparer.OrdinalIgnoreCase))
        {
            builder.AppendLine($"[assembly: S1Interop.S1InteropType(\"{Escape(alias.MonoType)}\", Alias = \"{Escape(alias.Alias)}\", Il2CppTypeName = \"{Escape(alias.Il2CppType)}\")]");
        }

        if (plan.TypeAliases.Count > 0)
        {
            builder.AppendLine();
        }
    }
}
