using System.Text;

namespace S1Interop.Core.CodeGeneration;

/// <summary>
/// Renders migration operations that require manual source review as a Markdown report.
/// </summary>
public sealed class SourceRiskReportGenerator
{
    /// <summary>
    /// Gets the generated source-risk report file name.
    /// </summary>
    public const string ReportFileName = "S1Interop.SourceRisks.md";

    /// <summary>
    /// Gets the source-risk report path for a project.
    /// </summary>
    /// <param name="projectPath">The path to the owning <c>.csproj</c> file.</param>
    /// <returns>The report path under the project's <c>S1Interop.Generated</c> directory.</returns>
    public static string GetReportPath(string projectPath)
    {
        string projectDirectory = Path.GetDirectoryName(projectPath)!;
        return Path.Combine(projectDirectory, "S1Interop.Generated", ReportFileName);
    }

    /// <summary>
    /// Checks whether a project migration plan contains source-risk operations.
    /// </summary>
    /// <param name="projectPlan">The project plan to inspect.</param>
    /// <returns>True when at least one operation has a <c>source_risk_</c> rule ID; otherwise, false.</returns>
    public static bool HasSourceRiskOperations(ProjectMigrationPlan projectPlan) =>
        projectPlan.Operations.Any(IsSourceRiskOperation);

    /// <summary>
    /// Generates a Markdown report for source risks in a project migration plan.
    /// </summary>
    /// <param name="projectPlan">The project plan whose source-risk operations should be reported.</param>
    /// <returns>A complete Markdown report ordered by risk and source location.</returns>
    public string GenerateReport(ProjectMigrationPlan projectPlan)
    {
        string projectDirectory = Path.GetDirectoryName(projectPlan.ProjectPath)!;
        MigrationOperation[] risks = projectPlan.Operations
            .Where(IsSourceRiskOperation)
            .OrderByDescending(operation => GetRiskRank(operation.Risk))
            .ThenBy(operation => GetRiskTitle(operation.RuleId), StringComparer.OrdinalIgnoreCase)
            .ThenBy(operation => GetDisplayPath(projectDirectory, operation.FilePath), StringComparer.OrdinalIgnoreCase)
            .ThenBy(operation => operation.Evidence, StringComparer.OrdinalIgnoreCase)
            .ToArray();

        var builder = new StringBuilder();
        builder.AppendLine("# S1Interop Source Risk Report");
        builder.AppendLine();
        builder.AppendLine("Generated by S1Interop. Do not edit by hand.");
        builder.AppendLine();
        builder.AppendLine("This report lists source patterns that S1Interop found while preparing the mod for IL2CPP or dual-runtime builds. They are not automatically rewritten yet because the safe migration depends on the exact game wrapper, delegate surface, patch shape, and helper APIs available to the mod.");
        builder.AppendLine();
        builder.AppendLine($"Project: `{GetDisplayPath(projectDirectory, projectPlan.ProjectPath)}`");
        builder.AppendLine();
        builder.AppendLine("## Summary");
        builder.AppendLine();

        foreach (IGrouping<string, MigrationOperation> group in risks.GroupBy(operation => GetRiskTitle(operation.RuleId)))
        {
            int high = group.Count(operation => operation.Risk.Equals("high", StringComparison.OrdinalIgnoreCase));
            int medium = group.Count(operation => operation.Risk.Equals("medium", StringComparison.OrdinalIgnoreCase));
            int low = group.Count(operation => operation.Risk.Equals("low", StringComparison.OrdinalIgnoreCase));
            builder.Append("- ");
            builder.Append(group.Key);
            builder.Append(": ");
            builder.Append(group.Count());
            builder.Append(" finding");
            if (group.Count() != 1)
            {
                builder.Append('s');
            }

            string severityText = FormatSeverityCounts(high, medium, low);
            if (severityText.Length > 0)
            {
                builder.Append(" (");
                builder.Append(severityText);
                builder.Append(')');
            }

            builder.AppendLine();
        }

        builder.AppendLine();
        builder.AppendLine("## Findings");
        builder.AppendLine();

        foreach (IGrouping<string, MigrationOperation> group in risks.GroupBy(operation => GetRiskTitle(operation.RuleId)))
        {
            builder.AppendLine($"### {group.Key}");
            builder.AppendLine();

            foreach (MigrationOperation operation in group)
            {
                builder.AppendLine($"- `{GetDisplayPath(projectDirectory, operation.FilePath)}` risk={operation.Risk}");
                if (!string.IsNullOrWhiteSpace(operation.Evidence))
                {
                    builder.AppendLine($"  - Evidence: `{EscapeInlineCode(operation.Evidence)}`");
                }

                builder.AppendLine($"  - Migration note: {operation.Description}");
            }

            builder.AppendLine();
        }

        return builder.ToString();
    }

    private static bool IsSourceRiskOperation(MigrationOperation operation) =>
        operation.RuleId.StartsWith("source_risk_", StringComparison.OrdinalIgnoreCase);

    private static int GetRiskRank(string risk) =>
        risk.ToLowerInvariant() switch
        {
            "high" => 3,
            "medium" => 2,
            "low" => 1,
            _ => 0
        };

    private static string GetRiskTitle(string ruleId)
    {
        string value = ruleId.StartsWith("source_risk_", StringComparison.OrdinalIgnoreCase)
            ? ruleId["source_risk_".Length..]
            : ruleId;

        string[] parts = value.Split('_', StringSplitOptions.RemoveEmptyEntries);
        return string.Join(" ", parts.Select(ToTitleCaseWord));
    }

    private static string ToTitleCaseWord(string value)
    {
        if (value.Equals("il2cpp", StringComparison.OrdinalIgnoreCase))
        {
            return "IL2CPP";
        }

        return value.Length == 0
            ? value
            : string.Concat(char.ToUpperInvariant(value[0]), value[1..].ToLowerInvariant());
    }

    private static string FormatSeverityCounts(int high, int medium, int low)
    {
        var parts = new List<string>();
        if (high > 0)
        {
            parts.Add($"{high} high");
        }

        if (medium > 0)
        {
            parts.Add($"{medium} medium");
        }

        if (low > 0)
        {
            parts.Add($"{low} low");
        }

        return string.Join(", ", parts);
    }

    private static string GetDisplayPath(string projectDirectory, string path)
    {
        string relativePath = Path.GetRelativePath(projectDirectory, path);
        return relativePath.StartsWith("..", StringComparison.Ordinal)
            ? path
            : relativePath;
    }

    private static string EscapeInlineCode(string value) =>
        value.Replace("`", "\\`", StringComparison.Ordinal);
}
