using System.Text;

namespace S1Interop.Core.CodeGeneration;

/// <summary>
/// Generates UnityEvent listener helpers that preserve removable delegate wrappers across Mono and IL2CPP.
/// </summary>
public sealed class UnityEventBridgeGenerator
{
    /// <summary>
    /// Gets the generated UnityEvent bridge file name.
    /// </summary>
    public const string SourceFileName = "S1Interop.UnityEventBridge.g.cs";

    /// <summary>
    /// Gets the generated UnityEvent bridge path for a project.
    /// </summary>
    /// <param name="projectPath">The path to the owning <c>.csproj</c> file.</param>
    /// <returns>The path under the project's <c>S1Interop.Generated</c> directory.</returns>
    public static string GetSourcePath(string projectPath)
    {
        string projectDirectory = Path.GetDirectoryName(projectPath)!;
        return Path.Combine(projectDirectory, "S1Interop.Generated", SourceFileName);
    }

    /// <summary>
    /// Generates the backend-neutral UnityEvent add and remove helper source.
    /// </summary>
    /// <returns>The complete generated C# source.</returns>
    public string GenerateSource()
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("// Generated by S1Interop. Do not edit by hand.");
        builder.AppendLine();
        builder.AppendLine("namespace S1Interop.Generated");
        builder.AppendLine("{");
        builder.AppendLine();
        builder.AppendLine("internal static class S1InteropUnityEventBridge");
        builder.AppendLine("{");
        builder.AppendLine("    private static readonly System.Collections.Generic.Dictionary<object, System.Collections.Generic.Dictionary<System.Delegate, System.Delegate>> WrappedListeners =");
        builder.AppendLine("        new System.Collections.Generic.Dictionary<object, System.Collections.Generic.Dictionary<System.Delegate, System.Delegate>>();");
        builder.AppendLine();
        builder.AppendLine("    public static void Add(UnityEngine.Events.UnityEvent unityEvent, System.Action listener)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (object.ReferenceEquals(unityEvent, null) || object.ReferenceEquals(listener, null) || HasWrapper(unityEvent, listener))");
        builder.AppendLine("        {");
        builder.AppendLine("            return;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("#if IL2CPP");
        builder.AppendLine("        System.Action wrapped = new System.Action(listener);");
        builder.AppendLine("        unityEvent.AddListener(wrapped);");
        builder.AppendLine("#else");
        builder.AppendLine("        UnityEngine.Events.UnityAction wrapped = new UnityEngine.Events.UnityAction(listener);");
        builder.AppendLine("        unityEvent.AddListener(wrapped);");
        builder.AppendLine("#endif");
        builder.AppendLine("        StoreWrapper(unityEvent, listener, wrapped);");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public static void Remove(UnityEngine.Events.UnityEvent unityEvent, System.Action listener)");
        builder.AppendLine("    {");
        builder.AppendLine("        System.Delegate wrapped;");
        builder.AppendLine("        if (object.ReferenceEquals(unityEvent, null) || object.ReferenceEquals(listener, null) || !TryRemoveWrapper(unityEvent, listener, out wrapped))");
        builder.AppendLine("        {");
        builder.AppendLine("            return;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("#if IL2CPP");
        builder.AppendLine("        if (wrapped is System.Action action)");
        builder.AppendLine("        {");
        builder.AppendLine("            unityEvent.RemoveListener(action);");
        builder.AppendLine("        }");
        builder.AppendLine("#else");
        builder.AppendLine("        if (wrapped is UnityEngine.Events.UnityAction action)");
        builder.AppendLine("        {");
        builder.AppendLine("            unityEvent.RemoveListener(action);");
        builder.AppendLine("        }");
        builder.AppendLine("#endif");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public static void Add<T0>(UnityEngine.Events.UnityEvent<T0> unityEvent, System.Action<T0> listener)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (object.ReferenceEquals(unityEvent, null) || object.ReferenceEquals(listener, null) || HasWrapper(unityEvent, listener))");
        builder.AppendLine("        {");
        builder.AppendLine("            return;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("#if IL2CPP");
        builder.AppendLine("        System.Action<T0> wrapped = new System.Action<T0>(listener);");
        builder.AppendLine("        unityEvent.AddListener(wrapped);");
        builder.AppendLine("#else");
        builder.AppendLine("        UnityEngine.Events.UnityAction<T0> wrapped = new UnityEngine.Events.UnityAction<T0>(listener);");
        builder.AppendLine("        unityEvent.AddListener(wrapped);");
        builder.AppendLine("#endif");
        builder.AppendLine("        StoreWrapper(unityEvent, listener, wrapped);");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public static void Remove<T0>(UnityEngine.Events.UnityEvent<T0> unityEvent, System.Action<T0> listener)");
        builder.AppendLine("    {");
        builder.AppendLine("        System.Delegate wrapped;");
        builder.AppendLine("        if (object.ReferenceEquals(unityEvent, null) || object.ReferenceEquals(listener, null) || !TryRemoveWrapper(unityEvent, listener, out wrapped))");
        builder.AppendLine("        {");
        builder.AppendLine("            return;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("#if IL2CPP");
        builder.AppendLine("        if (wrapped is System.Action<T0> action)");
        builder.AppendLine("        {");
        builder.AppendLine("            unityEvent.RemoveListener(action);");
        builder.AppendLine("        }");
        builder.AppendLine("#else");
        builder.AppendLine("        if (wrapped is UnityEngine.Events.UnityAction<T0> action)");
        builder.AppendLine("        {");
        builder.AppendLine("            unityEvent.RemoveListener(action);");
        builder.AppendLine("        }");
        builder.AppendLine("#endif");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    private static bool HasWrapper(object unityEvent, System.Delegate listener) =>");
        builder.AppendLine("        WrappedListeners.TryGetValue(unityEvent, out System.Collections.Generic.Dictionary<System.Delegate, System.Delegate> listeners) &&");
        builder.AppendLine("        listeners.ContainsKey(listener);");
        builder.AppendLine();
        builder.AppendLine("    private static void StoreWrapper(object unityEvent, System.Delegate listener, System.Delegate wrapped)");
        builder.AppendLine("    {");
        builder.AppendLine("        System.Collections.Generic.Dictionary<System.Delegate, System.Delegate> listeners;");
        builder.AppendLine("        if (!WrappedListeners.TryGetValue(unityEvent, out listeners))");
        builder.AppendLine("        {");
        builder.AppendLine("            listeners = new System.Collections.Generic.Dictionary<System.Delegate, System.Delegate>();");
        builder.AppendLine("            WrappedListeners[unityEvent] = listeners;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        listeners[listener] = wrapped;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    private static bool TryRemoveWrapper(object unityEvent, System.Delegate listener, out System.Delegate wrapped)");
        builder.AppendLine("    {");
        builder.AppendLine("        wrapped = null;");
        builder.AppendLine("        System.Collections.Generic.Dictionary<System.Delegate, System.Delegate> listeners;");
        builder.AppendLine("        if (!WrappedListeners.TryGetValue(unityEvent, out listeners) ||");
        builder.AppendLine("            !listeners.TryGetValue(listener, out wrapped))");
        builder.AppendLine("        {");
        builder.AppendLine("            return false;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        listeners.Remove(listener);");
        builder.AppendLine("        if (listeners.Count == 0)");
        builder.AppendLine("        {");
        builder.AppendLine("            WrappedListeners.Remove(unityEvent);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        return true;");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        builder.AppendLine("}");

        return builder.ToString();
    }
}
