<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="local.build.props" Condition="Exists('local.build.props')" />
  <Import Project="../../build/S1Interop.Compiler.props" />
  <PropertyGroup>
    <AssemblyName>S1Interop.Compiler.RuntimeSmoke</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../S1Interop.Compiler.RuntimeLibrary/S1Interop.Compiler.RuntimeLibrary.csproj" />
  </ItemGroup>
  <Import Project="../../build/S1Interop.Compiler.targets" />
</Project>
