using System.Text;

namespace S1Interop.Core;

public sealed class HarmonyMethodTargetGenerator
{
    public const string SourceFileName = "S1Interop.HarmonyMethodTargets.g.cs";

    public static string GetSourcePath(string projectPath)
    {
        string projectDirectory = Path.GetDirectoryName(projectPath)!;
        return Path.Combine(projectDirectory, "S1Interop.Generated", SourceFileName);
    }

    public string GenerateSource(IReadOnlyList<HarmonyMethodTarget> targets)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("// Generated by S1Interop. Do not edit by hand.");
        builder.AppendLine();

        foreach (HarmonyMethodTarget target in targets
                     .DistinctBy(target => (target.OwnerAlias, target.OwnerTypeName))
                     .OrderBy(target => target.OwnerAlias, StringComparer.Ordinal))
        {
            builder.AppendLine($"[assembly: S1Interop.S1InteropType(\"{Escape(target.OwnerTypeName)}\", Alias = \"{Escape(target.OwnerAlias)}\")]");
        }

        foreach (string parameterTypeName in targets
                     .SelectMany(target => target.ParameterTypeNames)
                     .Select(parameter => parameter.EndsWith("&", StringComparison.Ordinal) ? parameter[..^1] : parameter)
                     .Where(parameter => !IsPrimitiveTypeName(parameter))
                     .Distinct(StringComparer.Ordinal)
                     .OrderBy(parameter => parameter, StringComparer.Ordinal))
        {
            builder.AppendLine($"[assembly: S1Interop.S1InteropType(\"{Escape(parameterTypeName)}\", Alias = \"{Escape(parameterTypeName)}\")]");
        }

        foreach (HarmonyMethodTarget target in targets.OrderBy(target => target.MethodAlias, StringComparer.Ordinal))
        {
            builder.Append("[assembly: S1Interop.S1InteropMember(");
            builder.Append($"\"{Escape(target.OwnerAlias)}\", ");
            builder.Append($"\"{Escape(target.MethodName)}\", ");
            builder.Append($"Alias = \"{Escape(target.MethodAlias)}\", ");
            builder.Append("Kind = S1Interop.S1InteropMemberKind.Method");
            if (target.ParameterTypeNames.Count > 0)
            {
                builder.Append(", ParameterTypeNames = new[] { ");
                builder.Append(string.Join(", ", target.ParameterTypeNames.Select(parameter => $"\"{Escape(parameter)}\"")));
                builder.Append(" }");
            }

            builder.AppendLine(")]");
        }

        builder.AppendLine();
        builder.AppendLine("namespace S1Interop.Generated");
        builder.AppendLine("{");
        builder.AppendLine("    internal static class S1InteropHarmonyMethodTargets");
        builder.AppendLine("    {");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static bool IsPrimitiveTypeName(string parameter) =>
        parameter is "bool" or "byte" or "char" or "double" or "float" or "int" or "long" or "object" or "short" or "string" or "uint" or "ulong" or "void";

    private static string Escape(string value) =>
        value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal);
}
