using System.Text;

namespace S1Interop.Core.Generators;

public sealed class DelegateEventBridgeGenerator
{
    public const string SourceFileName = "S1Interop.DelegateEventBridge.g.cs";

    public static string GetSourcePath(string projectPath)
    {
        string projectDirectory = Path.GetDirectoryName(projectPath)!;
        return Path.Combine(projectDirectory, "S1Interop.Generated", SourceFileName);
    }

    public string GenerateSource()
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("// Generated by S1Interop. Do not edit by hand.");
        builder.AppendLine();
        builder.AppendLine("namespace S1Interop.Generated");
        builder.AppendLine("{");
        builder.AppendLine();
        builder.AppendLine("internal static class S1InteropDelegateEventBridge");
        builder.AppendLine("{");
        builder.AppendLine("    public static TDelegate Combine<TDelegate>(TDelegate current, System.Delegate listener) where TDelegate : class");
        builder.AppendLine("    {");
        builder.AppendLine("        return (TDelegate)(object)System.Delegate.Combine(current as System.Delegate, listener);");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public static TDelegate Remove<TDelegate>(TDelegate current, System.Delegate listener) where TDelegate : class");
        builder.AppendLine("    {");
        builder.AppendLine("        return (TDelegate)(object)System.Delegate.Remove(current as System.Delegate, listener);");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        builder.AppendLine("}");

        return builder.ToString();
    }
}
