using System.Text;

namespace S1Interop.Core.Generators;

public static class PlayerCameraCompatGenerator
{
    public static string GetSourcePath(string projectPath) =>
        Path.Combine(Path.GetDirectoryName(projectPath)!, "S1Interop.Generated", "S1PlayerCameraCompat.g.cs");

    public static string GenerateSource()
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("// Generated by S1Interop. Do not edit by hand.");
        builder.AppendLine();
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("namespace S1Interop.Generated");
        builder.AppendLine("{");
        builder.AppendLine("    internal static class S1PlayerCameraCompat");
        builder.AppendLine("    {");
        builder.AppendLine("#if MONO");
        builder.AppendLine("        public static void CloseInterface(ScheduleOne.PlayerScripts.PlayerCamera camera, float cameraLerpTime = 0.2f, bool reenableCameraInput = true)");
        builder.AppendLine("        {");
        builder.AppendLine("            camera.CloseInterface(cameraLerpTime, reenableCameraInput);");
        builder.AppendLine("        }");
        builder.AppendLine("#elif IL2CPP");
        builder.AppendLine("        public static void CloseInterface(Il2CppScheduleOne.PlayerScripts.PlayerCamera camera, float cameraLerpTime = 0.2f, bool reenableCameraInput = true)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (reenableCameraInput)");
        builder.AppendLine("            {");
        builder.AppendLine("                camera.SetCanLook(true);");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            camera.SetDoFActive(false, cameraLerpTime);");
        builder.AppendLine("        }");
        builder.AppendLine("#endif");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }
}
