using System.Text;
using System.Text.RegularExpressions;

using S1Interop.Core;

namespace S1Interop.Core.Generators;

public sealed class SdkFacadeGenerator
{
    private static readonly Regex ScheduleOneUsingRegex = new(
        @"^\s*using\s+(?<namespace>(?:Il2Cpp)?ScheduleOne(?:\.[A-Za-z_][A-Za-z0-9_]*)*)\s*;",
        RegexOptions.Compiled | RegexOptions.Multiline);

    private static readonly Regex FullyQualifiedScheduleOneTypeRegex = new(
        @"(?<![A-Za-z0-9_])(?<type>(?:Il2Cpp)?ScheduleOne(?:\.[A-Za-z_][A-Za-z0-9_]*){2,})",
        RegexOptions.Compiled);

    private static readonly Regex ScheduleOneUsingAliasRegex = new(
        @"^\s*using\s+(?<alias>[A-Za-z_][A-Za-z0-9_]*)\s*=\s*(?<type>(?:Il2Cpp)?ScheduleOne(?:\.[A-Za-z_][A-Za-z0-9_]*){1,})\s*;",
        RegexOptions.Compiled | RegexOptions.Multiline);

    public SdkFacadePlan Plan(ProjectAnalysis project)
    {
        string projectDirectory = Path.GetDirectoryName(project.ProjectPath)!;
        string outputPath = Path.Combine(projectDirectory, "S1Interop.Generated", "S1Interop.GlobalUsings.g.cs");
        IReadOnlyList<string> namespaces = DiscoverScheduleOneNamespaces(projectDirectory);
        IReadOnlyList<SdkTypeAlias> aliases = DiscoverTypeAliases(projectDirectory);
        return new SdkFacadePlan(project.ProjectPath, outputPath, namespaces, aliases, namespaces.Count > 0 || aliases.Count > 0);
    }

    public string GenerateSource(SdkFacadePlan plan)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("// Generated by S1Interop. Do not edit by hand.");
        builder.AppendLine();
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        foreach (string ns in plan.ScheduleOneNamespaces.OrderBy(value => value, StringComparer.OrdinalIgnoreCase))
        {
            string il2CppNamespace = $"Il2Cpp{ns}";
            builder.AppendLine("#if MONO");
            builder.AppendLine($"global using {ns};");
            builder.AppendLine("#elif IL2CPP");
            builder.AppendLine($"global using {il2CppNamespace};");
            builder.AppendLine("#endif");
            builder.AppendLine();
        }

        foreach (SdkTypeAlias alias in plan.TypeAliases
                     .Where(alias => alias.GenerateGlobalUsing)
                     .OrderBy(value => value.Alias, StringComparer.OrdinalIgnoreCase))
        {
            builder.AppendLine("#if MONO");
            builder.AppendLine($"global using {alias.Alias} = {alias.MonoType};");
            builder.AppendLine("#elif IL2CPP");
            builder.AppendLine($"global using {alias.Alias} = {alias.Il2CppType};");
            builder.AppendLine("#endif");
            builder.AppendLine();
        }

        foreach (SdkTypeAlias alias in plan.TypeAliases.OrderBy(value => value.Alias, StringComparer.OrdinalIgnoreCase))
        {
            builder.AppendLine($"[assembly: S1Interop.S1InteropType(\"{Escape(alias.MonoType)}\", Alias = \"{Escape(alias.Alias)}\", Il2CppTypeName = \"{Escape(alias.Il2CppType)}\")]");
        }

        if (plan.TypeAliases.Count > 0)
        {
            builder.AppendLine();
        }

        return builder.ToString();
    }

    private static IReadOnlyList<string> DiscoverScheduleOneNamespaces(string projectDirectory)
    {
        if (!Directory.Exists(projectDirectory))
        {
            return Array.Empty<string>();
        }

        var namespaces = new SortedSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (string file in WorkspaceTraversal.EnumerateFiles(projectDirectory, "*.cs"))
        {
            if (IsGeneratedOrBuildOutput(projectDirectory, file))
            {
                continue;
            }

            string source = File.ReadAllText(file);
            foreach (Match match in ScheduleOneUsingRegex.Matches(source))
            {
                string ns = match.Groups["namespace"].Value;
                if (ns.StartsWith("Il2Cpp", StringComparison.Ordinal))
                {
                    ns = ns["Il2Cpp".Length..];
                }

                namespaces.Add(ns);
            }
        }

        return namespaces.ToArray();
    }

    private static IReadOnlyList<SdkTypeAlias> DiscoverTypeAliases(string projectDirectory)
    {
        if (!Directory.Exists(projectDirectory))
        {
            return Array.Empty<SdkTypeAlias>();
        }

        var monoTypesByAlias = new Dictionary<string, SortedSet<string>>(StringComparer.Ordinal);
        var explicitSourceAliasKeys = new HashSet<string>(StringComparer.Ordinal);
        foreach (string file in WorkspaceTraversal.EnumerateFiles(projectDirectory, "*.cs"))
        {
            if (IsGeneratedOrBuildOutput(projectDirectory, file))
            {
                continue;
            }

            string source = File.ReadAllText(file);
            foreach (Match match in ScheduleOneUsingAliasRegex.Matches(source))
            {
                string alias = match.Groups["alias"].Value;
                string monoType = ToMonoTypeName(match.Groups["type"].Value);
                if (string.IsNullOrWhiteSpace(alias) ||
                    string.Equals(alias, monoType.Split('.').LastOrDefault(), StringComparison.Ordinal))
                {
                    continue;
                }

                if (!monoTypesByAlias.TryGetValue(alias, out SortedSet<string>? monoTypes))
                {
                    monoTypes = new SortedSet<string>(StringComparer.Ordinal);
                    monoTypesByAlias[alias] = monoTypes;
                }

                monoTypes.Add(monoType);
                explicitSourceAliasKeys.Add(GetAliasKey(alias, monoType));
            }

            foreach (Match match in FullyQualifiedScheduleOneTypeRegex.Matches(source))
            {
                string type = match.Groups["type"].Value;
                if (IsUsingDirectiveMatch(source, match.Index))
                {
                    continue;
                }

                string monoType = ToMonoTypeName(type);
                string[] parts = monoType.Split('.');
                string alias = parts.Last();
                if (string.IsNullOrWhiteSpace(alias))
                {
                    continue;
                }

                if (parts.Length >= 2 && string.Equals(parts[^2], alias, StringComparison.Ordinal))
                {
                    continue;
                }

                if (!monoTypesByAlias.TryGetValue(alias, out SortedSet<string>? monoTypes))
                {
                    monoTypes = new SortedSet<string>(StringComparer.Ordinal);
                    monoTypesByAlias[alias] = monoTypes;
                }

                monoTypes.Add(monoType);
            }
        }

        return monoTypesByAlias
            .Where(pair => pair.Value.Count == 1)
            .Select(pair =>
            {
                string monoType = pair.Value.Single();
                bool generateGlobalUsing = !explicitSourceAliasKeys.Contains(GetAliasKey(pair.Key, monoType));
                return new SdkTypeAlias(pair.Key, monoType, $"Il2Cpp{monoType}", generateGlobalUsing);
            })
            .OrderBy(alias => alias.Alias, StringComparer.Ordinal)
            .ToArray();
    }

    private static string GetAliasKey(string alias, string monoType) => $"{alias}\n{monoType}";

    private static string ToMonoTypeName(string type) =>
        type.StartsWith("Il2Cpp", StringComparison.Ordinal)
            ? type["Il2Cpp".Length..]
            : type;

    private static bool IsUsingDirectiveMatch(string source, int matchIndex)
    {
        int lineStart = source.LastIndexOf('\n', Math.Max(0, matchIndex - 1));
        lineStart = lineStart < 0 ? 0 : lineStart + 1;
        string prefix = source[lineStart..matchIndex];
        return prefix.TrimStart().StartsWith("using ", StringComparison.Ordinal);
    }

    private static bool IsGeneratedOrBuildOutput(string projectDirectory, string file)
    {
        return WorkspaceTraversal.HasExcludedPathPart(projectDirectory, file);
    }

    private static string Escape(string value) =>
        value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal);
}
