using System.Reflection.Metadata;
using System.Reflection.PortableExecutable;
using System.Text;
using System.Text.RegularExpressions;

using S1Interop.Core;

namespace S1Interop.Core.Generators;

public sealed class SdkFacadeGenerator
{
    private static readonly Regex ScheduleOneUsingRegex = new(
        @"^\s*using\s+(?<namespace>(?:Il2Cpp)?ScheduleOne(?:\.[A-Za-z_][A-Za-z0-9_]*)*)\s*;",
        RegexOptions.Compiled | RegexOptions.Multiline);

    private static readonly Regex FullyQualifiedScheduleOneTypeRegex = new(
        @"(?<![A-Za-z0-9_])(?<type>(?:Il2Cpp)?ScheduleOne(?:\.[A-Za-z_][A-Za-z0-9_]*){2,})",
        RegexOptions.Compiled);

    private static readonly Regex ScheduleOneUsingAliasRegex = new(
        @"^\s*using\s+(?<alias>[A-Za-z_][A-Za-z0-9_]*)\s*=\s*(?<type>(?:Il2Cpp)?ScheduleOne(?:\.[A-Za-z_][A-Za-z0-9_]*){1,})\s*;",
        RegexOptions.Compiled | RegexOptions.Multiline);

    private static readonly Regex LocalTypeDeclarationRegex = new(
        @"\b(?:class|struct|interface|enum|record)\s+(?<name>[A-Z][A-Za-z0-9_]*)\b",
        RegexOptions.Compiled);

    private static readonly Regex SimpleTypeUsageRegex = new(
        @"(?<![A-Za-z0-9_\.])(?<type>[A-Z][A-Za-z0-9_]*)(?:\s*<[^;\r\n{}()]+>)?\s+[A-Za-z_@][A-Za-z0-9_]*|(?<![A-Za-z0-9_\.])(?<type>[A-Z][A-Za-z0-9_]*)\s*\.\s*[A-Za-z_][A-Za-z0-9_]*|\b(?:new|typeof)\s*\(?\s*(?<type>[A-Z][A-Za-z0-9_]*)|<\s*(?<type>[A-Z][A-Za-z0-9_]*)\s*>",
        RegexOptions.Compiled);

    public SdkFacadePlan Plan(ProjectAnalysis project)
    {
        string projectDirectory = Path.GetDirectoryName(project.ProjectPath)!;
        string outputPath = Path.Combine(projectDirectory, "S1Interop.Generated", "S1Interop.GlobalUsings.g.cs");
        IReadOnlyList<string> namespaces = DiscoverScheduleOneNamespaces(projectDirectory);
        IReadOnlyList<SdkTypeAlias> aliases = DiscoverTypeAliases(projectDirectory, project);
        return new SdkFacadePlan(project.ProjectPath, outputPath, namespaces, aliases, namespaces.Count > 0 || aliases.Count > 0);
    }

    public string GenerateSource(SdkFacadePlan plan)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("// Generated by S1Interop. Do not edit by hand.");
        builder.AppendLine();
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        foreach (string ns in plan.ScheduleOneNamespaces.OrderBy(value => value, StringComparer.OrdinalIgnoreCase))
        {
            string il2CppNamespace = $"Il2Cpp{ns}";
            builder.AppendLine("#if MONO");
            builder.AppendLine($"global using {ns};");
            builder.AppendLine("#elif IL2CPP");
            builder.AppendLine($"global using {il2CppNamespace};");
            builder.AppendLine("#endif");
            builder.AppendLine();
        }

        foreach (SdkTypeAlias alias in plan.TypeAliases
                     .Where(alias => alias.GenerateGlobalUsing)
                     .OrderBy(value => value.Alias, StringComparer.OrdinalIgnoreCase))
        {
            builder.AppendLine("#if MONO");
            builder.AppendLine($"global using {alias.Alias} = {alias.MonoType};");
            builder.AppendLine("#elif IL2CPP");
            builder.AppendLine($"global using {alias.Alias} = {alias.Il2CppType};");
            builder.AppendLine("#endif");
            builder.AppendLine();
        }

        foreach (SdkTypeAlias alias in plan.TypeAliases.OrderBy(value => value.Alias, StringComparer.OrdinalIgnoreCase))
        {
            builder.AppendLine($"[assembly: S1Interop.S1InteropType(\"{Escape(alias.MonoType)}\", Alias = \"{Escape(alias.Alias)}\", Il2CppTypeName = \"{Escape(alias.Il2CppType)}\")]");
        }

        if (plan.TypeAliases.Count > 0)
        {
            builder.AppendLine();
        }

        return builder.ToString();
    }

    private static IReadOnlyList<string> DiscoverScheduleOneNamespaces(string projectDirectory)
    {
        if (!Directory.Exists(projectDirectory))
        {
            return Array.Empty<string>();
        }

        var namespaces = new SortedSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (string file in WorkspaceTraversal.EnumerateFiles(projectDirectory, "*.cs"))
        {
            if (IsGeneratedOrBuildOutput(projectDirectory, file))
            {
                continue;
            }

            string source = File.ReadAllText(file);
            foreach (Match match in ScheduleOneUsingRegex.Matches(source))
            {
                string ns = match.Groups["namespace"].Value;
                if (ns.StartsWith("Il2Cpp", StringComparison.Ordinal))
                {
                    ns = ns["Il2Cpp".Length..];
                }

                namespaces.Add(ns);
            }
        }

        return namespaces.ToArray();
    }

    private static IReadOnlyList<SdkTypeAlias> DiscoverTypeAliases(string projectDirectory, ProjectAnalysis project)
    {
        if (!Directory.Exists(projectDirectory))
        {
            return Array.Empty<SdkTypeAlias>();
        }

        var monoTypesByAlias = new Dictionary<string, SortedSet<string>>(StringComparer.Ordinal);
        var explicitSourceAliasKeys = new HashSet<string>(StringComparer.Ordinal);
        var suppressGlobalUsingKeys = new HashSet<string>(StringComparer.Ordinal);
        HashSet<string> localTypeNames = DiscoverLocalTypeNames(projectDirectory);
        HashSet<string> knownScheduleOneTypes = DiscoverKnownScheduleOneTypes(project);
        foreach (string file in WorkspaceTraversal.EnumerateFiles(projectDirectory, "*.cs"))
        {
            if (IsGeneratedOrBuildOutput(projectDirectory, file))
            {
                continue;
            }

            string source = File.ReadAllText(file);
            foreach (Match match in ScheduleOneUsingAliasRegex.Matches(source))
            {
                string alias = match.Groups["alias"].Value;
                string monoType = ToMonoTypeName(match.Groups["type"].Value);
                if (string.IsNullOrWhiteSpace(alias) ||
                    string.Equals(alias, monoType.Split('.').LastOrDefault(), StringComparison.Ordinal))
                {
                    continue;
                }

                if (!monoTypesByAlias.TryGetValue(alias, out SortedSet<string>? monoTypes))
                {
                    monoTypes = new SortedSet<string>(StringComparer.Ordinal);
                    monoTypesByAlias[alias] = monoTypes;
                }

                monoTypes.Add(monoType);
                explicitSourceAliasKeys.Add(GetAliasKey(alias, monoType));
            }

            foreach (Match match in FullyQualifiedScheduleOneTypeRegex.Matches(source))
            {
                string type = match.Groups["type"].Value;
                if (IsUsingDirectiveMatch(source, match.Index))
                {
                    continue;
                }

                string monoType = ToMonoTypeName(type);
                string[] parts = monoType.Split('.');
                string alias = parts.Last();
                if (string.IsNullOrWhiteSpace(alias))
                {
                    continue;
                }

                if (parts.Length >= 2 && string.Equals(parts[^2], alias, StringComparison.Ordinal))
                {
                    continue;
                }

                if (!monoTypesByAlias.TryGetValue(alias, out SortedSet<string>? monoTypes))
                {
                    monoTypes = new SortedSet<string>(StringComparer.Ordinal);
                    monoTypesByAlias[alias] = monoTypes;
                }

                monoTypes.Add(monoType);
            }

            foreach (SdkTypeAlias alias in DiscoverNamespaceScopedAliases(source, localTypeNames, knownScheduleOneTypes))
            {
                AddAliasCandidate(monoTypesByAlias, alias.Alias, alias.MonoType);
                suppressGlobalUsingKeys.Add(GetAliasKey(alias.Alias, alias.MonoType));
            }
        }

        return monoTypesByAlias
            .Where(pair => pair.Value.Count == 1)
            .Select(pair =>
            {
                string monoType = pair.Value.Single();
                string aliasKey = GetAliasKey(pair.Key, monoType);
                bool generateGlobalUsing = !explicitSourceAliasKeys.Contains(aliasKey) &&
                                           !suppressGlobalUsingKeys.Contains(aliasKey);
                return new SdkTypeAlias(pair.Key, monoType, $"Il2Cpp{monoType}", generateGlobalUsing);
            })
            .OrderBy(alias => alias.Alias, StringComparer.Ordinal)
            .ToArray();
    }

    private static string GetAliasKey(string alias, string monoType) => $"{alias}\n{monoType}";

    private static IEnumerable<SdkTypeAlias> DiscoverNamespaceScopedAliases(
        string source,
        HashSet<string> localTypeNames,
        HashSet<string> knownScheduleOneTypes)
    {
        if (knownScheduleOneTypes.Count == 0)
        {
            yield break;
        }

        string[] namespaces = ScheduleOneUsingRegex.Matches(source)
            .Select(match => NormalizeScheduleOneNamespace(match.Groups["namespace"].Value))
            .Where(value => value.StartsWith("ScheduleOne", StringComparison.Ordinal))
            .Distinct(StringComparer.Ordinal)
            .ToArray();
        if (namespaces.Length == 0)
        {
            yield break;
        }

        foreach (string typeName in DiscoverSimpleTypeNames(source))
        {
            if (localTypeNames.Contains(typeName))
            {
                continue;
            }

            foreach (string ns in namespaces)
            {
                string monoType = $"{ns}.{typeName}";
                if (knownScheduleOneTypes.Contains(monoType))
                {
                    yield return new SdkTypeAlias(typeName, monoType, $"Il2Cpp{monoType}", GenerateGlobalUsing: false);
                }
            }
        }
    }

    private static HashSet<string> DiscoverSimpleTypeNames(string source)
    {
        var typeNames = new HashSet<string>(StringComparer.Ordinal);
        foreach (Match match in SimpleTypeUsageRegex.Matches(source))
        {
            foreach (Capture capture in match.Groups["type"].Captures)
            {
                string typeName = capture.Value;
                if (!string.IsNullOrWhiteSpace(typeName))
                {
                    typeNames.Add(typeName);
                }
            }
        }

        return typeNames;
    }

    private static HashSet<string> DiscoverLocalTypeNames(string projectDirectory)
    {
        var typeNames = new HashSet<string>(StringComparer.Ordinal);
        foreach (string file in WorkspaceTraversal.EnumerateFiles(projectDirectory, "*.cs"))
        {
            if (IsGeneratedOrBuildOutput(projectDirectory, file))
            {
                continue;
            }

            string source = File.ReadAllText(file);
            foreach (Match match in LocalTypeDeclarationRegex.Matches(source))
            {
                typeNames.Add(match.Groups["name"].Value);
            }
        }

        return typeNames;
    }

    private static HashSet<string> DiscoverKnownScheduleOneTypes(ProjectAnalysis project)
    {
        var typeNames = new HashSet<string>(StringComparer.Ordinal);
        foreach (string path in project.Configurations
                     .SelectMany(configuration => configuration.References)
                     .Select(reference => reference.HintPath)
                     .Where(path => !string.IsNullOrWhiteSpace(path))
                     .Select(path => path!)
                     .Distinct(StringComparer.OrdinalIgnoreCase))
        {
            AddKnownTypesFromAssembly(path, typeNames);
        }

        return typeNames;
    }

    private static void AddKnownTypesFromAssembly(string path, HashSet<string> typeNames)
    {
        if (!File.Exists(path))
        {
            return;
        }

        try
        {
            using FileStream stream = File.OpenRead(path);
            using var reader = new PEReader(stream);
            if (!reader.HasMetadata)
            {
                return;
            }

            MetadataReader metadata = reader.GetMetadataReader();
            foreach (TypeDefinitionHandle handle in metadata.TypeDefinitions)
            {
                TypeDefinition definition = metadata.GetTypeDefinition(handle);
                string ns = metadata.GetString(definition.Namespace);
                string name = metadata.GetString(definition.Name);
                string? typeName = NormalizeMetadataTypeName(ns, name);
                if (typeName is not null)
                {
                    typeNames.Add(typeName);
                }
            }
        }
        catch
        {
        }
    }

    private static string? NormalizeMetadataTypeName(string ns, string name)
    {
        if (string.IsNullOrWhiteSpace(ns) ||
            string.IsNullOrWhiteSpace(name) ||
            name.StartsWith("<", StringComparison.Ordinal))
        {
            return null;
        }

        if (name.Contains('`', StringComparison.Ordinal))
        {
            name = name[..name.IndexOf('`')];
        }

        string fullName = ToMonoTypeName($"{ns}.{name}");
        return fullName.StartsWith("ScheduleOne.", StringComparison.Ordinal) ? fullName : null;
    }

    private static string NormalizeScheduleOneNamespace(string ns) =>
        ns.StartsWith("Il2Cpp", StringComparison.Ordinal)
            ? ns["Il2Cpp".Length..]
            : ns;

    private static void AddAliasCandidate(
        Dictionary<string, SortedSet<string>> monoTypesByAlias,
        string alias,
        string monoType)
    {
        if (!monoTypesByAlias.TryGetValue(alias, out SortedSet<string>? monoTypes))
        {
            monoTypes = new SortedSet<string>(StringComparer.Ordinal);
            monoTypesByAlias[alias] = monoTypes;
        }

        monoTypes.Add(monoType);
    }

    private static string ToMonoTypeName(string type) =>
        type.StartsWith("Il2Cpp", StringComparison.Ordinal)
            ? type["Il2Cpp".Length..]
            : type;

    private static bool IsUsingDirectiveMatch(string source, int matchIndex)
    {
        int lineStart = source.LastIndexOf('\n', Math.Max(0, matchIndex - 1));
        lineStart = lineStart < 0 ? 0 : lineStart + 1;
        string prefix = source[lineStart..matchIndex];
        return prefix.TrimStart().StartsWith("using ", StringComparison.Ordinal);
    }

    private static bool IsGeneratedOrBuildOutput(string projectDirectory, string file)
    {
        return WorkspaceTraversal.HasExcludedPathPart(projectDirectory, file);
    }

    private static string Escape(string value) =>
        value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal);
}
