<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="../../build/S1Interop.Compiler.props" LogicalName="Compiler.props" />
    <EmbeddedResource Include="../../build/S1Interop.Compiler.targets" LogicalName="Compiler.targets" />
  </ItemGroup>
</Project>
